CREATE TABLE IF NOT EXISTS `erp_sale_order` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `creator` varchar(64) NULL DEFAULT '',
  `updater` varchar(64) NULL DEFAULT '',
  `deleted` bit(1) NOT NULL DEFAULT 0,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `no` longtext NULL,
  `status` int NULL,
  `customer_id` bigint NULL,
  `account_id` bigint NULL,
  `sale_user_id` bigint NULL,
  `order_time` datetime(6) NULL,
  `total_count` decimal(24,6) NULL,
  `total_price` decimal(24,6) NULL,
  `total_product_price` decimal(24,6) NULL,
  `total_tax_price` decimal(24,6) NULL,
  `discount_percent` decimal(24,6) NULL,
  `discount_price` decimal(24,6) NULL,
  `deposit_price` decimal(24,6) NULL,
  `file_url` longtext NULL,
  `remark` longtext NULL,
  `out_count` decimal(24,6) NULL,
  `return_count` decimal(24,6) NULL,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `erp_sale_order_items` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `creator` varchar(64) NULL DEFAULT '',
  `updater` varchar(64) NULL DEFAULT '',
  `deleted` bit(1) NOT NULL DEFAULT 0,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `order_id` bigint NULL,
  `product_id` bigint NULL,
  `product_unit_id` bigint NULL,
  `product_price` decimal(24,6) NULL,
  `count` decimal(24,6) NULL,
  `total_price` decimal(24,6) NULL,
  `tax_percent` decimal(24,6) NULL,
  `tax_price` decimal(24,6) NULL,
  `remark` longtext NULL,
  `out_count` decimal(24,6) NULL,
  `return_count` decimal(24,6) NULL,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);
