-- Generated by sql/tools/schema/generate.py; see sql/mysql/modules/README.md.
-- Development schema reconstructed from entities; contains no seed data.
-- Existing tables are preserved; this is NOT an ALTER/migration script.
SET NAMES utf8mb4;

-- Entity: yudao-module-ai/src/main/java/cn/iocoder/yudao/module/ai/dal/dataobject/model/AiApiKeyDO.java
CREATE TABLE IF NOT EXISTS `ai_api_key` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `name` longtext NULL COMMENT '名称',
  `api_key` longtext NULL COMMENT '密钥',
  `platform` longtext NULL COMMENT '平台',
  `url` longtext NULL COMMENT 'API 地址',
  `status` int NULL COMMENT '状态',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='AI API 秘钥 DO';

-- Entity: yudao-module-ai/src/main/java/cn/iocoder/yudao/module/ai/dal/dataobject/chat/AiChatConversationDO.java
CREATE TABLE IF NOT EXISTS `ai_chat_conversation` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID 编号，自增',
  `user_id` bigint NULL COMMENT '用户编号',
  `title` longtext NULL COMMENT '对话标题',
  `pinned` bit(1) NULL COMMENT '是否置顶',
  `pinned_time` datetime(6) NULL COMMENT '置顶时间',
  `role_id` bigint NULL COMMENT '角色编号',
  `model_id` bigint NULL COMMENT '模型编号',
  `model` longtext NULL COMMENT '模型标志',
  `system_message` longtext NULL COMMENT '角色设定',
  `temperature` double NULL COMMENT '温度参数',
  `max_tokens` int NULL COMMENT '单条回复的最大 Token 数量',
  `max_contexts` int NULL COMMENT '上下文的最大 Message 数量',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_user_id` (`tenant_id`, `user_id`),
  KEY `idx_role_id` (`tenant_id`, `role_id`),
  KEY `idx_model_id` (`tenant_id`, `model_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='AI Chat 对话 DO';

-- Entity: yudao-module-ai/src/main/java/cn/iocoder/yudao/module/ai/dal/dataobject/chat/AiChatMessageDO.java
CREATE TABLE IF NOT EXISTS `ai_chat_message` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号，作为每条聊天记录的唯一标识符',
  `conversation_id` bigint NULL COMMENT '对话编号',
  `reply_id` bigint NULL COMMENT '回复消息编号',
  `type` longtext NULL COMMENT '消息类型',
  `user_id` bigint NULL COMMENT '用户编号',
  `role_id` bigint NULL COMMENT '角色编号',
  `model` longtext NULL COMMENT '模型标志',
  `model_id` bigint NULL COMMENT '模型编号',
  `content` longtext NULL COMMENT '聊天内容',
  `reasoning_content` longtext NULL COMMENT '推理内容',
  `use_context` bit(1) NULL COMMENT '是否携带上下文',
  `segment_ids` text NULL COMMENT '知识库段落编号数组',
  `web_search_pages` json NULL COMMENT '联网搜索的网页内容数组',
  `attachment_urls` text NULL COMMENT '附件 URL 数组',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_conversation_id` (`tenant_id`, `conversation_id`),
  KEY `idx_reply_id` (`tenant_id`, `reply_id`),
  KEY `idx_user_id` (`tenant_id`, `user_id`),
  KEY `idx_role_id` (`tenant_id`, `role_id`),
  KEY `idx_model_id` (`tenant_id`, `model_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='AI Chat 消息 DO';

-- Entity: yudao-module-ai/src/main/java/cn/iocoder/yudao/module/ai/dal/dataobject/model/AiChatRoleDO.java
CREATE TABLE IF NOT EXISTS `ai_chat_role` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `name` longtext NULL COMMENT '角色名称',
  `avatar` longtext NULL COMMENT '角色头像',
  `category` longtext NULL COMMENT '角色分类',
  `description` longtext NULL COMMENT '角色描述',
  `system_message` longtext NULL COMMENT '角色设定',
  `user_id` bigint NULL COMMENT '用户编号',
  `model_id` bigint NULL COMMENT '模型编号',
  `knowledge_ids` text NULL COMMENT '引用的知识库编号列表',
  `tool_ids` text NULL COMMENT '引用的工具编号列表',
  `mcp_client_names` text NULL COMMENT '引用的 MCP Client 名字列表',
  `public_status` bit(1) NULL COMMENT '是否公开',
  `sort` int NULL COMMENT '排序值',
  `status` int NULL COMMENT '状态',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_user_id` (`tenant_id`, `user_id`),
  KEY `idx_model_id` (`tenant_id`, `model_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='AI 聊天角色 DO';

-- Entity: yudao-module-ai/src/main/java/cn/iocoder/yudao/module/ai/dal/dataobject/image/AiImageDO.java
CREATE TABLE IF NOT EXISTS `ai_image` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `user_id` bigint NULL COMMENT '用户编号',
  `prompt` longtext NULL COMMENT '提示词',
  `platform` longtext NULL COMMENT '平台',
  `model_id` bigint NULL COMMENT '模型编号',
  `model` longtext NULL COMMENT '模型标识',
  `width` int NULL COMMENT '图片宽度',
  `height` int NULL COMMENT '图片高度',
  `status` int NULL COMMENT '生成状态',
  `finish_time` datetime(6) NULL COMMENT '完成时间',
  `error_message` longtext NULL COMMENT '绘画错误信息',
  `pic_url` longtext NULL COMMENT '图片地址',
  `public_status` bit(1) NULL COMMENT '是否公开',
  `options` json NULL COMMENT '绘制参数，不同 platform 的不同参数',
  `buttons` json NULL COMMENT 'mj buttons 按钮',
  `task_id` longtext NULL COMMENT '任务编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_user_id` (`tenant_id`, `user_id`),
  KEY `idx_model_id` (`tenant_id`, `model_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='AI 绘画 DO';

-- Entity: yudao-module-ai/src/main/java/cn/iocoder/yudao/module/ai/dal/dataobject/knowledge/AiKnowledgeDO.java
CREATE TABLE IF NOT EXISTS `ai_knowledge` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `name` longtext NULL COMMENT '知识库名称',
  `description` longtext NULL COMMENT '知识库描述',
  `embedding_model_id` bigint NULL COMMENT '向量模型编号',
  `embedding_model` longtext NULL COMMENT '模型标识',
  `top_k` int NULL COMMENT 'topK',
  `similarity_threshold` double NULL COMMENT '相似度阈值',
  `status` int NULL COMMENT '状态',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_embedding_model_id` (`tenant_id`, `embedding_model_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='AI 知识库 DO';

-- Entity: yudao-module-ai/src/main/java/cn/iocoder/yudao/module/ai/dal/dataobject/knowledge/AiKnowledgeDocumentDO.java
CREATE TABLE IF NOT EXISTS `ai_knowledge_document` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `knowledge_id` bigint NULL COMMENT '知识库编号',
  `name` longtext NULL COMMENT '文档名称',
  `url` longtext NULL COMMENT '文件 URL',
  `content` longtext NULL COMMENT '内容',
  `content_length` int NULL COMMENT '文档长度',
  `tokens` int NULL COMMENT '文档 token 数量',
  `segment_max_tokens` int NULL COMMENT '分片最大 Token 数',
  `retrieval_count` int NULL COMMENT '召回次数',
  `status` int NULL COMMENT '状态',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_knowledge_id` (`tenant_id`, `knowledge_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='AI 知识库-文档 DO';

-- Entity: yudao-module-ai/src/main/java/cn/iocoder/yudao/module/ai/dal/dataobject/knowledge/AiKnowledgeSegmentDO.java
CREATE TABLE IF NOT EXISTS `ai_knowledge_segment` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `knowledge_id` bigint NULL COMMENT '知识库编号',
  `document_id` bigint NULL COMMENT '文档编号',
  `content` longtext NULL COMMENT '切片内容',
  `content_length` int NULL COMMENT '切片内容长度',
  `vector_id` longtext NULL COMMENT '向量库的编号',
  `tokens` int NULL COMMENT 'token 数量',
  `retrieval_count` int NULL COMMENT '召回次数',
  `status` int NULL COMMENT '状态',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_knowledge_id` (`tenant_id`, `knowledge_id`),
  KEY `idx_document_id` (`tenant_id`, `document_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='AI 知识库-文档分段 DO';

-- Entity: yudao-module-ai/src/main/java/cn/iocoder/yudao/module/ai/dal/dataobject/mindmap/AiMindMapDO.java
CREATE TABLE IF NOT EXISTS `ai_mind_map` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `user_id` bigint NULL COMMENT '用户编号',
  `platform` longtext NULL COMMENT '平台',
  `model_id` bigint NULL COMMENT '模型编号',
  `model` longtext NULL COMMENT '模型',
  `prompt` longtext NULL COMMENT '生成内容提示',
  `generated_content` longtext NULL COMMENT '生成的内容',
  `error_message` longtext NULL COMMENT '错误信息',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_user_id` (`tenant_id`, `user_id`),
  KEY `idx_model_id` (`tenant_id`, `model_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='AI 思维导图 DO';

-- Entity: yudao-module-ai/src/main/java/cn/iocoder/yudao/module/ai/dal/dataobject/model/AiModelDO.java
CREATE TABLE IF NOT EXISTS `ai_model` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `key_id` bigint NULL COMMENT 'API 秘钥编号',
  `name` longtext NULL COMMENT '模型名称',
  `model` longtext NULL COMMENT '模型标志',
  `platform` longtext NULL COMMENT '平台',
  `type` int NULL COMMENT '类型',
  `sort` int NULL COMMENT '排序值',
  `status` int NULL COMMENT '状态',
  `temperature` double NULL COMMENT '温度参数',
  `max_tokens` int NULL COMMENT '单条回复的最大 Token 数量',
  `max_contexts` int NULL COMMENT '上下文的最大 Message 数量',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_key_id` (`tenant_id`, `key_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='AI 模型 DO';

-- Entity: yudao-module-ai/src/main/java/cn/iocoder/yudao/module/ai/dal/dataobject/music/AiMusicDO.java
CREATE TABLE IF NOT EXISTS `ai_music` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `user_id` bigint NULL COMMENT '用户编号',
  `title` longtext NULL COMMENT '音乐名称',
  `lyric` longtext NULL COMMENT '歌词',
  `image_url` longtext NULL COMMENT '图片地址',
  `audio_url` longtext NULL COMMENT '音频地址',
  `video_url` longtext NULL COMMENT '视频地址',
  `status` int NULL COMMENT '音乐状态',
  `generate_mode` int NULL COMMENT '生成模式',
  `description` longtext NULL COMMENT '描述词',
  `platform` longtext NULL COMMENT '平台',
  `model` longtext NULL COMMENT '模型',
  `tags` json NULL COMMENT '音乐风格标签',
  `duration` double NULL COMMENT '音乐时长',
  `public_status` bit(1) NULL COMMENT '是否公开',
  `task_id` longtext NULL COMMENT '任务编号',
  `error_message` longtext NULL COMMENT '错误信息',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_user_id` (`tenant_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='AI 音乐 DO';

-- Entity: yudao-module-ai/src/main/java/cn/iocoder/yudao/module/ai/dal/dataobject/model/AiToolDO.java
CREATE TABLE IF NOT EXISTS `ai_tool` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '工具编号',
  `name` longtext NULL COMMENT '工具名称',
  `description` longtext NULL COMMENT '工具描述',
  `status` int NULL COMMENT '状态',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='AI 工具 DO';

-- Entity: yudao-module-ai/src/main/java/cn/iocoder/yudao/module/ai/dal/dataobject/workflow/AiWorkflowDO.java
CREATE TABLE IF NOT EXISTS `ai_workflow` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `name` longtext NULL COMMENT '工作流名称',
  `code` longtext NULL COMMENT '工作流标识',
  `graph` longtext NULL COMMENT '工作流模型 JSON 数据',
  `remark` longtext NULL COMMENT '备注',
  `status` int NULL COMMENT '状态',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='AI 工作流 DO';

-- Entity: yudao-module-ai/src/main/java/cn/iocoder/yudao/module/ai/dal/dataobject/write/AiWriteDO.java
CREATE TABLE IF NOT EXISTS `ai_write` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `user_id` bigint NULL COMMENT '用户编号',
  `type` int NULL COMMENT '写作类型',
  `platform` longtext NULL COMMENT '平台',
  `model_id` bigint NULL COMMENT '模型编号',
  `model` longtext NULL COMMENT '模型',
  `prompt` longtext NULL COMMENT '生成内容提示',
  `generated_content` longtext NULL COMMENT '生成的内容',
  `original_content` longtext NULL COMMENT '原文',
  `length` int NULL COMMENT '长度提示词',
  `format` int NULL COMMENT '格式提示词',
  `tone` int NULL COMMENT '语气提示词',
  `language` int NULL COMMENT '语言提示词',
  `error_message` longtext NULL COMMENT '错误信息',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_user_id` (`tenant_id`, `user_id`),
  KEY `idx_model_id` (`tenant_id`, `model_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='AI 写作 DO';
