-- Generated by sql/tools/schema/generate.py; see sql/mysql/modules/README.md.
-- Development schema reconstructed from entities; contains no seed data.
-- Existing tables are preserved; this is NOT an ALTER/migration script.
SET NAMES utf8mb4;

-- Entity: yudao-module-bpm/src/main/java/cn/iocoder/yudao/module/bpm/dal/dataobject/definition/BpmCategoryDO.java
-- Schema hints: yudao-module-bpm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `bpm_category` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '分类编号',
  `name` varchar(63) NULL COMMENT '分类名',
  `code` varchar(63) NULL COMMENT '分类标志',
  `description` varchar(255) NULL COMMENT '分类描述',
  `status` int NULL COMMENT '分类状态',
  `sort` int NULL COMMENT '分类排序',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='BPM 流程分类 DO';

-- Entity: yudao-module-bpm/src/main/java/cn/iocoder/yudao/module/bpm/dal/dataobject/definition/BpmFormDO.java
-- Schema hints: yudao-module-bpm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `bpm_form` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `name` varchar(63) NULL COMMENT '表单名',
  `status` int NULL COMMENT '状态',
  `conf` varchar(255) NULL COMMENT '表单的配置',
  `fields` json NULL COMMENT '表单项的数组',
  `remark` varchar(255) NULL COMMENT '备注',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='BPM 工作流的表单定义';

-- Entity: yudao-module-bpm/src/main/java/cn/iocoder/yudao/module/bpm/dal/dataobject/oa/BpmOALeaveDO.java
CREATE TABLE IF NOT EXISTS `bpm_oa_leave` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '请假表单主键',
  `user_id` bigint NULL COMMENT '申请人的用户编号',
  `type` int NULL COMMENT '请假类型',
  `reason` longtext NULL COMMENT '原因',
  `start_time` datetime(6) NULL COMMENT '开始时间',
  `end_time` datetime(6) NULL COMMENT '结束时间',
  `day` bigint NULL COMMENT '请假天数',
  `status` int NULL COMMENT '审批结果',
  `process_instance_id` longtext NULL COMMENT '对应的流程编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_user_id` (`tenant_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='OA 请假申请 DO';

-- Entity: yudao-module-bpm/src/main/java/cn/iocoder/yudao/module/bpm/dal/dataobject/definition/BpmProcessDefinitionInfoDO.java
CREATE TABLE IF NOT EXISTS `bpm_process_definition_info` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `process_definition_id` longtext NULL COMMENT '流程定义的编号',
  `model_id` longtext NULL COMMENT '流程模型的编号',
  `model_type` int NULL COMMENT '流程模型的类型',
  `category` longtext NULL COMMENT '流程分类的编码',
  `icon` longtext NULL COMMENT '图标',
  `description` longtext NULL COMMENT '描述',
  `form_type` int NULL COMMENT '表单类型',
  `form_id` bigint NULL COMMENT '动态表单编号',
  `form_conf` longtext NULL COMMENT '表单的配置',
  `form_fields` json NULL COMMENT '表单项的数组',
  `form_custom_create_path` longtext NULL COMMENT '自定义表单的提交路径，使用 Vue 的路由地址',
  `form_custom_view_path` longtext NULL COMMENT '自定义表单的查看路径，使用 Vue 的路由地址',
  `simple_model` longtext NULL COMMENT 'SIMPLE 设计器模型数据 json 格式',
  `visible` bit(1) NULL COMMENT '是否可见',
  `sort` bigint NULL COMMENT '排序值',
  `start_user_ids` text NULL COMMENT '可发起用户编号数组',
  `start_dept_ids` text NULL COMMENT '可发起部门编号数组',
  `manager_user_ids` text NULL COMMENT '可管理用户编号数组',
  `allow_cancel_running_process` bit(1) NULL COMMENT '是否允许撤销审批中的申请',
  `allow_withdraw_task` bit(1) NULL COMMENT '是否允许审批人撤回任务',
  `process_id_rule` json NULL COMMENT '流程 ID 规则',
  `auto_approval_type` int NULL COMMENT '自动去重类型',
  `title_setting` json NULL COMMENT '标题设置',
  `summary_setting` json NULL COMMENT '摘要设置',
  `process_before_trigger_setting` json NULL COMMENT '流程前置通知设置',
  `process_after_trigger_setting` json NULL COMMENT '流程后置通知设置',
  `task_before_trigger_setting` json NULL COMMENT '任务前置通知设置',
  `task_after_trigger_setting` json NULL COMMENT '任务后置通知设置',
  `print_template_setting` json NULL COMMENT '自定义打印模板设置',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_form_id` (`tenant_id`, `form_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='BPM 流程定义的拓信息';

-- Entity: yudao-module-bpm/src/main/java/cn/iocoder/yudao/module/bpm/dal/dataobject/definition/BpmProcessExpressionDO.java
CREATE TABLE IF NOT EXISTS `bpm_process_expression` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `name` longtext NULL COMMENT '表达式名字',
  `status` int NULL COMMENT '表达式状态',
  `expression` longtext NULL COMMENT '表达式',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='BPM 流程表达式 DO';

-- Entity: yudao-module-bpm/src/main/java/cn/iocoder/yudao/module/bpm/dal/dataobject/task/BpmProcessInstanceCopyDO.java
CREATE TABLE IF NOT EXISTS `bpm_process_instance_copy` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `start_user_id` bigint NULL COMMENT '发起人 Id',
  `process_instance_name` longtext NULL COMMENT '流程名',
  `process_instance_id` longtext NULL COMMENT '流程实例的编号',
  `process_definition_id` longtext NULL COMMENT '流程实例的流程定义编号',
  `category` longtext NULL COMMENT '流程分类',
  `activity_id` longtext NULL COMMENT '流程活动的编号',
  `activity_name` longtext NULL COMMENT '流程活动的名字',
  `task_id` longtext NULL COMMENT '流程活动的编号',
  `user_id` bigint NULL COMMENT '用户编号（被抄送的用户编号）',
  `reason` longtext NULL COMMENT '抄送意见',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_start_user_id` (`tenant_id`, `start_user_id`),
  KEY `idx_user_id` (`tenant_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='流程抄送 DO';

-- Entity: yudao-module-bpm/src/main/java/cn/iocoder/yudao/module/bpm/dal/dataobject/definition/BpmProcessListenerDO.java
CREATE TABLE IF NOT EXISTS `bpm_process_listener` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键 ID，自增',
  `name` longtext NULL COMMENT '监听器名字',
  `status` int NULL COMMENT '状态',
  `type` longtext NULL COMMENT '监听类型',
  `event` longtext NULL COMMENT '监听事件',
  `value_type` longtext NULL COMMENT '值类型',
  `value` longtext NULL COMMENT '值',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='BPM 流程监听器 DO';

-- Entity: yudao-module-bpm/src/main/java/cn/iocoder/yudao/module/bpm/dal/dataobject/definition/BpmUserGroupDO.java
-- Schema hints: yudao-module-bpm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `bpm_user_group` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号，自增',
  `name` varchar(63) NULL COMMENT '组名',
  `description` varchar(255) NULL COMMENT '描述',
  `status` int NULL COMMENT '状态',
  `user_ids` json NULL COMMENT '成员用户编号数组',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='BPM 用户组';
