-- Generated by sql/tools/schema/generate.py; see sql/mysql/modules/README.md.
-- Development schema reconstructed from entities; contains no seed data.
-- Existing tables are preserved; this is NOT an ALTER/migration script.
SET NAMES utf8mb4;

-- Entity: yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/business/CrmBusinessDO.java
CREATE TABLE IF NOT EXISTS `crm_business` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `name` longtext NULL COMMENT '商机名称',
  `customer_id` bigint NULL COMMENT '客户编号',
  `follow_up_status` bit(1) NULL COMMENT '跟进状态',
  `contact_last_time` datetime(6) NULL COMMENT '最后跟进时间',
  `contact_next_time` datetime(6) NULL COMMENT '下次联系时间',
  `owner_user_id` bigint NULL COMMENT '负责人的用户编号',
  `status_type_id` bigint NULL COMMENT '商机状态组编号',
  `status_id` bigint NULL COMMENT '商机状态编号',
  `end_status` int NULL COMMENT '结束状态',
  `end_remark` longtext NULL COMMENT '结束时的备注',
  `deal_time` datetime(6) NULL COMMENT '预计成交日期',
  `total_product_price` decimal(24,6) NULL COMMENT '产品总金额，单位：元',
  `discount_percent` decimal(24,6) NULL COMMENT '整单折扣，百分比',
  `total_price` decimal(24,6) NULL COMMENT '商机总金额，单位：元',
  `remark` longtext NULL COMMENT '备注',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_customer_id` (`tenant_id`, `customer_id`),
  KEY `idx_owner_user_id` (`tenant_id`, `owner_user_id`),
  KEY `idx_status_type_id` (`tenant_id`, `status_type_id`),
  KEY `idx_status_id` (`tenant_id`, `status_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='CRM 商机 DO';

-- Entity: yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/business/CrmBusinessProductDO.java
CREATE TABLE IF NOT EXISTS `crm_business_product` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `business_id` bigint NULL COMMENT '商机编号',
  `product_id` bigint NULL COMMENT '产品编号',
  `product_price` decimal(24,6) NULL COMMENT '产品单价，单位：元',
  `business_price` decimal(24,6) NULL COMMENT '商机价格, 单位：元',
  `count` decimal(24,6) NULL COMMENT '数量',
  `total_price` decimal(24,6) NULL COMMENT '总计价格，单位：元',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_business_id` (`tenant_id`, `business_id`),
  KEY `idx_product_id` (`tenant_id`, `product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='CRM 商机产品关联表 DO';

-- Entity: yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/business/CrmBusinessStatusDO.java
CREATE TABLE IF NOT EXISTS `crm_business_status` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `type_id` bigint NULL COMMENT '状态类型编号',
  `name` longtext NULL COMMENT '状态名',
  `percent` int NULL COMMENT '赢单率，百分比',
  `sort` int NULL COMMENT '排序',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_type_id` (`tenant_id`, `type_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='CRM 商机状态 DO';

-- Entity: yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/business/CrmBusinessStatusTypeDO.java
CREATE TABLE IF NOT EXISTS `crm_business_status_type` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` longtext NULL COMMENT '状态类型名',
  `dept_ids` text NULL COMMENT '使用的部门编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='CRM 商机状态组 DO';

-- Entity: yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/clue/CrmClueDO.java
CREATE TABLE IF NOT EXISTS `crm_clue` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号，主键自增',
  `name` longtext NULL COMMENT '线索名称',
  `follow_up_status` bit(1) NULL COMMENT '跟进状态',
  `contact_last_time` datetime(6) NULL COMMENT '最后跟进时间',
  `contact_last_content` longtext NULL COMMENT '最后跟进内容',
  `contact_next_time` datetime(6) NULL COMMENT '下次联系时间',
  `owner_user_id` bigint NULL COMMENT '负责人的用户编号',
  `transform_status` bit(1) NULL COMMENT '转化状态',
  `customer_id` bigint NULL COMMENT '客户编号',
  `mobile` longtext NULL COMMENT '手机号',
  `telephone` longtext NULL COMMENT '电话',
  `qq` longtext NULL COMMENT 'QQ',
  `wechat` longtext NULL COMMENT 'wechat',
  `email` longtext NULL COMMENT 'email',
  `area_id` int NULL COMMENT '所在地',
  `detail_address` longtext NULL COMMENT '详细地址',
  `industry_id` int NULL COMMENT '所属行业',
  `level` int NULL COMMENT '客户等级',
  `source` int NULL COMMENT '客户来源',
  `remark` longtext NULL COMMENT '备注',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_owner_user_id` (`tenant_id`, `owner_user_id`),
  KEY `idx_customer_id` (`tenant_id`, `customer_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='CRM 线索 DO';

-- Entity: yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/contact/CrmContactDO.java
CREATE TABLE IF NOT EXISTS `crm_contact` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` longtext NULL COMMENT '联系人姓名',
  `customer_id` bigint NULL COMMENT '客户编号',
  `contact_last_time` datetime(6) NULL COMMENT '最后跟进时间',
  `contact_last_content` longtext NULL COMMENT '最后跟进内容',
  `contact_next_time` datetime(6) NULL COMMENT '下次联系时间',
  `owner_user_id` bigint NULL COMMENT '负责人用户编号',
  `mobile` longtext NULL COMMENT '手机号',
  `telephone` longtext NULL COMMENT '电话',
  `email` longtext NULL COMMENT '电子邮箱',
  `qq` bigint NULL COMMENT 'QQ',
  `wechat` longtext NULL COMMENT '微信',
  `area_id` int NULL COMMENT '所在地',
  `detail_address` longtext NULL COMMENT '详细地址',
  `sex` int NULL COMMENT '性别',
  `master` bit(1) NULL COMMENT '是否关键决策人',
  `post` longtext NULL COMMENT '职位',
  `parent_id` bigint NULL COMMENT '直属上级',
  `remark` longtext NULL COMMENT '备注',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_customer_id` (`tenant_id`, `customer_id`),
  KEY `idx_owner_user_id` (`tenant_id`, `owner_user_id`),
  KEY `idx_parent_id` (`tenant_id`, `parent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='CRM 联系人 DO';

-- Entity: yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/contact/CrmContactBusinessDO.java
CREATE TABLE IF NOT EXISTS `crm_contact_business` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `contact_id` bigint NULL COMMENT '联系人编号',
  `business_id` bigint NULL COMMENT '商机编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_contact_id` (`tenant_id`, `contact_id`),
  KEY `idx_business_id` (`tenant_id`, `business_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='CRM 联系人与商机的关联 DO';

-- Entity: yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/contract/CrmContractDO.java
CREATE TABLE IF NOT EXISTS `crm_contract` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '合同编号',
  `name` longtext NULL COMMENT '合同名称',
  `no` longtext NULL COMMENT '合同编号',
  `customer_id` bigint NULL COMMENT '客户编号',
  `business_id` bigint NULL COMMENT '商机编号，非必须',
  `contact_last_time` datetime(6) NULL COMMENT '最后跟进时间',
  `owner_user_id` bigint NULL COMMENT '负责人的用户编号',
  `process_instance_id` longtext NULL COMMENT '工作流编号',
  `audit_status` int NULL COMMENT '审批状态',
  `order_date` datetime(6) NULL COMMENT '下单日期',
  `start_time` datetime(6) NULL COMMENT '开始时间',
  `end_time` datetime(6) NULL COMMENT '结束时间',
  `total_product_price` decimal(24,6) NULL COMMENT '产品总金额，单位：元',
  `discount_percent` decimal(24,6) NULL COMMENT '整单折扣',
  `total_price` decimal(24,6) NULL COMMENT '合同总金额，单位：分',
  `sign_contact_id` bigint NULL COMMENT '客户签约人，非必须',
  `sign_user_id` bigint NULL COMMENT '公司签约人，非必须',
  `remark` longtext NULL COMMENT '备注',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_customer_id` (`tenant_id`, `customer_id`),
  KEY `idx_business_id` (`tenant_id`, `business_id`),
  KEY `idx_owner_user_id` (`tenant_id`, `owner_user_id`),
  KEY `idx_sign_contact_id` (`tenant_id`, `sign_contact_id`),
  KEY `idx_sign_user_id` (`tenant_id`, `sign_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='CRM 合同 DO';

-- Entity: yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/contract/CrmContractConfigDO.java
CREATE TABLE IF NOT EXISTS `crm_contract_config` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `notify_enabled` bit(1) NULL COMMENT '是否开启提前提醒',
  `notify_days` int NULL COMMENT '提前提醒天数',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='crm_contract_config';

-- Entity: yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/contract/CrmContractProductDO.java
CREATE TABLE IF NOT EXISTS `crm_contract_product` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `contract_id` bigint NULL COMMENT '合同编号',
  `product_id` bigint NULL COMMENT '产品编号',
  `product_price` decimal(24,6) NULL COMMENT '产品单价，单位：元',
  `contract_price` decimal(24,6) NULL COMMENT '合同价格, 单位：元',
  `count` decimal(24,6) NULL COMMENT '数量',
  `total_price` decimal(24,6) NULL COMMENT '总计价格，单位：元',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_contract_id` (`tenant_id`, `contract_id`),
  KEY `idx_product_id` (`tenant_id`, `product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='CRM 合同产品关联表 DO';

-- Entity: yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/customer/CrmCustomerDO.java
CREATE TABLE IF NOT EXISTS `crm_customer` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `name` longtext NULL COMMENT '客户名称',
  `follow_up_status` bit(1) NULL COMMENT '跟进状态',
  `contact_last_time` datetime(6) NULL COMMENT '最后跟进时间',
  `contact_last_content` longtext NULL COMMENT '最后跟进内容',
  `contact_next_time` datetime(6) NULL COMMENT '下次联系时间',
  `owner_user_id` bigint NULL COMMENT '负责人的用户编号',
  `owner_time` datetime(6) NULL COMMENT '成为负责人的时间',
  `lock_status` bit(1) NULL COMMENT '锁定状态',
  `deal_status` bit(1) NULL COMMENT '成交状态',
  `mobile` longtext NULL COMMENT '手机',
  `telephone` longtext NULL COMMENT '电话',
  `qq` longtext NULL COMMENT 'QQ',
  `wechat` longtext NULL COMMENT 'wechat',
  `email` longtext NULL COMMENT 'email',
  `area_id` int NULL COMMENT '所在地',
  `detail_address` longtext NULL COMMENT '详细地址',
  `industry_id` int NULL COMMENT '所属行业',
  `level` int NULL COMMENT '客户等级',
  `source` int NULL COMMENT '客户来源',
  `remark` longtext NULL COMMENT '备注',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_owner_user_id` (`tenant_id`, `owner_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='CRM 客户 DO';

-- Entity: yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/customer/CrmCustomerLimitConfigDO.java
CREATE TABLE IF NOT EXISTS `crm_customer_limit_config` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `type` int NULL COMMENT '规则类型',
  `user_ids` text NULL COMMENT '规则适用人群',
  `dept_ids` text NULL COMMENT '规则适用部门',
  `max_count` int NULL COMMENT '数量上限',
  `deal_count_enabled` bit(1) NULL COMMENT '成交客户是否占有拥有客户数',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='客户限制配置 DO';

-- Entity: yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/customer/CrmCustomerPoolConfigDO.java
CREATE TABLE IF NOT EXISTS `crm_customer_pool_config` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `enabled` bit(1) NULL COMMENT '是否启用客户公海',
  `contact_expire_days` int NULL COMMENT '未跟进放入公海天数',
  `deal_expire_days` int NULL COMMENT '未成交放入公海天数',
  `notify_enabled` bit(1) NULL COMMENT '是否开启提前提醒',
  `notify_days` int NULL COMMENT '提前提醒天数',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='客户公海配置 DO';

-- Entity: yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/followup/CrmFollowUpRecordDO.java
CREATE TABLE IF NOT EXISTS `crm_follow_up_record` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `biz_type` int NULL COMMENT '数据类型',
  `biz_id` bigint NULL COMMENT '数据编号',
  `type` int NULL COMMENT '跟进类型',
  `content` longtext NULL COMMENT '跟进内容',
  `next_time` datetime(6) NULL COMMENT '下次联系时间',
  `pic_urls` text NULL COMMENT '图片',
  `file_urls` text NULL COMMENT '附件',
  `business_ids` text NULL COMMENT '关联的商机编号数组',
  `contact_ids` text NULL COMMENT '关联的联系人编号数组',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_biz_id` (`tenant_id`, `biz_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='跟进记录 DO';

-- Entity: yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/permission/CrmOwnerRecordDO.java
CREATE TABLE IF NOT EXISTS `crm_owner_record` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `biz_type` int NULL COMMENT 'CRM 业务类型',
  `biz_id` bigint NULL COMMENT 'CRM 业务编号',
  `pre_owner_user_id` bigint NULL COMMENT '变更前负责人',
  `post_owner_user_id` bigint NULL COMMENT '变更后负责人',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_biz_id` (`tenant_id`, `biz_id`),
  KEY `idx_pre_owner_user_id` (`tenant_id`, `pre_owner_user_id`),
  KEY `idx_post_owner_user_id` (`tenant_id`, `post_owner_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='CRM 负责人变更记录 DO';

-- Entity: yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/performance/CrmPerformanceConfigDO.java
CREATE TABLE IF NOT EXISTS `crm_performance_config` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `biz_type` int NULL COMMENT '目标类型',
  `object_id` bigint NULL COMMENT '目标对象编号',
  `object_type` int NULL COMMENT '目标对象类型',
  `year` int NULL COMMENT '年份',
  `year_target_price` decimal(24,6) NULL COMMENT '年度目标金额',
  `january_target_price` decimal(24,6) NULL COMMENT '一月目标金额',
  `february_target_price` decimal(24,6) NULL COMMENT '二月目标金额',
  `march_target_price` decimal(24,6) NULL COMMENT '三月目标金额',
  `april_target_price` decimal(24,6) NULL COMMENT '四月目标金额',
  `may_target_price` decimal(24,6) NULL COMMENT '五月目标金额',
  `june_target_price` decimal(24,6) NULL COMMENT '六月目标金额',
  `july_target_price` decimal(24,6) NULL COMMENT '七月目标金额',
  `august_target_price` decimal(24,6) NULL COMMENT '八月目标金额',
  `september_target_price` decimal(24,6) NULL COMMENT '九月目标金额',
  `october_target_price` decimal(24,6) NULL COMMENT '十月目标金额',
  `november_target_price` decimal(24,6) NULL COMMENT '十一月目标金额',
  `december_target_price` decimal(24,6) NULL COMMENT '十二月目标金额',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_object_id` (`tenant_id`, `object_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='CRM 业绩目标 DO';

-- Entity: yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/permission/CrmPermissionDO.java
CREATE TABLE IF NOT EXISTS `crm_permission` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号，主键自增',
  `biz_type` int NULL COMMENT '数据类型',
  `biz_id` bigint NULL COMMENT '数据编号',
  `user_id` bigint NULL COMMENT '用户编号',
  `level` int NULL COMMENT '权限级别',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_biz_id` (`tenant_id`, `biz_id`),
  KEY `idx_user_id` (`tenant_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='CRM 数据权限 DO';

-- Entity: yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/product/CrmProductDO.java
CREATE TABLE IF NOT EXISTS `crm_product` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `name` longtext NULL COMMENT '产品名称',
  `no` longtext NULL COMMENT '产品编码',
  `unit` int NULL COMMENT '单位',
  `price` decimal(24,6) NULL COMMENT '价格，单位：元',
  `status` int NULL COMMENT '状态',
  `category_id` bigint NULL COMMENT '产品分类 ID',
  `description` longtext NULL COMMENT '产品描述',
  `owner_user_id` bigint NULL COMMENT '负责人的用户编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_category_id` (`tenant_id`, `category_id`),
  KEY `idx_owner_user_id` (`tenant_id`, `owner_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='CRM 产品 DO';

-- Entity: yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/product/CrmProductCategoryDO.java
CREATE TABLE IF NOT EXISTS `crm_product_category` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '分类编号',
  `name` longtext NULL COMMENT '分类名称',
  `parent_id` bigint NULL COMMENT '父级编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_parent_id` (`tenant_id`, `parent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='产品分类 DO';

-- Entity: yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/receivable/CrmReceivableDO.java
CREATE TABLE IF NOT EXISTS `crm_receivable` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `no` longtext NULL COMMENT '回款编号',
  `plan_id` bigint NULL COMMENT '回款计划编号',
  `customer_id` bigint NULL COMMENT '客户编号',
  `contract_id` bigint NULL COMMENT '合同编号',
  `owner_user_id` bigint NULL COMMENT '负责人编号，关联 AdminUserRespDTO#getId()',
  `return_time` datetime(6) NULL COMMENT '回款日期',
  `return_type` int NULL COMMENT '回款方式',
  `price` decimal(24,6) NULL COMMENT '计划回款金额，单位：元',
  `remark` longtext NULL COMMENT '备注',
  `process_instance_id` longtext NULL COMMENT '工作流编号',
  `audit_status` int NULL COMMENT '审批状态',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_plan_id` (`tenant_id`, `plan_id`),
  KEY `idx_customer_id` (`tenant_id`, `customer_id`),
  KEY `idx_contract_id` (`tenant_id`, `contract_id`),
  KEY `idx_owner_user_id` (`tenant_id`, `owner_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='回款 DO';

-- Entity: yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/receivable/CrmReceivablePlanDO.java
CREATE TABLE IF NOT EXISTS `crm_receivable_plan` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `period` int NULL COMMENT '期数',
  `customer_id` bigint NULL COMMENT '客户编号',
  `contract_id` bigint NULL COMMENT '合同编号',
  `owner_user_id` bigint NULL COMMENT '负责人编号',
  `return_time` datetime(6) NULL COMMENT '计划回款日期',
  `return_type` int NULL COMMENT '计划回款类型',
  `price` decimal(24,6) NULL COMMENT '计划回款金额，单位：元',
  `receivable_id` bigint NULL COMMENT '回款编号，关联 CrmReceivableDO#getId()',
  `remind_days` int NULL COMMENT '提前几天提醒',
  `remind_time` datetime(6) NULL COMMENT '提醒日期',
  `remark` longtext NULL COMMENT '备注',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_customer_id` (`tenant_id`, `customer_id`),
  KEY `idx_contract_id` (`tenant_id`, `contract_id`),
  KEY `idx_owner_user_id` (`tenant_id`, `owner_user_id`),
  KEY `idx_receivable_id` (`tenant_id`, `receivable_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='CRM 回款计划 DO';
