-- Generated by sql/tools/schema/generate.py; see sql/mysql/modules/README.md.
-- Development schema reconstructed from entities; contains no seed data.
-- Existing tables are preserved; this is NOT an ALTER/migration script.
SET NAMES utf8mb4;

-- Entity: yudao-module-fms/src/main/java/cn/iocoder/yudao/module/fms/dal/dataobject/config/FmsAccountSetDO.java
-- Schema hints: yudao-module-fms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `fms_account_set` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `company_code` varchar(64) NULL DEFAULT NULL COMMENT '公司编码',
  `company_name` varchar(255) NULL DEFAULT NULL COMMENT '公司名称',
  `company_profile` varchar(500) NULL DEFAULT NULL COMMENT '公司简介',
  `industry` varchar(255) NULL DEFAULT NULL COMMENT '所在行业',
  `location` varchar(255) NULL DEFAULT NULL COMMENT '所在地',
  `legal_representative` varchar(255) NULL DEFAULT NULL COMMENT '法人代表',
  `legal_representative_id_number` varchar(255) NULL DEFAULT NULL COMMENT '身份证号',
  `business_license_number` varchar(255) NULL DEFAULT NULL COMMENT '营业执照号',
  `organization_code` varchar(255) NULL DEFAULT NULL COMMENT '组织机构代码',
  `remark` varchar(500) NULL DEFAULT NULL COMMENT '备注',
  `contact_name` varchar(255) NULL DEFAULT NULL COMMENT '联系人',
  `office_telephone` varchar(32) NULL DEFAULT NULL COMMENT '办公电话',
  `mobile` varchar(32) NULL DEFAULT NULL COMMENT '手机号码',
  `fax_number` varchar(32) NULL DEFAULT NULL COMMENT '传真号码',
  `qq_number` varchar(255) NULL DEFAULT NULL COMMENT 'QQ 号码',
  `email` varchar(255) NULL DEFAULT NULL COMMENT '邮箱',
  `other_contact` varchar(255) NULL DEFAULT NULL COMMENT '其他',
  `address` varchar(255) NULL DEFAULT NULL COMMENT '详细地址',
  `currency_id` bigint NULL DEFAULT NULL COMMENT '币种编号',
  `start_time` datetime(6) NULL DEFAULT NULL COMMENT '启用期间',
  `standard` int NULL DEFAULT NULL COMMENT '会计制度',
  `initialized` bit(1) NULL DEFAULT b'0' COMMENT '是否已初始化',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_1` (`company_code`, `deleted`, `tenant_id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_currency_id` (`tenant_id`, `currency_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='FMS 账套 DO';

-- Entity: yudao-module-fms/src/main/java/cn/iocoder/yudao/module/fms/dal/dataobject/config/FmsAccountUserDO.java
-- Schema hints: yudao-module-fms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `fms_account_user` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `account_set_id` bigint NULL DEFAULT NULL COMMENT '账套编号',
  `user_id` bigint NULL DEFAULT NULL COMMENT '后台用户编号',
  `default_status` bit(1) NULL DEFAULT b'0' COMMENT '是否默认账套',
  `founder` bit(1) NULL DEFAULT b'0' COMMENT '是否账套创建人',
  `level` int NULL DEFAULT 2 COMMENT '成员权限级别',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_account_set_id` (`tenant_id`, `account_set_id`),
  KEY `idx_user_id` (`tenant_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='FMS 账套用户 DO';

-- Entity: yudao-module-fms/src/main/java/cn/iocoder/yudao/module/fms/dal/dataobject/config/FmsAuxiliaryCombinationDO.java
-- Schema hints: yudao-module-fms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `fms_assist_combination` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `subject_id` bigint NULL DEFAULT NULL COMMENT '科目编号',
  `account_set_id` bigint NULL DEFAULT NULL COMMENT '账套编号',
  `items` json NULL COMMENT '辅助核算项目数组',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_subject_id` (`tenant_id`, `subject_id`),
  KEY `idx_account_set_id` (`tenant_id`, `account_set_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='FMS 辅助核算组合 DO';

-- Entity: yudao-module-fms/src/main/java/cn/iocoder/yudao/module/fms/dal/dataobject/config/FmsAuxiliaryItemDO.java
-- Schema hints: yudao-module-fms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `fms_auxiliary_item` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `code` varchar(64) NULL DEFAULT NULL COMMENT '编码',
  `name` varchar(255) NULL DEFAULT NULL COMMENT '名称',
  `auxiliary_type_id` bigint NULL DEFAULT NULL COMMENT '辅助核算类别编号',
  `status` int NULL DEFAULT NULL COMMENT '状态',
  `account_set_id` bigint NULL DEFAULT NULL COMMENT '账套编号',
  `remark` varchar(500) NULL DEFAULT NULL COMMENT '备注',
  `specification` varchar(255) NULL DEFAULT NULL COMMENT '规格（存货）',
  `unit` varchar(255) NULL DEFAULT NULL COMMENT '单位（存货）',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_1` (`account_set_id`, `auxiliary_type_id`, `code`, `deleted`, `tenant_id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_auxiliary_type_id` (`tenant_id`, `auxiliary_type_id`),
  KEY `idx_account_set_id` (`tenant_id`, `account_set_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='FMS 辅助核算项目 DO';

-- Entity: yudao-module-fms/src/main/java/cn/iocoder/yudao/module/fms/dal/dataobject/config/FmsAuxiliaryTypeDO.java
-- Schema hints: yudao-module-fms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `fms_auxiliary_type` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `name` varchar(255) NULL DEFAULT NULL COMMENT '辅助核算名称',
  `system_preset` bit(1) NULL DEFAULT b'0' COMMENT '是否系统预置',
  `account_set_id` bigint NULL DEFAULT NULL COMMENT '账套编号',
  `type` int NULL DEFAULT NULL COMMENT '类型',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_1` (`account_set_id`, `name`, `deleted`, `tenant_id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_account_set_id` (`tenant_id`, `account_set_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='FMS 辅助核算类别 DO';

-- Entity: yudao-module-fms/src/main/java/cn/iocoder/yudao/module/fms/dal/dataobject/report/balance/FmsBalanceSheetConfigDO.java
-- Schema hints: yudao-module-fms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `fms_balance_sheet_config` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `name` varchar(255) NULL DEFAULT NULL COMMENT '配置名称',
  `row_no` int NULL DEFAULT NULL COMMENT '行次',
  `formula` longtext NULL COMMENT '公式',
  `remark` varchar(500) NULL DEFAULT NULL COMMENT '备注',
  `editable` bit(1) NULL DEFAULT b'0' COMMENT '是否可编辑',
  `sort` int NULL DEFAULT NULL COMMENT '显示顺序',
  `account_set_id` bigint NULL DEFAULT NULL COMMENT '账套编号',
  `level` int NULL DEFAULT NULL COMMENT '层级',
  `row_id` int NULL DEFAULT NULL COMMENT '行编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_account_set_id` (`tenant_id`, `account_set_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='FMS 资产负债表配置 DO';

-- Entity: yudao-module-fms/src/main/java/cn/iocoder/yudao/module/fms/dal/dataobject/report/balance/FmsBalanceSheetReportDO.java
-- Schema hints: yudao-module-fms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `fms_balance_sheet_report` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `from_period` int NULL DEFAULT NULL COMMENT '开始会计期间，格式为 yyyyMM',
  `to_period` int NULL DEFAULT NULL COMMENT '结束会计期间，格式为 yyyyMM',
  `type` int NULL DEFAULT NULL COMMENT '报表期间类型',
  `level` int NULL DEFAULT NULL COMMENT '层级快照',
  `name` varchar(255) NULL DEFAULT NULL COMMENT '配置名称快照',
  `row_no` int NULL DEFAULT NULL COMMENT '行次快照',
  `formula` longtext NULL COMMENT '公式快照',
  `remark` varchar(500) NULL DEFAULT NULL COMMENT '备注快照',
  `editable` bit(1) NULL DEFAULT b'0' COMMENT '是否可编辑快照',
  `sort` int NULL DEFAULT NULL COMMENT '显示顺序快照',
  `opening_amount` decimal(18,2) NULL DEFAULT 0 COMMENT '期初金额',
  `closing_amount` decimal(18,2) NULL DEFAULT 0 COMMENT '期末金额',
  `account_set_id` bigint NULL DEFAULT NULL COMMENT '账套编号',
  `settled` bit(1) NULL DEFAULT b'0' COMMENT '是否已结账',
  `row_id` int NULL DEFAULT NULL COMMENT '行编号快照',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_account_set_id` (`tenant_id`, `account_set_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='FMS 资产负债表数据 DO';

-- Entity: yudao-module-fms/src/main/java/cn/iocoder/yudao/module/fms/dal/dataobject/report/cashflow/FmsCashFlowExtendConfigDO.java
-- Schema hints: yudao-module-fms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `fms_cash_flow_extend_config` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `name` varchar(255) NULL DEFAULT NULL COMMENT '配置名称',
  `row_no` int NULL DEFAULT NULL COMMENT '行次',
  `formula` longtext NULL COMMENT '公式',
  `remark` varchar(500) NULL DEFAULT NULL COMMENT '备注',
  `category` int NULL DEFAULT NULL COMMENT '表格标识',
  `type` int NULL DEFAULT NULL COMMENT '公式类型',
  `current_amount` decimal(18,2) NULL DEFAULT 0 COMMENT '本期金额',
  `year_amount` decimal(18,2) NULL DEFAULT 0 COMMENT '本年累计金额',
  `editable` bit(1) NULL DEFAULT b'0' COMMENT '是否可编辑',
  `account_set_id` bigint NULL DEFAULT NULL COMMENT '账套编号',
  `sort` int NULL DEFAULT NULL COMMENT '显示顺序',
  `level` int NULL DEFAULT NULL COMMENT '层级',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_account_set_id` (`tenant_id`, `account_set_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='FMS 现金流量表扩展配置 DO';

-- Entity: yudao-module-fms/src/main/java/cn/iocoder/yudao/module/fms/dal/dataobject/report/cashflow/FmsCashFlowExtendDataDO.java
-- Schema hints: yudao-module-fms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `fms_cash_flow_extend_data` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `name` varchar(255) NULL DEFAULT NULL COMMENT '配置名称',
  `row_no` int NULL DEFAULT NULL COMMENT '行次',
  `formula` longtext NULL COMMENT '公式',
  `remark` varchar(500) NULL DEFAULT NULL COMMENT '备注',
  `category` int NULL DEFAULT NULL COMMENT '现金流量表分类',
  `current_amount` decimal(18,2) NULL DEFAULT 0 COMMENT '本期金额',
  `year_amount` decimal(18,2) NULL DEFAULT 0 COMMENT '本年累计金额',
  `from_period` int NULL DEFAULT NULL COMMENT '开始会计期间，格式为 yyyyMM',
  `editable` bit(1) NULL DEFAULT b'0' COMMENT '是否可编辑',
  `account_set_id` bigint NULL DEFAULT NULL COMMENT '账套编号',
  `sort` int NULL DEFAULT NULL COMMENT '显示顺序',
  `to_period` int NULL DEFAULT NULL COMMENT '结束会计期间，格式为 yyyyMM',
  `type` int NULL DEFAULT NULL COMMENT '报表期间类型',
  `level` int NULL DEFAULT NULL COMMENT '层级',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_account_set_id` (`tenant_id`, `account_set_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='FMS 现金流量表扩展数据 DO';

-- Entity: yudao-module-fms/src/main/java/cn/iocoder/yudao/module/fms/dal/dataobject/report/cashflow/FmsCashFlowStatementConfigDO.java
-- Schema hints: yudao-module-fms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `fms_cash_flow_statement_config` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `name` varchar(255) NULL DEFAULT NULL COMMENT '配置名称',
  `row_no` int NULL DEFAULT NULL COMMENT '行次',
  `formula` longtext NULL COMMENT '公式',
  `remark` varchar(500) NULL DEFAULT NULL COMMENT '备注',
  `editable` bit(1) NULL DEFAULT b'0' COMMENT '是否可编辑',
  `sort` int NULL DEFAULT NULL COMMENT '显示顺序',
  `category` int NULL DEFAULT NULL COMMENT '现金流量表分类',
  `account_set_id` bigint NULL DEFAULT NULL COMMENT '账套编号',
  `level` int NULL DEFAULT NULL COMMENT '层级',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_account_set_id` (`tenant_id`, `account_set_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='FMS 现金流量表配置 DO';

-- Entity: yudao-module-fms/src/main/java/cn/iocoder/yudao/module/fms/dal/dataobject/report/cashflow/FmsCashFlowStatementReportDO.java
-- Schema hints: yudao-module-fms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `fms_cash_flow_statement_report` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `from_period` int NULL DEFAULT NULL COMMENT '开始会计期间，格式为 yyyyMM',
  `name` varchar(255) NULL DEFAULT NULL COMMENT '配置名称',
  `row_no` int NULL DEFAULT NULL COMMENT '行次',
  `formula` longtext NULL COMMENT '公式',
  `remark` varchar(500) NULL DEFAULT NULL COMMENT '备注',
  `editable` bit(1) NULL DEFAULT b'0' COMMENT '是否可编辑',
  `current_amount` decimal(18,2) NULL DEFAULT 0 COMMENT '本期金额',
  `year_amount` decimal(18,2) NULL DEFAULT 0 COMMENT '本年累计金额',
  `sort` int NULL DEFAULT NULL COMMENT '显示顺序',
  `category` int NULL DEFAULT NULL COMMENT '现金流量表分类',
  `account_set_id` bigint NULL DEFAULT NULL COMMENT '账套编号',
  `to_period` int NULL DEFAULT NULL COMMENT '结束会计期间，格式为 yyyyMM',
  `type` int NULL DEFAULT NULL COMMENT '报表期间类型',
  `level` int NULL DEFAULT NULL COMMENT '层级',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_account_set_id` (`tenant_id`, `account_set_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='FMS 现金流量表数据 DO';

-- Entity: yudao-module-fms/src/main/java/cn/iocoder/yudao/module/fms/dal/dataobject/closing/FmsClosingSchemeDO.java
-- Schema hints: yudao-module-fms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `fms_closing` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `name` varchar(255) NULL DEFAULT NULL COMMENT '结账名称',
  `period_end` bit(1) NULL DEFAULT b'0' COMMENT '是否期末结转',
  `subject_id` bigint NULL DEFAULT NULL COMMENT '科目编号',
  `formula_rule` int NULL DEFAULT NULL COMMENT '取数规则',
  `time_type` int NULL DEFAULT NULL COMMENT '取数时间类型',
  `voucher_word_id` bigint NULL DEFAULT NULL COMMENT '凭证字编号',
  `digest` varchar(500) NULL DEFAULT NULL COMMENT '凭证摘要',
  `voucher_type` int NULL DEFAULT NULL COMMENT '结转凭证类型',
  `prior_year_adjustment_subject_id` bigint NULL DEFAULT NULL COMMENT '“以前年度损益调整”科目',
  `adjustment_closing_subject_id` bigint NULL DEFAULT NULL COMMENT '“以前年度损益调整”科目的结转科目',
  `other_closing_subject_id` bigint NULL DEFAULT NULL COMMENT '其他损益科目的结转科目',
  `reverse_balance` bit(1) NULL DEFAULT b'0' COMMENT '是否按余额反向结转',
  `type` int NULL DEFAULT NULL COMMENT '类型',
  `account_set_id` bigint NULL DEFAULT NULL COMMENT '账套编号',
  `closing_day` int NULL DEFAULT NULL COMMENT '结转损益日期，最大31，超过31默认最后一天',
  `subject_rules` json NULL COMMENT '结转科目规则数组',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_subject_id` (`tenant_id`, `subject_id`),
  KEY `idx_voucher_word_id` (`tenant_id`, `voucher_word_id`),
  KEY `idx_prior_year_adjustment_subject_id` (`tenant_id`, `prior_year_adjustment_subject_id`),
  KEY `idx_adjustment_closing_subject_id` (`tenant_id`, `adjustment_closing_subject_id`),
  KEY `idx_other_closing_subject_id` (`tenant_id`, `other_closing_subject_id`),
  KEY `idx_account_set_id` (`tenant_id`, `account_set_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='FMS 结账方案 DO';

-- Entity: yudao-module-fms/src/main/java/cn/iocoder/yudao/module/fms/dal/dataobject/closing/FmsClosingPeriodDO.java
-- Schema hints: yudao-module-fms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `fms_closing_period` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `closing_time` datetime(6) NULL DEFAULT NULL COMMENT '结账时间',
  `account_set_id` bigint NULL DEFAULT NULL COMMENT '账套编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_account_set_id` (`tenant_id`, `account_set_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='FMS 结账期间 DO';

-- Entity: yudao-module-fms/src/main/java/cn/iocoder/yudao/module/fms/dal/dataobject/closing/FmsClosingTemplateDO.java
-- Schema hints: yudao-module-fms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `fms_closing_template` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `account_set_id` bigint NULL DEFAULT NULL COMMENT '账套编号',
  `preset_code` varchar(64) NULL DEFAULT NULL COMMENT '系统预置编码',
  `name` varchar(255) NULL DEFAULT NULL COMMENT '模板名称',
  `category` int NULL DEFAULT NULL COMMENT '模板分类',
  `period_end` bit(1) NULL DEFAULT b'0' COMMENT '是否期末结转',
  `subject_id` bigint NULL DEFAULT NULL COMMENT '来源科目编号',
  `formula_rule` int NULL DEFAULT NULL COMMENT '取数规则',
  `time_type` int NULL DEFAULT NULL COMMENT '取数时间类型',
  `subject_rules` json NULL COMMENT '结转科目规则数组',
  `sort` int NULL DEFAULT NULL COMMENT '显示顺序',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  `unique_active` int GENERATED ALWAYS AS (CASE WHEN `deleted` = FALSE THEN 1 ELSE NULL END) COMMENT '来自模块 H2 脚本的生成列',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_fms_closing_template_active` (`account_set_id`, `preset_code`, `unique_active`, `tenant_id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_account_set_id` (`tenant_id`, `account_set_id`),
  KEY `idx_subject_id` (`tenant_id`, `subject_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='FMS 结账模板 DO';

-- Entity: yudao-module-fms/src/main/java/cn/iocoder/yudao/module/fms/dal/dataobject/closing/FmsClosingVoucherDO.java
-- Schema hints: yudao-module-fms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `fms_closing_voucher` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `closing_id` bigint NULL DEFAULT NULL COMMENT '结账方案编号',
  `voucher_id` bigint NULL DEFAULT NULL COMMENT '凭证编号',
  `voucher_time` datetime(6) NULL DEFAULT NULL COMMENT '凭证日期',
  `amount` decimal(24,6) NULL DEFAULT 0 COMMENT '结转金额',
  `closed` bit(1) NULL DEFAULT b'0' COMMENT '是否已结账',
  `account_set_id` bigint NULL DEFAULT NULL COMMENT '账套编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_closing_id` (`tenant_id`, `closing_id`),
  KEY `idx_voucher_id` (`tenant_id`, `voucher_id`),
  KEY `idx_account_set_id` (`tenant_id`, `account_set_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='FMS 结账凭证 DO';

-- Entity: yudao-module-fms/src/main/java/cn/iocoder/yudao/module/fms/dal/dataobject/config/FmsCurrencyDO.java
-- Schema hints: yudao-module-fms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `fms_currency` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `code` varchar(64) NULL DEFAULT NULL COMMENT '编码',
  `name` varchar(255) NULL DEFAULT NULL COMMENT '币种名称',
  `exchange_rate` decimal(18,6) NULL DEFAULT 0 COMMENT '汇率',
  `standard` bit(1) NULL DEFAULT b'0' COMMENT '是否本位币',
  `account_set_id` bigint NULL DEFAULT NULL COMMENT '账套编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_1` (`account_set_id`, `code`, `deleted`, `tenant_id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_account_set_id` (`tenant_id`, `account_set_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='FMS 币别 DO';

-- Entity: yudao-module-fms/src/main/java/cn/iocoder/yudao/module/fms/dal/dataobject/config/FmsDigestDO.java
-- Schema hints: yudao-module-fms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `fms_digest` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `content` varchar(500) NULL COMMENT '摘要内容',
  `account_set_id` bigint NULL COMMENT '账套编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_account_set_id` (`tenant_id`, `account_set_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='FMS 常用摘要 DO';

-- Entity: yudao-module-fms/src/main/java/cn/iocoder/yudao/module/fms/dal/dataobject/config/FmsFinanceIndicatorDO.java
-- Schema hints: yudao-module-fms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `fms_finance_indicator` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `account_set_id` bigint NULL COMMENT '账套编号',
  `name` varchar(100) NULL COMMENT '指标名称',
  `code` varchar(64) NULL COMMENT '指标编码',
  `type` int NULL COMMENT '取数报表类型',
  `formula` varchar(2000) NULL COMMENT '指标公式，支持报表行次公式或科目公式 JSON',
  `sort` int NULL DEFAULT 0 COMMENT '展示顺序',
  `status` int NULL DEFAULT 0 COMMENT '状态',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_account_set_id` (`tenant_id`, `account_set_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='FMS 首页财务指标 DO';

-- Entity: yudao-module-fms/src/main/java/cn/iocoder/yudao/module/fms/dal/dataobject/config/FmsFinanceParameterDO.java
-- Schema hints: yudao-module-fms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `fms_finance_parameter` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `account_set_id` bigint NULL COMMENT '账套编号',
  `level` int NULL COMMENT '科目层级',
  `subject_code_rule` varchar(64) NULL COMMENT '科目编码规则',
  `ledger_balance_mode` int NULL COMMENT '账簿余额方向模式',
  `deficit_check` bit(1) NULL DEFAULT b'0' COMMENT '是否检查现金及银行存款科目赤字',
  `voucher_review_required` bit(1) NULL DEFAULT b'0' COMMENT '结账前是否要求凭证审核',
  `asset_period_locked` bit(1) NULL DEFAULT b'0' COMMENT '生成折旧凭证后是否锁定以前期间资产卡片',
  `taxpayer_name` varchar(255) NULL DEFAULT NULL COMMENT '纳税人名称',
  `taxpayer_number` varchar(64) NULL DEFAULT NULL COMMENT '纳税人识别号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_1` (`account_set_id`, `deleted`, `tenant_id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_account_set_id` (`tenant_id`, `account_set_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='FMS 财务参数 DO';

-- Entity: yudao-module-fms/src/main/java/cn/iocoder/yudao/module/fms/dal/dataobject/report/income/FmsIncomeStatementConfigDO.java
-- Schema hints: yudao-module-fms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `fms_income_statement_config` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `name` varchar(255) NULL DEFAULT NULL COMMENT '配置名称',
  `row_no` int NULL DEFAULT NULL COMMENT '行次',
  `formula` longtext NULL COMMENT '公式',
  `sort` int NULL DEFAULT NULL COMMENT '显示顺序',
  `editable` bit(1) NULL DEFAULT b'0' COMMENT '是否可编辑',
  `account_set_id` bigint NULL DEFAULT NULL COMMENT '账套编号',
  `level` int NULL DEFAULT NULL COMMENT '层级',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_account_set_id` (`tenant_id`, `account_set_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='FMS 利润表配置 DO';

-- Entity: yudao-module-fms/src/main/java/cn/iocoder/yudao/module/fms/dal/dataobject/report/income/FmsIncomeStatementReportDO.java
-- Schema hints: yudao-module-fms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `fms_income_statement_report` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `type` int NULL DEFAULT NULL COMMENT '报表期间类型',
  `from_period` int NULL DEFAULT NULL COMMENT '开始会计期间，格式为 yyyyMM',
  `to_period` int NULL DEFAULT NULL COMMENT '结束会计期间，格式为 yyyyMM',
  `name` varchar(255) NULL DEFAULT NULL COMMENT '配置名称',
  `row_no` int NULL DEFAULT NULL COMMENT '行次',
  `formula` longtext NULL COMMENT '公式',
  `sort` int NULL DEFAULT NULL COMMENT '显示顺序',
  `editable` bit(1) NULL DEFAULT b'0' COMMENT '是否可编辑',
  `current_amount` decimal(18,2) NULL DEFAULT 0 COMMENT '本期金额',
  `year_amount` decimal(18,2) NULL DEFAULT 0 COMMENT '本年累计金额',
  `account_set_id` bigint NULL DEFAULT NULL COMMENT '账套编号',
  `level` int NULL DEFAULT NULL COMMENT '层级',
  `settled` bit(1) NULL DEFAULT b'0' COMMENT '是否已结账',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_account_set_id` (`tenant_id`, `account_set_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='FMS 利润表数据 DO';

-- Entity: yudao-module-fms/src/main/java/cn/iocoder/yudao/module/fms/dal/dataobject/config/FmsInitialBalanceDO.java
-- Schema hints: yudao-module-fms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `fms_initial_balance` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `subject_id` bigint NULL DEFAULT NULL COMMENT '科目编号',
  `auxiliary_accounting` bit(1) NULL DEFAULT b'0' COMMENT '是否启用辅助核算',
  `opening_amount` decimal(18,2) NULL DEFAULT 0 COMMENT '期初金额',
  `opening_quantity` decimal(18,4) NULL DEFAULT 0 COMMENT '期初数量',
  `year_debit_amount` decimal(18,2) NULL DEFAULT 0 COMMENT '本年累计借方金额',
  `year_debit_quantity` decimal(18,4) NULL DEFAULT 0 COMMENT '本年累计借方数量',
  `year_credit_amount` decimal(18,2) NULL DEFAULT 0 COMMENT '本年累计贷方金额',
  `year_credit_quantity` decimal(18,4) NULL DEFAULT 0 COMMENT '本年累计贷方数量',
  `year_opening_amount` decimal(18,2) NULL DEFAULT 0 COMMENT '年初金额',
  `year_opening_quantity` decimal(18,4) NULL DEFAULT 0 COMMENT '年初数量',
  `profit_loss_amount` decimal(18,2) NULL DEFAULT 0 COMMENT '实际损益发生额',
  `profit_loss_quantity` decimal(18,4) NULL DEFAULT 0 COMMENT '实际损益发生数量',
  `account_set_id` bigint NULL DEFAULT NULL COMMENT '账套编号',
  `assist_balances` json NULL COMMENT '辅助核算余额数组',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_1` (`account_set_id`, `subject_id`, `deleted`, `tenant_id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_subject_id` (`tenant_id`, `subject_id`),
  KEY `idx_account_set_id` (`tenant_id`, `account_set_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='FMS 科目期初余额 DO';

-- Entity: yudao-module-fms/src/main/java/cn/iocoder/yudao/module/fms/dal/dataobject/report/FmsReportTemplateDO.java
-- Schema hints: yudao-module-fms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `fms_report_template` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `name` varchar(255) NULL DEFAULT NULL COMMENT '配置名称',
  `row_no` int NULL DEFAULT NULL COMMENT '行次',
  `formula` longtext NULL COMMENT '公式',
  `remark` varchar(500) NULL DEFAULT NULL COMMENT '备注',
  `editable` bit(1) NULL DEFAULT b'0' COMMENT '是否可编辑',
  `sort` int NULL DEFAULT NULL COMMENT '显示顺序',
  `row_id` int NULL DEFAULT NULL COMMENT '行编号',
  `type` int NULL DEFAULT NULL COMMENT '类型',
  `category` int NULL DEFAULT NULL COMMENT '现金流量表分类',
  `level` int NULL DEFAULT NULL COMMENT '层级',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='FMS 报表模板 DO';

-- Entity: yudao-module-fms/src/main/java/cn/iocoder/yudao/module/fms/dal/dataobject/config/FmsSubjectDO.java
-- Schema hints: yudao-module-fms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `fms_subject` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `code` varchar(64) NULL DEFAULT NULL COMMENT '科目编码',
  `name` varchar(255) NULL DEFAULT NULL COMMENT '科目名称',
  `parent_id` bigint NULL DEFAULT 0 COMMENT '上级科目编号',
  `type` int NULL DEFAULT NULL COMMENT '科目类型',
  `category` int NULL DEFAULT NULL COMMENT '科目类别',
  `balance_direction` int NULL DEFAULT NULL COMMENT '余额方向',
  `quantity_unit` varchar(255) NULL DEFAULT NULL COMMENT '数量核算 计量单位',
  `cash` bit(1) NULL DEFAULT b'0' COMMENT '是否现金科目',
  `status` int NULL DEFAULT 0 COMMENT '状态',
  `level` int NULL DEFAULT NULL COMMENT '科目层级',
  `quantity_accounting` bit(1) NULL DEFAULT b'0' COMMENT '是否启用数量核算',
  `account_set_id` bigint NULL DEFAULT NULL COMMENT '账套编号',
  `auxiliary_type_ids` json NULL COMMENT '辅助核算类别编号数组',
  `currency_ids` json NULL COMMENT '核算币种编号数组',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_parent_id` (`tenant_id`, `parent_id`),
  KEY `idx_account_set_id` (`tenant_id`, `account_set_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='FMS 会计科目 DO';

-- Entity: yudao-module-fms/src/main/java/cn/iocoder/yudao/module/fms/dal/dataobject/config/FmsSubjectTemplateDO.java
-- Schema hints: yudao-module-fms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `fms_subject_template` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `code` varchar(64) NULL DEFAULT NULL COMMENT '科目编码',
  `name` varchar(255) NULL DEFAULT NULL COMMENT '科目名称',
  `parent_id` bigint NULL DEFAULT 0 COMMENT '上级科目编号',
  `type` int NULL DEFAULT NULL COMMENT '科目类型',
  `category` int NULL DEFAULT NULL COMMENT '科目类别',
  `balance_direction` int NULL DEFAULT NULL COMMENT '余额方向',
  `quantity_unit` varchar(255) NULL DEFAULT NULL COMMENT '数量核算 计量单位',
  `cash` bit(1) NULL DEFAULT b'0' COMMENT '是否现金科目',
  `status` int NULL DEFAULT NULL COMMENT '状态',
  `level` int NULL DEFAULT NULL COMMENT '科目层级',
  `quantity_accounting` bit(1) NULL DEFAULT b'0' COMMENT '是否启用数量核算',
  PRIMARY KEY (`id`),
  KEY `idx_parent_id` (`parent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='FMS 科目模板 DO';

-- Entity: yudao-module-fms/src/main/java/cn/iocoder/yudao/module/fms/dal/dataobject/voucher/FmsVoucherDO.java
-- Schema hints: yudao-module-fms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `fms_voucher` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `voucher_word_id` bigint NULL DEFAULT NULL COMMENT '凭证字编号',
  `voucher_number` int NULL DEFAULT NULL COMMENT '凭证号',
  `voucher_time` datetime(6) NULL DEFAULT NULL COMMENT '凭证日期',
  `attachment_urls` json NULL COMMENT '附件地址',
  `attachment_count` int NULL DEFAULT 0 COMMENT '附单据张数',
  `debit_amount` decimal(18,2) NULL DEFAULT 0 COMMENT '借方金额',
  `credit_amount` decimal(18,2) NULL DEFAULT 0 COMMENT '贷方金额',
  `total` decimal(18,2) NULL DEFAULT 0.00 COMMENT '合计金额',
  `status` int NULL DEFAULT NULL COMMENT '状态',
  `reviewer_user_id` bigint NULL DEFAULT NULL COMMENT '审核人后台用户编号',
  `account_set_id` bigint NULL DEFAULT NULL COMMENT '账套编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_voucher_word_id` (`tenant_id`, `voucher_word_id`),
  KEY `idx_reviewer_user_id` (`tenant_id`, `reviewer_user_id`),
  KEY `idx_account_set_id` (`tenant_id`, `account_set_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='FMS 凭证 DO';

-- Entity: yudao-module-fms/src/main/java/cn/iocoder/yudao/module/fms/dal/dataobject/voucher/FmsVoucherEntryDO.java
-- Schema hints: yudao-module-fms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `fms_voucher_entry` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `digest` varchar(500) NULL DEFAULT NULL COMMENT '摘要内容',
  `subject_name` varchar(255) NULL DEFAULT NULL COMMENT '科目名称快照',
  `quantity` decimal(18,4) NULL DEFAULT 0 COMMENT '数量',
  `debit_amount` decimal(18,2) NULL DEFAULT 0 COMMENT '借方金额',
  `credit_amount` decimal(18,2) NULL DEFAULT 0 COMMENT '贷方金额',
  `voucher_id` bigint NULL DEFAULT NULL COMMENT '凭证编号',
  `subject_code` varchar(64) NULL DEFAULT NULL COMMENT '科目编码快照',
  `sort` int NULL DEFAULT NULL COMMENT '显示顺序',
  `subject_id` bigint NULL DEFAULT NULL COMMENT '科目编号',
  `account_set_id` bigint NULL DEFAULT NULL COMMENT '账套编号',
  `unit_price` decimal(18,6) NULL DEFAULT 0 COMMENT '单价',
  `assist_combination_id` bigint NULL DEFAULT NULL COMMENT '辅助核算组合编号',
  `auxiliaries` json NULL COMMENT '辅助核算项目数组',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_voucher_id` (`tenant_id`, `voucher_id`),
  KEY `idx_subject_id` (`tenant_id`, `subject_id`),
  KEY `idx_account_set_id` (`tenant_id`, `account_set_id`),
  KEY `idx_assist_combination_id` (`tenant_id`, `assist_combination_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='FMS 凭证分录 DO';

-- Entity: yudao-module-fms/src/main/java/cn/iocoder/yudao/module/fms/dal/dataobject/config/FmsVoucherTemplateDO.java
-- Schema hints: yudao-module-fms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `fms_voucher_template` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `name` varchar(255) NULL COMMENT '凭证模板名称',
  `category_id` bigint NULL COMMENT '凭证模板分类编号',
  `entries` json NULL COMMENT '凭证模板分录数组',
  `account_set_id` bigint NULL COMMENT '账套编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_category_id` (`tenant_id`, `category_id`),
  KEY `idx_account_set_id` (`tenant_id`, `account_set_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='FMS 凭证模板 DO';

-- Entity: yudao-module-fms/src/main/java/cn/iocoder/yudao/module/fms/dal/dataobject/config/FmsVoucherTemplateCategoryDO.java
-- Schema hints: yudao-module-fms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `fms_voucher_template_category` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `name` varchar(255) NULL COMMENT '凭证模板分类名称',
  `account_set_id` bigint NULL COMMENT '账套编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_account_set_id` (`tenant_id`, `account_set_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='FMS 凭证模板分类 DO';

-- Entity: yudao-module-fms/src/main/java/cn/iocoder/yudao/module/fms/dal/dataobject/config/FmsVoucherWordDO.java
-- Schema hints: yudao-module-fms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `fms_voucher_word` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `name` varchar(255) NULL DEFAULT NULL COMMENT '凭证字',
  `print_title` varchar(255) NULL DEFAULT NULL COMMENT '打印标题',
  `default_status` bit(1) NULL DEFAULT b'0' COMMENT '是否默认凭证字',
  `sort` int NULL DEFAULT 0 COMMENT '显示顺序',
  `account_set_id` bigint NULL DEFAULT NULL COMMENT '账套编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_account_set_id` (`tenant_id`, `account_set_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='FMS 凭证字 DO';
