-- Generated by sql/tools/schema/generate.py; see sql/mysql/modules/README.md.
-- Development schema reconstructed from entities; contains no seed data.
-- Existing tables are preserved; this is NOT an ALTER/migration script.
SET NAMES utf8mb4;

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/attendance/record/HrmAttendanceClockDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_attendance_clock` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '打卡记录编号',
  `employee_id` bigint NULL DEFAULT NULL COMMENT '员工编号',
  `clock_time` datetime(6) NULL COMMENT '打卡时间',
  `type` int NULL COMMENT '打卡类型',
  `attendance_time` datetime(6) NULL COMMENT '应打卡时间',
  `source_type` int NULL DEFAULT 2 COMMENT '打卡来源',
  `status` int NULL DEFAULT 0 COMMENT '打卡状态',
  `stage` int NULL DEFAULT 1 COMMENT '打卡阶段',
  `address` varchar(255) NULL DEFAULT NULL COMMENT '打卡地址',
  `longitude` decimal(10,6) NULL DEFAULT NULL COMMENT '经度',
  `latitude` decimal(10,6) NULL DEFAULT NULL COMMENT '纬度',
  `ssid` varchar(50) NULL DEFAULT NULL COMMENT 'WiFi 名称',
  `mac` varchar(50) NULL DEFAULT NULL COMMENT 'WiFi MAC 地址',
  `remark` varchar(255) NULL DEFAULT NULL COMMENT '备注',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_employee_id` (`tenant_id`, `employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 考勤打卡记录 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/attendance/config/HrmAttendanceGroupDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_attendance_group` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '考勤组编号',
  `name` varchar(50) NULL COMMENT '考勤组名称',
  `dept_ids` text NULL COMMENT '适用部门编号',
  `employee_ids` text NULL COMMENT '适用员工编号',
  `open_wifi_card` bit(1) NULL DEFAULT b'0' COMMENT '是否启用 WiFi 打卡',
  `open_point_card` bit(1) NULL DEFAULT b'0' COMMENT '是否启用定位打卡',
  `shifts` json NULL COMMENT '班次配置',
  `rest` bit(1) NULL DEFAULT b'1' COMMENT '是否法定节假日休息',
  `special_dates` json NULL COMMENT '特殊日期设置数组',
  `points` json NULL COMMENT '打卡地点配置',
  `wifis` json NULL COMMENT 'WiFi 打卡配置',
  `deduct_rule` json NULL COMMENT '扣款规则',
  `default_status` bit(1) NULL DEFAULT b'0' COMMENT '是否默认考勤组',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 考勤组 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/attendance/config/HrmAttendanceHolidayDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_attendance_holiday` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '节假日编号',
  `date` datetime(6) NULL COMMENT '日期',
  `type` int NULL DEFAULT 2 COMMENT '日期类型',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 考勤节假日 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/attendance/record/HrmAttendanceLeaveDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_attendance_leave` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '请假记录编号',
  `employee_id` bigint NULL COMMENT '员工编号',
  `type` varchar(64) NULL DEFAULT NULL COMMENT '请假类型',
  `start_time` datetime(6) NULL DEFAULT NULL COMMENT '请假开始时间',
  `end_time` datetime(6) NULL DEFAULT NULL COMMENT '请假结束时间',
  `day` decimal(10,2) NULL DEFAULT NULL COMMENT '请假时长',
  `reason` varchar(300) NULL DEFAULT NULL COMMENT '请假理由',
  `remark` varchar(500) NULL DEFAULT NULL COMMENT '备注',
  `approval_status` int NULL COMMENT '审批状态',
  `process_instance_id` varchar(64) NULL DEFAULT NULL COMMENT 'BPM 流程实例编号',
  `approval_time` datetime(6) NULL DEFAULT NULL COMMENT '审批完成时间',
  `approval_reason` varchar(500) NULL DEFAULT NULL COMMENT '审批或取消原因',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_hrm_attendance_leave_process_instance_id` (`process_instance_id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_employee_id` (`tenant_id`, `employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 考勤请假 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/config/HrmConfigDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_config` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `type` int NULL COMMENT '配置类型',
  `value` varchar(255) NULL COMMENT '配置值',
  `sort` int NULL DEFAULT NULL COMMENT '显示顺序',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 通用业务配置 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/employee/info/HrmEmployeeDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_employee` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '员工编号',
  `name` varchar(255) NULL COMMENT '员工姓名',
  `job_number` varchar(64) NULL DEFAULT NULL COMMENT '工号',
  `user_id` bigint NULL DEFAULT NULL COMMENT '后台用户编号',
  `mobile` varchar(255) NULL DEFAULT NULL COMMENT '手机号码',
  `country` varchar(64) NULL DEFAULT NULL COMMENT '国家或地区',
  `nation` varchar(64) NULL DEFAULT NULL COMMENT '民族',
  `id_type` int NULL DEFAULT NULL COMMENT '证件类型',
  `id_number` varchar(255) NULL DEFAULT NULL COMMENT '证件号码',
  `sex` int NULL DEFAULT NULL COMMENT '性别',
  `email` varchar(255) NULL DEFAULT NULL COMMENT '邮箱',
  `native_place` varchar(128) NULL DEFAULT NULL COMMENT '籍贯',
  `birthday` datetime(6) NULL DEFAULT NULL COMMENT '出生时间',
  `age` int NULL DEFAULT NULL COMMENT '年龄',
  `address` varchar(255) NULL DEFAULT NULL COMMENT '户籍地址',
  `highest_education` int NULL DEFAULT NULL COMMENT '最高学历',
  `dept_id` bigint NULL DEFAULT NULL COMMENT '部门编号',
  `leader_employee_id` bigint NULL DEFAULT NULL COMMENT '直属上级员工编号',
  `entry_status` int NULL DEFAULT NULL COMMENT '入职状态',
  `status` int NULL DEFAULT NULL COMMENT '员工状态',
  `type` int NULL DEFAULT NULL COMMENT '聘用形式',
  `entry_time` datetime(6) NULL DEFAULT NULL COMMENT '入职时间',
  `probation` int NULL DEFAULT NULL COMMENT '试用期，单位：月',
  `regular_time` datetime(6) NULL DEFAULT NULL COMMENT '转正时间',
  `leave_time` datetime(6) NULL DEFAULT NULL COMMENT '离职时间',
  `post_name` varchar(255) NULL DEFAULT NULL COMMENT '职位名称',
  `post_level` varchar(255) NULL DEFAULT NULL COMMENT '岗位职级',
  `work_city` varchar(64) NULL DEFAULT NULL COMMENT '工作城市',
  `work_address` varchar(255) NULL DEFAULT NULL COMMENT '工作地址',
  `work_detail_address` varchar(255) NULL DEFAULT NULL COMMENT '工作详细地址',
  `channel_id` bigint NULL DEFAULT NULL COMMENT '招聘渠道编号',
  `company_age_start_time` datetime(6) NULL DEFAULT NULL COMMENT '司龄开始时间',
  `company_age` int NULL DEFAULT NULL COMMENT '司龄，单位：年',
  `candidate_id` bigint NULL DEFAULT NULL COMMENT '招聘候选人编号',
  `remark` varchar(500) NULL DEFAULT NULL COMMENT '备注',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_user_id` (`tenant_id`, `user_id`),
  KEY `idx_dept_id` (`tenant_id`, `dept_id`),
  KEY `idx_leader_employee_id` (`tenant_id`, `leader_employee_id`),
  KEY `idx_channel_id` (`tenant_id`, `channel_id`),
  KEY `idx_candidate_id` (`tenant_id`, `candidate_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 员工档案 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/employee/experience/HrmEmployeeCertificateDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_employee_certificate` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '证书编号',
  `employee_id` bigint NULL COMMENT '员工编号',
  `name` varchar(255) NULL DEFAULT NULL COMMENT '证书名称',
  `level` varchar(255) NULL DEFAULT NULL COMMENT '证书级别',
  `no` varchar(255) NULL DEFAULT NULL COMMENT '证书编号',
  `start_time` datetime(6) NULL DEFAULT NULL COMMENT '有效开始日期',
  `end_time` datetime(6) NULL DEFAULT NULL COMMENT '有效结束日期',
  `issuing_authority` varchar(255) NULL DEFAULT NULL COMMENT '发证机构',
  `issuing_time` datetime(6) NULL DEFAULT NULL COMMENT '发证日期',
  `remark` varchar(500) NULL DEFAULT NULL COMMENT '备注',
  `sort` int NULL DEFAULT NULL COMMENT '显示顺序',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_employee_id` (`tenant_id`, `employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 员工证书 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/employee/employment/HrmEmployeeChangeRecordDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_employee_change_record` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '异动记录编号',
  `employee_id` bigint NULL COMMENT '员工编号',
  `type` int NULL DEFAULT NULL COMMENT '异动类型',
  `reason` int NULL DEFAULT NULL COMMENT '异动原因',
  `old_dept_id` bigint NULL DEFAULT NULL COMMENT '原部门编号',
  `new_dept_id` bigint NULL DEFAULT NULL COMMENT '新部门编号',
  `old_post_name` varchar(255) NULL DEFAULT NULL COMMENT '原岗位',
  `new_post_name` varchar(255) NULL DEFAULT NULL COMMENT '新岗位',
  `old_post_level` varchar(255) NULL DEFAULT NULL COMMENT '原职级',
  `new_post_level` varchar(255) NULL DEFAULT NULL COMMENT '新职级',
  `old_work_address` varchar(255) NULL DEFAULT NULL COMMENT '原工作地点',
  `new_work_address` varchar(255) NULL DEFAULT NULL COMMENT '新工作地点',
  `old_leader_employee_id` bigint NULL DEFAULT NULL COMMENT '原直属上级员工编号',
  `new_leader_employee_id` bigint NULL DEFAULT NULL COMMENT '新直属上级员工编号',
  `probation` int NULL DEFAULT NULL COMMENT '试用期，单位：月',
  `effect_time` datetime(6) NULL DEFAULT NULL COMMENT '生效日期',
  `applied_time` datetime(6) NULL DEFAULT NULL COMMENT '实际生效时间',
  `remark` varchar(500) NULL DEFAULT NULL COMMENT '备注',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_employee_id` (`tenant_id`, `employee_id`),
  KEY `idx_old_dept_id` (`tenant_id`, `old_dept_id`),
  KEY `idx_new_dept_id` (`tenant_id`, `new_dept_id`),
  KEY `idx_old_leader_employee_id` (`tenant_id`, `old_leader_employee_id`),
  KEY `idx_new_leader_employee_id` (`tenant_id`, `new_leader_employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 员工异动记录 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/employee/info/HrmEmployeeContactDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_employee_contact` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '联系人编号',
  `employee_id` bigint NULL COMMENT '员工编号',
  `name` varchar(64) NULL DEFAULT NULL COMMENT '联系人名称',
  `relation` varchar(64) NULL DEFAULT NULL COMMENT '与员工的关系',
  `phone` varchar(40) NULL DEFAULT NULL COMMENT '联系人电话',
  `work_unit` varchar(128) NULL DEFAULT NULL COMMENT '联系人工作单位',
  `post_name` varchar(128) NULL DEFAULT NULL COMMENT '联系人职务',
  `address` varchar(255) NULL DEFAULT NULL COMMENT '联系人地址',
  `sort` int NULL DEFAULT NULL COMMENT '显示顺序',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_employee_id` (`tenant_id`, `employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 员工联系人 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/employee/employment/HrmEmployeeContractDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_employee_contract` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '合同编号',
  `employee_id` bigint NULL COMMENT '员工编号',
  `no` varchar(128) NULL DEFAULT NULL COMMENT '合同编号',
  `type` int NULL DEFAULT NULL COMMENT '合同类型',
  `start_time` datetime(6) NULL DEFAULT NULL COMMENT '合同开始日期',
  `end_time` datetime(6) NULL DEFAULT NULL COMMENT '合同结束日期',
  `term` int NULL DEFAULT NULL COMMENT '合同期限，单位：年',
  `status` int NULL DEFAULT NULL COMMENT '合同状态',
  `sign_company` varchar(255) NULL DEFAULT NULL COMMENT '签约公司',
  `sign_time` datetime(6) NULL DEFAULT NULL COMMENT '合同签订日期',
  `remark` varchar(500) NULL DEFAULT NULL COMMENT '备注',
  `expire_remind` bit(1) NULL DEFAULT NULL COMMENT '是否到期提醒',
  `sort` int NULL DEFAULT NULL COMMENT '显示顺序',
  `file_urls` text NULL COMMENT '附件地址数组',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_employee_id` (`tenant_id`, `employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 员工合同 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/employee/experience/HrmEmployeeEducationExperienceDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_employee_education_experience` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '教育经历编号',
  `employee_id` bigint NULL COMMENT '员工编号',
  `education` int NULL DEFAULT NULL COMMENT '学历',
  `graduate_school` varchar(255) NULL DEFAULT NULL COMMENT '毕业院校',
  `major` varchar(255) NULL DEFAULT NULL COMMENT '专业',
  `admission_time` datetime(6) NULL DEFAULT NULL COMMENT '入学日期',
  `graduation_time` datetime(6) NULL DEFAULT NULL COMMENT '毕业日期',
  `teaching_methods` int NULL DEFAULT NULL COMMENT '教学方式',
  `first_degree` bit(1) NULL DEFAULT NULL COMMENT '是否第一学历',
  `sort` int NULL DEFAULT NULL COMMENT '显示顺序',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_employee_id` (`tenant_id`, `employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 员工教育经历 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/employee/info/HrmEmployeeFileDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_employee_file` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '附件编号',
  `employee_id` bigint NULL COMMENT '员工编号',
  `type` int NULL COMMENT '附件类型',
  `url` varchar(512) NULL COMMENT '附件地址',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_employee_id` (`tenant_id`, `employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 员工材料附件 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/employee/info/HrmEmployeePersonalNoteDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_employee_personal_note` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `employee_id` bigint NULL COMMENT '所属员工编号',
  `content` varchar(1024) NULL COMMENT '备忘内容',
  `reminder_time` datetime(6) NULL COMMENT '提醒时间',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_employee_id` (`tenant_id`, `employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 员工个人备忘 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/employee/employment/HrmEmployeeQuitInfoDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_employee_quit_info` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '离职信息编号',
  `employee_id` bigint NULL COMMENT '员工编号',
  `plan_quit_time` datetime(6) NULL DEFAULT NULL COMMENT '计划离职时间',
  `apply_quit_time` datetime(6) NULL DEFAULT NULL COMMENT '申请离职时间',
  `salary_settlement_time` datetime(6) NULL DEFAULT NULL COMMENT '薪资结算时间',
  `type` int NULL DEFAULT NULL COMMENT '离职类型',
  `reason` int NULL DEFAULT NULL COMMENT '离职原因',
  `remark` varchar(500) NULL DEFAULT NULL COMMENT '备注',
  `old_employee_status` int NULL DEFAULT NULL COMMENT '离职前员工状态',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_employee_id` (`tenant_id`, `employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 员工离职信息 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/employee/employment/HrmEmployeeSalaryCardDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_employee_salary_card` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `employee_id` bigint NULL COMMENT '员工编号',
  `bank_card_number` varchar(64) NULL DEFAULT NULL COMMENT '银行卡号',
  `bank_area_id` int NULL DEFAULT NULL COMMENT '开户地区编号',
  `bank_name` varchar(64) NULL DEFAULT NULL COMMENT '银行名称',
  `bank_branch_name` varchar(128) NULL DEFAULT NULL COMMENT '开户支行名称',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_employee_id` (`tenant_id`, `employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 员工工资卡 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/employee/experience/HrmEmployeeTrainingExperienceDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_employee_training_experience` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '培训经历编号',
  `employee_id` bigint NULL COMMENT '员工编号',
  `course` varchar(128) NULL DEFAULT NULL COMMENT '培训课程',
  `organization_name` varchar(128) NULL DEFAULT NULL COMMENT '培训机构名称',
  `start_time` datetime(6) NULL DEFAULT NULL COMMENT '培训开始日期',
  `end_time` datetime(6) NULL DEFAULT NULL COMMENT '培训结束日期',
  `duration` varchar(64) NULL DEFAULT NULL COMMENT '培训时长',
  `result` varchar(64) NULL DEFAULT NULL COMMENT '培训成绩',
  `certificate_name` varchar(128) NULL DEFAULT NULL COMMENT '培训证书名称',
  `remark` varchar(500) NULL DEFAULT NULL COMMENT '备注',
  `sort` int NULL DEFAULT NULL COMMENT '显示顺序',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_employee_id` (`tenant_id`, `employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 员工培训经历 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/employee/experience/HrmEmployeeWorkExperienceDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_employee_work_experience` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '工作经历编号',
  `employee_id` bigint NULL COMMENT '员工编号',
  `work_unit` varchar(255) NULL DEFAULT NULL COMMENT '工作单位',
  `post_name` varchar(255) NULL DEFAULT NULL COMMENT '职务',
  `start_time` datetime(6) NULL DEFAULT NULL COMMENT '工作开始日期',
  `end_time` datetime(6) NULL DEFAULT NULL COMMENT '工作结束日期',
  `reason` varchar(1024) NULL DEFAULT NULL COMMENT '离职原因',
  `witness_name` varchar(255) NULL DEFAULT NULL COMMENT '证明人',
  `witness_phone` varchar(32) NULL DEFAULT NULL COMMENT '证明人手机号',
  `remark` varchar(500) NULL DEFAULT NULL COMMENT '工作备注',
  `sort` int NULL DEFAULT NULL COMMENT '显示顺序',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_employee_id` (`tenant_id`, `employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 员工工作经历 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/insurance/employee/HrmInsuranceEmployeeInfoDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_insurance_employee_info` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `employee_id` bigint NULL COMMENT '员工编号',
  `first_social_security` bit(1) NULL DEFAULT b'0' COMMENT '是否首次参保',
  `first_accumulation_fund` bit(1) NULL DEFAULT b'0' COMMENT '是否首次缴纳公积金',
  `social_security_number` varchar(64) NULL DEFAULT NULL COMMENT '社保账号',
  `accumulation_fund_number` varchar(64) NULL DEFAULT NULL COMMENT '公积金账号',
  `social_security_start_month` datetime(6) NULL DEFAULT NULL COMMENT '社保起缴月份',
  `scheme_id` bigint NULL DEFAULT NULL COMMENT '社保方案编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_employee_id` (`tenant_id`, `employee_id`),
  KEY `idx_scheme_id` (`tenant_id`, `scheme_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 员工参保信息 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/insurance/monthrecord/HrmInsuranceMonthEmployeeRecordDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_insurance_month_employee_record` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `month_record_id` bigint NULL COMMENT '月度社保表编号',
  `employee_id` bigint NULL COMMENT '员工编号',
  `scheme_id` bigint NULL DEFAULT NULL COMMENT '社保方案编号',
  `year` int NULL COMMENT '年份',
  `month` int NULL COMMENT '月份',
  `personal_insurance_amount` decimal(12,2) NULL DEFAULT NULL COMMENT '个人社保金额',
  `personal_provident_fund_amount` decimal(12,2) NULL DEFAULT NULL COMMENT '个人公积金金额',
  `corporate_insurance_amount` decimal(12,2) NULL DEFAULT NULL COMMENT '公司社保金额',
  `corporate_provident_fund_amount` decimal(12,2) NULL DEFAULT NULL COMMENT '公司公积金金额',
  `status` int NULL DEFAULT NULL COMMENT '参保状态',
  `projects` json NULL COMMENT '参保项目快照',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_month_record_id` (`tenant_id`, `month_record_id`),
  KEY `idx_employee_id` (`tenant_id`, `employee_id`),
  KEY `idx_scheme_id` (`tenant_id`, `scheme_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 员工月度社保记录 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/insurance/monthrecord/HrmInsuranceMonthRecordDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_insurance_month_record` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `title` varchar(128) NULL DEFAULT NULL COMMENT '标题',
  `year` int NULL COMMENT '年份',
  `month` int NULL COMMENT '月份',
  `insured_employee_count` int NULL DEFAULT NULL COMMENT '参保人数',
  `stopped_employee_count` int NULL DEFAULT NULL COMMENT '停保人数',
  `status` int NULL DEFAULT NULL COMMENT '状态',
  `personal_insurance_amount` decimal(12,2) NULL DEFAULT NULL COMMENT '个人社保金额',
  `personal_provident_fund_amount` decimal(12,2) NULL DEFAULT NULL COMMENT '个人公积金金额',
  `corporate_insurance_amount` decimal(12,2) NULL DEFAULT NULL COMMENT '公司社保金额',
  `corporate_provident_fund_amount` decimal(12,2) NULL DEFAULT NULL COMMENT '公司公积金金额',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 月度社保表 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/insurance/config/HrmInsuranceSchemeDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_insurance_scheme` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `name` varchar(64) NULL COMMENT '方案名称',
  `area_id` int NULL DEFAULT NULL COMMENT '参保地区编号',
  `household_type` varchar(64) NULL DEFAULT NULL COMMENT '户籍类型',
  `type` int NULL COMMENT '方案类型',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 社保方案 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/insurance/config/HrmInsuranceSchemeProjectDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_insurance_scheme_project` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `scheme_id` bigint NULL COMMENT '社保方案编号',
  `type` int NULL COMMENT '项目类型',
  `name` varchar(64) NULL COMMENT '项目名称',
  `base_amount` decimal(12,2) NULL DEFAULT NULL COMMENT '缴纳基数',
  `corporate_rate` decimal(10,2) NULL DEFAULT NULL COMMENT '公司缴纳比例',
  `personal_rate` decimal(10,2) NULL DEFAULT NULL COMMENT '个人缴纳比例',
  `corporate_amount` decimal(12,2) NULL DEFAULT NULL COMMENT '公司缴纳金额',
  `personal_amount` decimal(12,2) NULL DEFAULT NULL COMMENT '个人缴纳金额',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_scheme_id` (`tenant_id`, `scheme_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 社保方案项目 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/performance/assessment/HrmPerformanceAssessmentDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_performance_assessment` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '员工绩效考核编号',
  `plan_id` bigint NULL COMMENT '绩效计划编号',
  `employee_id` bigint NULL COMMENT '员工编号',
  `status` int NULL DEFAULT 2 COMMENT '考核状态',
  `process_status` int NULL DEFAULT 1 COMMENT '流程处理状态',
  `stage_type` int NULL DEFAULT 0 COMMENT '当前业务阶段类型',
  `stage_sort` int NULL DEFAULT 0 COMMENT '当前阶段排序',
  `score` decimal(10,2) NULL DEFAULT 0.00 COMMENT '综合得分',
  `result_level` varchar(64) NULL DEFAULT NULL COMMENT '结果等级',
  `coefficient` decimal(10,2) NULL DEFAULT 1.00 COMMENT '绩效系数',
  `target_confirmation_result` int NULL DEFAULT NULL COMMENT '目标确认结果',
  `target_confirmation_comment` varchar(1000) NULL DEFAULT NULL COMMENT '目标确认意见',
  `target_confirmation_time` datetime(6) NULL DEFAULT NULL COMMENT '目标确认时间',
  `self_comment` varchar(2000) NULL DEFAULT NULL COMMENT '自评说明',
  `reviewer_comment` varchar(2000) NULL DEFAULT NULL COMMENT '他评说明',
  `result_comment` varchar(2000) NULL DEFAULT NULL COMMENT '结果说明',
  `result_confirmation_time` datetime(6) NULL DEFAULT NULL COMMENT '结果确认时间',
  `result_audit_status` int NULL DEFAULT NULL COMMENT '结果审核状态',
  `result_audit_time` datetime(6) NULL DEFAULT NULL COMMENT '结果审核时间',
  `result_audit_reason` varchar(1000) NULL DEFAULT NULL COMMENT '结果审核意见',
  `appeal_reason` varchar(1000) NULL DEFAULT NULL COMMENT '申诉原因',
  `appeal_file_urls` text NULL COMMENT '申诉附件地址列表',
  `appeal_submit_time` datetime(6) NULL DEFAULT NULL COMMENT '申诉提交时间',
  `appeal_status` int NULL DEFAULT 0 COMMENT '申诉状态',
  `appeal_time` datetime(6) NULL DEFAULT NULL COMMENT '申诉完成时间',
  `appeal_comment` varchar(1000) NULL DEFAULT NULL COMMENT '申诉处理意见',
  `archive_time` datetime(6) NULL DEFAULT NULL COMMENT '归档时间',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_plan_id` (`tenant_id`, `plan_id`),
  KEY `idx_employee_id` (`tenant_id`, `employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 员工绩效考核 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/performance/assessment/HrmPerformanceAssessmentActionRecordDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_performance_assessment_action_record` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '动作记录编号',
  `assessment_id` bigint NULL COMMENT '员工绩效考核编号',
  `stage_id` bigint NULL DEFAULT NULL COMMENT '员工绩效考核阶段编号',
  `employee_id` bigint NULL DEFAULT NULL COMMENT '操作员工编号',
  `type` int NULL COMMENT '动作类型',
  `title` varchar(128) NULL COMMENT '动作标题',
  `content` varchar(2000) NULL DEFAULT NULL COMMENT '动作内容',
  `file_urls` json NULL COMMENT '附件地址列表',
  `status` int NULL DEFAULT NULL COMMENT '动作完成后的阶段状态',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_assessment_id` (`tenant_id`, `assessment_id`),
  KEY `idx_stage_id` (`tenant_id`, `stage_id`),
  KEY `idx_employee_id` (`tenant_id`, `employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 员工绩效考核动作记录 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/performance/assessment/HrmPerformanceAssessmentAppealRecordDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_performance_assessment_appeal_record` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '申诉记录编号',
  `assessment_id` bigint NULL COMMENT '员工绩效考核编号',
  `stage_id` bigint NULL COMMENT '员工绩效考核阶段编号',
  `status` int NULL COMMENT '处理状态',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_assessment_id` (`tenant_id`, `assessment_id`),
  KEY `idx_stage_id` (`tenant_id`, `stage_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 员工绩效考核申诉记录 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/performance/assessment/HrmPerformanceAssessmentDimensionDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_performance_assessment_dimension` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '考核维度编号',
  `assessment_id` bigint NULL COMMENT '员工绩效考核编号',
  `name` varchar(255) NULL COMMENT '维度名称',
  `quota_type` int NULL DEFAULT NULL COMMENT '指标类型',
  `weight` decimal(10,2) NULL DEFAULT NULL COMMENT '维度权重',
  `remark` varchar(255) NULL DEFAULT NULL COMMENT '备注',
  `allow_edit` bit(1) NULL DEFAULT b'0' COMMENT '是否允许员工编辑指标',
  `sort` int NULL DEFAULT 0 COMMENT '排序',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_assessment_id` (`tenant_id`, `assessment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 员工绩效考核维度 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/performance/assessment/HrmPerformanceAssessmentQuotaDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_performance_assessment_quota` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '考核指标编号',
  `assessment_id` bigint NULL COMMENT '员工绩效考核编号',
  `dimension_id` bigint NULL COMMENT '考核维度编号',
  `preset` bit(1) NULL DEFAULT b'1' COMMENT '是否预置指标',
  `name` varchar(255) NULL DEFAULT NULL COMMENT '指标名称',
  `description` varchar(1000) NULL DEFAULT NULL COMMENT '指标说明',
  `standard` varchar(1000) NULL DEFAULT NULL COMMENT '评分标准',
  `weight` decimal(10,2) NULL DEFAULT 100.00 COMMENT '指标权重',
  `score_type` int NULL DEFAULT NULL COMMENT '评分类型',
  `target_value` varchar(1000) NULL DEFAULT NULL COMMENT '目标值',
  `actual_value` varchar(1000) NULL DEFAULT NULL COMMENT '实际值',
  `self_score` decimal(10,2) NULL DEFAULT 0.00 COMMENT '自评汇总分',
  `reviewer_score` decimal(10,2) NULL DEFAULT 0.00 COMMENT '他评汇总分',
  `final_score` decimal(10,2) NULL DEFAULT 0.00 COMMENT '最终指标得分',
  `sort` int NULL DEFAULT 0 COMMENT '排序',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_assessment_id` (`tenant_id`, `assessment_id`),
  KEY `idx_dimension_id` (`tenant_id`, `dimension_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 员工绩效考核指标 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/performance/assessment/HrmPerformanceAssessmentQuotaScoreDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_performance_assessment_quota_score` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '考核指标评分编号',
  `assessment_stage_id` bigint NULL COMMENT '员工绩效考核阶段编号',
  `assessment_quota_id` bigint NULL COMMENT '员工绩效考核指标编号',
  `score` decimal(10,2) NULL COMMENT '指标得分',
  `comment` varchar(1000) NULL DEFAULT NULL COMMENT '指标评语',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_assessment_stage_id` (`tenant_id`, `assessment_stage_id`),
  KEY `idx_assessment_quota_id` (`tenant_id`, `assessment_quota_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 员工绩效考核指标评分 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/performance/assessment/HrmPerformanceAssessmentStageDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_performance_assessment_stage` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '考核阶段编号',
  `assessment_id` bigint NULL COMMENT '员工绩效考核编号',
  `type` int NULL COMMENT '业务阶段类型',
  `name` varchar(128) NULL COMMENT '阶段名称',
  `handler_employee_id` bigint NULL DEFAULT NULL COMMENT '实际处理员工编号',
  `rater_type` int NULL DEFAULT NULL COMMENT '评分人类型',
  `weight` decimal(10,2) NULL DEFAULT NULL COMMENT '评分权重快照',
  `scoring_type` int NULL DEFAULT NULL COMMENT '评分方式快照',
  `visible_content` int NULL DEFAULT NULL COMMENT '评分内容可见范围快照',
  `required_setting` bit(1) NULL DEFAULT NULL COMMENT '评语是否必填',
  `reject_authority` bit(1) NULL DEFAULT NULL COMMENT '是否允许驳回',
  `sort` int NULL DEFAULT 0 COMMENT '排序',
  `status` int NULL DEFAULT 0 COMMENT '阶段处理状态',
  `score` decimal(10,2) NULL DEFAULT NULL COMMENT '阶段汇总得分',
  `result_level` varchar(64) NULL DEFAULT NULL COMMENT '阶段结果等级',
  `comment` varchar(2000) NULL DEFAULT NULL COMMENT '阶段意见',
  `reject_reason` varchar(1000) NULL DEFAULT NULL COMMENT '最近一次驳回原因',
  `submit_time` datetime(6) NULL DEFAULT NULL COMMENT '提交时间',
  `deadline_time` datetime(6) NULL DEFAULT NULL COMMENT '截止时间',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_assessment_id` (`tenant_id`, `assessment_id`),
  KEY `idx_handler_employee_id` (`tenant_id`, `handler_employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 员工绩效考核阶段 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/performance/config/HrmPerformanceAssessmentTemplateDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_performance_assessment_template` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '绩效考核模板编号',
  `name` varchar(500) NULL COMMENT '模板名称',
  `illustrate` varchar(1000) NULL DEFAULT NULL COMMENT '模板说明',
  `score_calculation` int NULL DEFAULT 1 COMMENT '计分方式',
  `upper_limit_type` int NULL DEFAULT 0 COMMENT '分数上限类型',
  `upper_limit_score` decimal(10,2) NULL DEFAULT 100.00 COMMENT '分数上限',
  `dimension_count` int NULL DEFAULT 0 COMMENT '维度数量',
  `quota_count` int NULL DEFAULT 0 COMMENT '指标数量',
  `dimensions` json NULL COMMENT '考核维度配置',
  `status` int NULL DEFAULT 0 COMMENT '状态',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 绩效考核模板 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/performance/plan/HrmPerformancePlanDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_performance_plan` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '计划编号',
  `status` int NULL DEFAULT 2 COMMENT '计划状态',
  `stage_type` int NULL DEFAULT 0 COMMENT '当前业务阶段类型',
  `operation_type` int NULL DEFAULT NULL COMMENT '当前可执行操作类型',
  `terminate_time` datetime(6) NULL DEFAULT NULL COMMENT '终止时间',
  `name` varchar(255) NULL COMMENT '计划名称',
  `cycle_type` int NULL DEFAULT NULL COMMENT '考核周期类型',
  `cycle` varchar(255) NULL DEFAULT NULL COMMENT '考核周期',
  `quarter` int NULL DEFAULT NULL COMMENT '季度',
  `start_time` datetime(6) NULL DEFAULT NULL COMMENT '开始时间',
  `end_time` datetime(6) NULL DEFAULT NULL COMMENT '结束时间',
  `description` varchar(1000) NULL DEFAULT NULL COMMENT '考核说明',
  `scopes` json NULL COMMENT '考评范围列表',
  `assessment_template_id` bigint NULL COMMENT '考核模板编号',
  `assessment_config` json NULL COMMENT '考核配置快照',
  `quota_setting_type` int NULL DEFAULT 1 COMMENT '指标制定类型',
  `target_confirmation` bit(1) NULL DEFAULT b'0' COMMENT '是否开启目标确认',
  `target_confirmation_stage` json NULL COMMENT '目标确认节点',
  `review_stages` json NULL COMMENT '评分阶段列表',
  `result_audit` bit(1) NULL DEFAULT b'1' COMMENT '是否开启结果审核',
  `result_audit_stages` json NULL COMMENT '结果审核节点列表',
  `result_confirmation` bit(1) NULL DEFAULT b'1' COMMENT '是否开启结果确认',
  `appeal_stages` json NULL COMMENT '申诉处理节点列表',
  `appeal_timeout_days` int NULL DEFAULT 2 COMMENT '申诉超期天数',
  `appeal_timeout_action` int NULL DEFAULT 1 COMMENT '申诉超期处理动作',
  `result_template_id` bigint NULL COMMENT '结果模板编号',
  `result_config` json NULL COMMENT '结果配置快照',
  `sync_to_salary` bit(1) NULL DEFAULT b'0' COMMENT '是否同步到薪资',
  `paid_for_month` varchar(20) NULL DEFAULT NULL COMMENT '计薪月份',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_assessment_template_id` (`tenant_id`, `assessment_template_id`),
  KEY `idx_result_template_id` (`tenant_id`, `result_template_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 绩效考核计划 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/performance/config/HrmPerformanceResultTemplateDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_performance_result_template` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '绩效结果模板编号',
  `name` varchar(255) NULL COMMENT '模板名称',
  `status` int NULL DEFAULT 0 COMMENT '状态',
  `levels` json NULL COMMENT '结果等级配置',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 绩效结果模板 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/recruit/candidate/HrmRecruitCandidateDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_recruit_candidate` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '候选人编号',
  `name` varchar(255) NULL COMMENT '候选人姓名',
  `mobile` varchar(255) NULL COMMENT '手机号码',
  `sex` int NULL COMMENT '性别',
  `age` int NULL DEFAULT NULL COMMENT '年龄',
  `email` varchar(255) NULL DEFAULT NULL COMMENT '邮箱',
  `post_id` bigint NULL COMMENT '应聘职位编号',
  `stage_number` int NULL DEFAULT NULL COMMENT '面试轮次',
  `work_time` int NULL DEFAULT NULL COMMENT '工作年限，单位：年',
  `education` int NULL COMMENT '学历',
  `graduate_school` varchar(255) NULL DEFAULT NULL COMMENT '毕业院校',
  `latest_work_place` varchar(255) NULL DEFAULT NULL COMMENT '最近工作单位',
  `channel_id` bigint NULL DEFAULT NULL COMMENT '招聘渠道编号',
  `remark` varchar(255) NULL DEFAULT NULL COMMENT '备注',
  `status` int NULL DEFAULT NULL COMMENT '候选人状态',
  `eliminate` varchar(255) NULL DEFAULT NULL COMMENT '淘汰原因',
  `status_update_time` datetime(6) NULL DEFAULT NULL COMMENT '状态更新时间',
  `entry_time` datetime(6) NULL DEFAULT NULL COMMENT '入职时间',
  `resume_urls` text NULL COMMENT '简历附件地址数组',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_post_id` (`tenant_id`, `post_id`),
  KEY `idx_channel_id` (`tenant_id`, `channel_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 招聘候选人 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/recruit/config/HrmRecruitChannelDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_recruit_channel` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '招聘渠道编号',
  `system_flag` bit(1) NULL DEFAULT b'0' COMMENT '是否系统内置',
  `status` int NULL DEFAULT NULL COMMENT '状态',
  `name` varchar(255) NULL COMMENT '渠道名称',
  `sort` int NULL DEFAULT NULL COMMENT '显示顺序',
  `remark` varchar(500) NULL DEFAULT NULL COMMENT '备注',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 招聘渠道 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/recruit/candidate/HrmRecruitInterviewDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_recruit_interview` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '面试编号',
  `candidate_id` bigint NULL COMMENT '候选人编号',
  `type` int NULL DEFAULT NULL COMMENT '面试方式',
  `stage_number` int NULL DEFAULT NULL COMMENT '面试轮次',
  `interview_employee_id` bigint NULL DEFAULT NULL COMMENT '主面试官员工编号',
  `other_interview_employee_ids` text NULL COMMENT '其他面试官员工编号数组',
  `interview_time` datetime(6) NULL DEFAULT NULL COMMENT '面试时间',
  `address` varchar(255) NULL DEFAULT NULL COMMENT '面试地址',
  `remark` varchar(500) NULL DEFAULT NULL COMMENT '备注',
  `result` int NULL DEFAULT NULL COMMENT '面试结果',
  `evaluate` varchar(255) NULL DEFAULT NULL COMMENT '面试评价',
  `cancel_reason` varchar(255) NULL DEFAULT NULL COMMENT '取消原因',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_candidate_id` (`tenant_id`, `candidate_id`),
  KEY `idx_interview_employee_id` (`tenant_id`, `interview_employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 招聘面试记录 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/recruit/post/HrmRecruitPostDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_recruit_post` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '招聘职位编号',
  `post_name` varchar(255) NULL COMMENT '职位名称',
  `dept_id` bigint NULL DEFAULT NULL COMMENT '部门编号',
  `job_nature` int NULL DEFAULT NULL COMMENT '工作性质',
  `area_id` int NULL DEFAULT NULL COMMENT '工作城市地区编号',
  `recruit_num` int NULL DEFAULT NULL COMMENT '招聘人数',
  `reason` varchar(255) NULL DEFAULT NULL COMMENT '招聘原因',
  `work_time` int NULL DEFAULT NULL COMMENT '工作经验要求',
  `education_require` int NULL DEFAULT NULL COMMENT '学历要求',
  `min_salary` decimal(10,2) NULL DEFAULT NULL COMMENT '最低薪资',
  `max_salary` decimal(10,2) NULL DEFAULT NULL COMMENT '最高薪资',
  `salary_unit` int NULL DEFAULT NULL COMMENT '薪资单位',
  `min_age` int NULL DEFAULT NULL COMMENT '最小年龄',
  `max_age` int NULL DEFAULT NULL COMMENT '最大年龄',
  `latest_entry_time` datetime(6) NULL DEFAULT NULL COMMENT '最迟到岗时间',
  `owner_employee_id` bigint NULL DEFAULT NULL COMMENT '招聘负责人员工编号',
  `interview_employee_ids` text NULL COMMENT '面试官员工编号数组',
  `description` longtext NULL COMMENT '职位描述',
  `emergency_level` int NULL DEFAULT NULL COMMENT '紧急程度',
  `post_type_id` bigint NULL DEFAULT NULL COMMENT '职位类型编号',
  `status` int NULL DEFAULT NULL COMMENT '职位状态',
  `stop_reason` varchar(255) NULL DEFAULT NULL COMMENT '停止原因',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_dept_id` (`tenant_id`, `dept_id`),
  KEY `idx_owner_employee_id` (`tenant_id`, `owner_employee_id`),
  KEY `idx_post_type_id` (`tenant_id`, `post_type_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 招聘职位 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/recruit/post/HrmRecruitPostTypeDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_recruit_post_type` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '职位类型编号',
  `name` varchar(40) NULL DEFAULT NULL COMMENT '类型名称',
  `parent_id` bigint NULL DEFAULT NULL COMMENT '父类型编号',
  `sort` int NULL DEFAULT NULL COMMENT '显示顺序',
  `status` int NULL DEFAULT NULL COMMENT '状态',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_parent_id` (`tenant_id`, `parent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 招聘职位类型 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/salary/employee/HrmSalaryChangeRecordDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_salary_change_record` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `employee_id` bigint NULL COMMENT '员工编号',
  `type` int NULL DEFAULT NULL COMMENT '记录类型',
  `reason` int NULL DEFAULT NULL COMMENT '调整原因',
  `effect_time` datetime(6) NULL DEFAULT NULL COMMENT '生效时间',
  `before_total` decimal(12,2) NULL DEFAULT NULL COMMENT '调整前正式薪资',
  `after_total` decimal(12,2) NULL DEFAULT NULL COMMENT '调整后正式薪资',
  `probation_before_total` decimal(12,2) NULL DEFAULT NULL COMMENT '调整前试用期薪资',
  `probation_after_total` decimal(12,2) NULL DEFAULT NULL COMMENT '调整后试用期薪资',
  `salary_options` json NULL COMMENT '正式薪资项后态快照',
  `probation_salary_options` json NULL COMMENT '试用期薪资项后态快照',
  `status` int NULL DEFAULT NULL COMMENT '状态',
  `remark` varchar(500) NULL DEFAULT NULL COMMENT '备注',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_employee_id` (`tenant_id`, `employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 定薪/调薪记录 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/salary/config/HrmSalaryChangeTemplateDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_salary_change_template` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '调薪模板编号',
  `name` varchar(64) NULL COMMENT '模板名称',
  `default_status` bit(1) NULL DEFAULT b'0' COMMENT '是否默认模板',
  `options` json NULL COMMENT '调薪项配置',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 调薪模板 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/salary/config/HrmSalaryConfigDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_salary_config` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `cycle_start_day` int NULL DEFAULT NULL COMMENT '计薪周期开始日',
  `cycle_end_day` int NULL DEFAULT NULL COMMENT '计薪周期结束日',
  `social_security_month_type` int NULL DEFAULT NULL COMMENT '社保对应月份类型',
  `start_year` int NULL DEFAULT NULL COMMENT '工资开始年份',
  `start_month` int NULL DEFAULT NULL COMMENT '工资开始月份',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_hrm_salary_config_tenant_id` (`tenant_id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 计薪配置 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/salary/employee/HrmSalaryEmployeeInfoDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_salary_employee_info` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `employee_id` bigint NULL COMMENT '员工编号',
  `change_reason` int NULL DEFAULT NULL COMMENT '定薪、调薪原因',
  `effect_time` datetime(6) NULL DEFAULT NULL COMMENT '生效时间',
  `change_type` int NULL DEFAULT NULL COMMENT '薪资信息变更类型',
  `probation_salary` decimal(12,2) NULL DEFAULT NULL COMMENT '试用期工资',
  `regular_salary` decimal(12,2) NULL DEFAULT NULL COMMENT '正式工资',
  `remark` varchar(500) NULL DEFAULT NULL COMMENT '备注',
  `salary_options` json NULL COMMENT '正式薪资项',
  `probation_salary_options` json NULL COMMENT '试用期薪资项',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_hrm_salary_employee_info_employee_id` (`employee_id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_employee_id` (`tenant_id`, `employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 员工薪资信息 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/salary/config/HrmSalaryGroupDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_salary_group` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `name` varchar(64) NULL COMMENT '薪资组名称',
  `salary_standard` decimal(12,2) NULL DEFAULT NULL COMMENT '月计薪标准',
  `change_rule` varchar(255) NULL DEFAULT NULL COMMENT '转正、调薪月规则',
  `dept_ids` json NULL COMMENT '适用部门编号列表',
  `employee_ids` json NULL COMMENT '适用员工编号列表',
  `tax_rule_id` bigint NULL DEFAULT NULL COMMENT '计税规则编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_tax_rule_id` (`tenant_id`, `tax_rule_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 薪资组 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/salary/monthrecord/HrmSalaryMonthEmployeeRecordDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_salary_month_employee_record` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `month_record_id` bigint NULL COMMENT '月度工资表编号',
  `employee_id` bigint NULL COMMENT '员工编号',
  `actual_work_day` decimal(10,2) NULL DEFAULT NULL COMMENT '实际工作天数',
  `need_work_day` decimal(10,2) NULL DEFAULT NULL COMMENT '应工作天数',
  `year` int NULL COMMENT '年份',
  `month` int NULL COMMENT '月份',
  `expected_pay_salary` decimal(12,2) NULL DEFAULT NULL COMMENT '应发工资',
  `taxable_salary` decimal(12,2) NULL DEFAULT NULL COMMENT '应税工资',
  `personal_tax` decimal(12,2) NULL DEFAULT NULL COMMENT '个人所得税',
  `real_pay_salary` decimal(12,2) NULL DEFAULT NULL COMMENT '实发工资',
  `option_values` json NULL COMMENT '薪资项值快照',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_month_record_id` (`tenant_id`, `month_record_id`),
  KEY `idx_employee_id` (`tenant_id`, `employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 员工月度工资记录 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/salary/monthrecord/HrmSalaryMonthRecordDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_salary_month_record` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `title` varchar(128) NULL DEFAULT NULL COMMENT '工资表标题',
  `year` int NULL COMMENT '年份',
  `month` int NULL COMMENT '月份',
  `employee_count` int NULL DEFAULT NULL COMMENT '员工人数',
  `start_time` datetime(6) NULL DEFAULT NULL COMMENT '计薪开始日期',
  `end_time` datetime(6) NULL DEFAULT NULL COMMENT '计薪结束日期',
  `expected_pay_salary` decimal(12,2) NULL DEFAULT NULL COMMENT '应发工资',
  `personal_tax` decimal(12,2) NULL DEFAULT NULL COMMENT '个人所得税',
  `real_pay_salary` decimal(12,2) NULL DEFAULT NULL COMMENT '实发工资',
  `personal_insurance_amount` decimal(12,2) NULL DEFAULT NULL COMMENT '个人社保金额',
  `personal_provident_fund_amount` decimal(12,2) NULL DEFAULT NULL COMMENT '个人公积金金额',
  `corporate_insurance_amount` decimal(12,2) NULL DEFAULT NULL COMMENT '公司社保金额',
  `corporate_provident_fund_amount` decimal(12,2) NULL DEFAULT NULL COMMENT '公司公积金金额',
  `option_headers` json NULL COMMENT '薪资项表头快照',
  `status` int NULL DEFAULT NULL COMMENT '状态',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 月度工资表 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/salary/config/HrmSalaryOptionDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_salary_option` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '薪资项编号',
  `template_id` bigint NULL DEFAULT NULL COMMENT '标准薪资项目录编号（可选）',
  `code` int NULL COMMENT '薪资项编码',
  `parent_code` int NULL DEFAULT 0 COMMENT '父薪资项编码',
  `name` varchar(64) NULL COMMENT '薪资项名称',
  `remark` varchar(255) NULL DEFAULT NULL COMMENT '备注',
  `system_flag` bit(1) NULL DEFAULT b'0' COMMENT '是否系统默认项',
  `type` int NULL DEFAULT 1 COMMENT '薪资项类型',
  `visible` bit(1) NULL DEFAULT b'1' COMMENT '是否显示',
  `enabled` bit(1) NULL DEFAULT b'1' COMMENT '是否启用',
  `tax_enabled` bit(1) NULL DEFAULT b'1' COMMENT '是否计税',
  `calculate_enabled` bit(1) NULL DEFAULT b'1' COMMENT '是否参与计算',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_hrm_salary_option_tenant_code` (`tenant_id`, `code`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_template_id` (`tenant_id`, `template_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 工资表薪资项 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/salary/config/HrmSalaryOptionTemplateDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_salary_option_template` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '标准薪资项编号',
  `code` int NULL COMMENT '薪资项编码',
  `parent_code` int NULL DEFAULT 0 COMMENT '父薪资项编码',
  `name` varchar(64) NULL COMMENT '薪资项名称',
  `remark` varchar(255) NULL DEFAULT NULL COMMENT '备注',
  `system_flag` bit(1) NULL DEFAULT b'0' COMMENT '是否系统默认项',
  `type` int NULL DEFAULT 1 COMMENT '薪资项类型',
  `visible` bit(1) NULL DEFAULT b'1' COMMENT '是否显示',
  `tax_enabled` bit(1) NULL DEFAULT b'1' COMMENT '是否计税',
  `calculate_enabled` bit(1) NULL DEFAULT b'1' COMMENT '是否参与计算',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_hrm_salary_option_template_code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 标准薪资项目录 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/salary/slip/HrmSalarySlipDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_salary_slip` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `send_record_id` bigint NULL COMMENT '工资条发放记录编号',
  `month_employee_record_id` bigint NULL COMMENT '员工月度工资记录编号',
  `employee_id` bigint NULL COMMENT '员工编号',
  `year` int NULL COMMENT '年份',
  `month` int NULL COMMENT '月份',
  `read_status` int NULL DEFAULT NULL COMMENT '阅读状态',
  `real_pay_salary` decimal(12,2) NULL DEFAULT NULL COMMENT '实发工资',
  `remark` varchar(500) NULL DEFAULT NULL COMMENT '备注',
  `options` json NULL COMMENT '工资条项',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_send_record_id` (`tenant_id`, `send_record_id`),
  KEY `idx_month_employee_record_id` (`tenant_id`, `month_employee_record_id`),
  KEY `idx_employee_id` (`tenant_id`, `employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 工资条 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/salary/slip/HrmSalarySlipSendRecordDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_salary_slip_send_record` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `month_record_id` bigint NULL COMMENT '月度工资表编号',
  `employee_count` int NULL DEFAULT NULL COMMENT '工资表总人数',
  `send_employee_count` int NULL DEFAULT NULL COMMENT '本批次发放人数',
  `year` int NULL COMMENT '年份',
  `month` int NULL COMMENT '月份',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_month_record_id` (`tenant_id`, `month_record_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 工资条发放记录 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/salary/slip/HrmSalarySlipTemplateDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_salary_slip_template` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `name` varchar(64) NULL COMMENT '模板名称',
  `hide_empty` bit(1) NULL DEFAULT b'0' COMMENT '是否隐藏空项',
  `default_status` bit(1) NULL DEFAULT b'0' COMMENT '是否默认模板',
  `options` json NULL COMMENT '工资条模板项',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 工资条模板 DO';

-- Entity: yudao-module-hrm/src/main/java/cn/iocoder/yudao/module/hrm/dal/dataobject/salary/config/HrmSalaryTaxRuleDO.java
-- Schema hints: yudao-module-hrm/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `hrm_salary_tax_rule` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `name` varchar(64) NULL COMMENT '计税规则名称',
  `type` int NULL DEFAULT NULL COMMENT '计税类型',
  `tax_enabled` bit(1) NULL DEFAULT NULL COMMENT '是否计税',
  `threshold` decimal(12,2) NULL DEFAULT NULL COMMENT '起征阈值',
  `decimal_scale` int NULL DEFAULT NULL COMMENT '小数位数',
  `cycle_type` int NULL DEFAULT NULL COMMENT '计税周期类型',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='HRM 计税规则 DO';
