-- Generated by sql/tools/schema/generate.py; see sql/mysql/modules/README.md.
-- Development schema reconstructed from entities; contains no seed data.
-- Existing tables are preserved; this is NOT an ALTER/migration script.
SET NAMES utf8mb4;

-- Entity: yudao-module-im/src/main/java/cn/iocoder/yudao/module/im/dal/dataobject/channel/ImChannelDO.java
-- Schema hints: yudao-module-im/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `im_channel` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `code` varchar(64) NULL COMMENT '频道业务码',
  `name` varchar(64) NULL COMMENT '频道名称',
  `avatar` varchar(512) NULL DEFAULT NULL COMMENT '频道头像',
  `sort` int NULL DEFAULT 0 COMMENT '排序',
  `status` int NULL DEFAULT 0 COMMENT '状态',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='IM 频道 DO';

-- Entity: yudao-module-im/src/main/java/cn/iocoder/yudao/module/im/dal/dataobject/channel/ImChannelMaterialDO.java
-- Schema hints: yudao-module-im/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `im_channel_material` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `channel_id` bigint NULL COMMENT '频道编号',
  `type` int NULL COMMENT '素材内容类型',
  `title` varchar(128) NULL COMMENT '标题',
  `cover_url` varchar(512) NULL DEFAULT NULL COMMENT '封面图',
  `summary` varchar(255) NULL DEFAULT NULL COMMENT '摘要',
  `content` longtext NULL COMMENT '富文本 HTML；在 ImChannelMaterialTypeEnum#CONTENT 使用',
  `url` varchar(512) NULL DEFAULT NULL COMMENT '跳转链接；在 ImChannelMaterialTypeEnum#LINK 使用',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_channel_id` (`tenant_id`, `channel_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='IM 频道素材 DO';

-- Entity: yudao-module-im/src/main/java/cn/iocoder/yudao/module/im/dal/dataobject/message/ImChannelMessageDO.java
-- Schema hints: yudao-module-im/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `im_channel_message` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `channel_id` bigint NULL COMMENT '频道编号',
  `material_id` bigint NULL COMMENT '关联素材编号',
  `type` int NULL COMMENT '消息类型',
  `content` longtext NULL COMMENT '消息内容；推送时 payload 的 JSON 快照',
  `receiver_user_ids` text NULL COMMENT '接收人编号列表；为空表示全员',
  `send_time` datetime(6) NULL COMMENT '发送时间',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_channel_id` (`tenant_id`, `channel_id`),
  KEY `idx_material_id` (`tenant_id`, `material_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='IM 频道消息 DO';

-- Entity: yudao-module-im/src/main/java/cn/iocoder/yudao/module/im/dal/dataobject/conversation/ImConversationReadDO.java
-- Schema hints: yudao-module-im/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `im_conversation_read` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `user_id` bigint NULL COMMENT '用户编号',
  `conversation_type` int NULL COMMENT '会话类型',
  `target_id` bigint NULL COMMENT '目标编号',
  `message_id` bigint NULL COMMENT '最大已读消息编号',
  `read_time` datetime(6) NULL COMMENT '最近已读时间',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_im_conversation_read_user_target` (`user_id`, `conversation_type`, `target_id`, `tenant_id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_user_id` (`tenant_id`, `user_id`),
  KEY `idx_target_id` (`tenant_id`, `target_id`),
  KEY `idx_message_id` (`tenant_id`, `message_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='IM 会话读位置 DO';

-- Entity: yudao-module-im/src/main/java/cn/iocoder/yudao/module/im/dal/dataobject/face/ImFacePackDO.java
-- Schema hints: yudao-module-im/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `im_face_pack` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `name` varchar(64) NULL COMMENT '表情包名称',
  `icon` varchar(512) NULL DEFAULT NULL COMMENT '表情包图标',
  `sort` int NULL DEFAULT 0 COMMENT '排序',
  `status` int NULL COMMENT '状态',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='IM 表情包 DO（运营配置的系统表情包元数据）';

-- Entity: yudao-module-im/src/main/java/cn/iocoder/yudao/module/im/dal/dataobject/face/ImFacePackItemDO.java
-- Schema hints: yudao-module-im/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `im_face_pack_item` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `pack_id` bigint NULL COMMENT '所属表情包编号',
  `url` varchar(512) NULL COMMENT '表情图 URL',
  `name` varchar(64) NULL DEFAULT NULL COMMENT '表情名（可选；如「狗头」「捂脸」）',
  `width` int NULL DEFAULT 0 COMMENT '渲染宽度（像素）',
  `height` int NULL DEFAULT 0 COMMENT '渲染高度（像素）',
  `sort` int NULL DEFAULT 0 COMMENT '排序',
  `status` int NULL COMMENT '状态',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_pack_id` (`tenant_id`, `pack_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='IM 表情包项 DO（系统表情包内的单张表情图）';

-- Entity: yudao-module-im/src/main/java/cn/iocoder/yudao/module/im/dal/dataobject/face/ImFaceUserItemDO.java
-- Schema hints: yudao-module-im/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `im_face_user_item` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `user_id` bigint NULL COMMENT '所属用户编号',
  `url` varchar(512) NULL COMMENT '表情图 URL',
  `name` varchar(64) NULL DEFAULT NULL COMMENT '表情名（可选）',
  `width` int NULL DEFAULT 0 COMMENT '渲染宽度（像素）',
  `height` int NULL DEFAULT 0 COMMENT '渲染高度（像素）',
  `sort` int NULL DEFAULT 0 COMMENT '排序',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_im_face_user_item_user_url_deleted` (`user_id`, `url`, `deleted`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_user_id` (`tenant_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='IM 用户私有表情 DO（个人表情包，对照微信「我的表情」）';

-- Entity: yudao-module-im/src/main/java/cn/iocoder/yudao/module/im/dal/dataobject/friend/ImFriendDO.java
-- Schema hints: yudao-module-im/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `im_friend` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `user_id` bigint NULL COMMENT '用户编号',
  `friend_user_id` bigint NULL COMMENT '好友用户编号',
  `silent` bit(1) NULL DEFAULT b'0' COMMENT '是否免打扰',
  `display_name` varchar(64) NULL DEFAULT '' COMMENT '好友展示备注',
  `add_source` int NULL DEFAULT NULL COMMENT '添加来源',
  `pinned` bit(1) NULL DEFAULT b'0' COMMENT '是否置顶联系人',
  `blocked` bit(1) NULL DEFAULT b'0' COMMENT '是否拉黑（弱关联 friend，单边屏蔽对方私聊消息）',
  `status` int NULL COMMENT '好友状态',
  `add_time` datetime(6) NULL DEFAULT NULL COMMENT '添加好友时间',
  `delete_time` datetime(6) NULL DEFAULT NULL COMMENT '删除好友时间',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_friend` (`user_id`, `friend_user_id`, `tenant_id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_user_id` (`tenant_id`, `user_id`),
  KEY `idx_friend_user_id` (`tenant_id`, `friend_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='IM 好友关系 DO';

-- Entity: yudao-module-im/src/main/java/cn/iocoder/yudao/module/im/dal/dataobject/friend/ImFriendRequestDO.java
-- Schema hints: yudao-module-im/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `im_friend_request` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `from_user_id` bigint NULL COMMENT '发起方用户编号',
  `to_user_id` bigint NULL COMMENT '接收方用户编号',
  `apply_content` varchar(255) NULL DEFAULT NULL COMMENT '申请理由',
  `display_name` varchar(64) NULL DEFAULT NULL COMMENT '发起方对接收方的备注',
  `add_source` int NULL DEFAULT NULL COMMENT '添加来源',
  `handle_result` int NULL DEFAULT 0 COMMENT '处理结果',
  `handle_content` varchar(255) NULL DEFAULT NULL COMMENT '处理理由（接收方拒绝时可选填）',
  `handle_time` datetime(6) NULL DEFAULT NULL COMMENT '处理时间',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_im_friend_request` (`from_user_id`, `to_user_id`, `tenant_id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_from_user_id` (`tenant_id`, `from_user_id`),
  KEY `idx_to_user_id` (`tenant_id`, `to_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='IM 好友申请记录 DO';

-- Entity: yudao-module-im/src/main/java/cn/iocoder/yudao/module/im/dal/dataobject/group/ImGroupDO.java
-- Schema hints: yudao-module-im/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `im_group` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `name` varchar(64) NULL COMMENT '群名称',
  `owner_user_id` bigint NULL COMMENT '群主用户编号',
  `avatar` varchar(512) NULL DEFAULT NULL COMMENT '群头像',
  `notice` varchar(2048) NULL DEFAULT NULL COMMENT '群公告',
  `join_approval` bit(1) NULL DEFAULT b'0' COMMENT '进群是否需群主 / 管理员审批',
  `banned` bit(1) NULL DEFAULT b'0' COMMENT '是否封禁',
  `banned_reason` varchar(512) NULL DEFAULT NULL COMMENT '封禁原因',
  `banned_time` datetime(6) NULL DEFAULT NULL COMMENT '封禁时间',
  `status` int NULL COMMENT '群状态',
  `dissolved_time` datetime(6) NULL DEFAULT NULL COMMENT '解散时间',
  `muted_all` bit(1) NULL DEFAULT b'0' COMMENT '是否全群禁言',
  `pinned_message_ids` text NULL COMMENT '群置顶消息编号列表',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_owner_user_id` (`tenant_id`, `owner_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='IM 群信息 DO';

-- Entity: yudao-module-im/src/main/java/cn/iocoder/yudao/module/im/dal/dataobject/group/ImGroupMemberDO.java
-- Schema hints: yudao-module-im/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `im_group_member` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `group_id` bigint NULL COMMENT '群编号',
  `user_id` bigint NULL COMMENT '用户编号',
  `display_user_name` varchar(64) NULL DEFAULT NULL COMMENT '组内显示名',
  `group_remark` varchar(64) NULL DEFAULT NULL COMMENT '群备注',
  `silent` bit(1) NULL DEFAULT b'0' COMMENT '是否免打扰',
  `status` int NULL COMMENT '成员状态',
  `role` int NULL DEFAULT 3 COMMENT '成员角色',
  `join_time` datetime(6) NULL DEFAULT NULL COMMENT '入群时间',
  `add_source` int NULL DEFAULT NULL COMMENT '加入来源',
  `inviter_user_id` bigint NULL DEFAULT NULL COMMENT '邀请人用户编号',
  `quit_time` datetime(6) NULL DEFAULT NULL COMMENT '退群时间',
  `mute_end_time` datetime(6) NULL DEFAULT NULL COMMENT '禁言到期时间',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_im_group_member` (`group_id`, `user_id`, `tenant_id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_group_id` (`tenant_id`, `group_id`),
  KEY `idx_user_id` (`tenant_id`, `user_id`),
  KEY `idx_inviter_user_id` (`tenant_id`, `inviter_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='IM 群成员 DO';

-- Entity: yudao-module-im/src/main/java/cn/iocoder/yudao/module/im/dal/dataobject/message/ImGroupMessageDO.java
-- Schema hints: yudao-module-im/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `im_group_message` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `client_message_id` varchar(64) NULL DEFAULT NULL COMMENT '客户端消息编号，用于发送幂等',
  `sender_id` bigint NULL COMMENT '发送人编号',
  `group_id` bigint NULL COMMENT '群编号',
  `type` int NULL COMMENT '消息类型',
  `content` longtext NULL COMMENT '消息内容，JSON 格式',
  `status` int NULL COMMENT '消息状态',
  `send_time` datetime(6) NULL COMMENT '发送时间',
  `receiver_user_ids` text NULL COMMENT '定向接收用户编号列表，以逗号分隔',
  `at_user_ids` text NULL COMMENT '关联 AdminUserDO 的 id 字段',
  `receipt_status` int NULL DEFAULT 0 COMMENT '回执状态',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_im_group_message_sender_client` (`sender_id`, `client_message_id`, `tenant_id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_sender_id` (`tenant_id`, `sender_id`),
  KEY `idx_group_id` (`tenant_id`, `group_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='IM 群聊消息 DO';

-- Entity: yudao-module-im/src/main/java/cn/iocoder/yudao/module/im/dal/dataobject/group/ImGroupRequestDO.java
-- Schema hints: yudao-module-im/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `im_group_request` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `group_id` bigint NULL COMMENT '群编号',
  `user_id` bigint NULL COMMENT '申请人 / 被邀请人用户编号',
  `inviter_user_id` bigint NULL DEFAULT NULL COMMENT '邀请人用户编号',
  `apply_content` varchar(255) NULL DEFAULT NULL COMMENT '申请理由',
  `add_source` int NULL DEFAULT NULL COMMENT '加入来源',
  `handle_result` int NULL DEFAULT 0 COMMENT '处理结果',
  `handle_user_id` bigint NULL DEFAULT NULL COMMENT '处理人用户编号（群主或管理员）',
  `handle_content` varchar(255) NULL DEFAULT NULL COMMENT '处理理由（拒绝时可选填）',
  `handle_time` datetime(6) NULL DEFAULT NULL COMMENT '处理时间',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_im_group_request` (`group_id`, `user_id`, `tenant_id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_group_id` (`tenant_id`, `group_id`),
  KEY `idx_user_id` (`tenant_id`, `user_id`),
  KEY `idx_inviter_user_id` (`tenant_id`, `inviter_user_id`),
  KEY `idx_handle_user_id` (`tenant_id`, `handle_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='IM 加群申请记录 DO';

-- Entity: yudao-module-im/src/main/java/cn/iocoder/yudao/module/im/dal/dataobject/message/ImPrivateMessageDO.java
-- Schema hints: yudao-module-im/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `im_private_message` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `client_message_id` varchar(64) NULL DEFAULT NULL COMMENT '客户端消息编号，用于发送幂等',
  `sender_id` bigint NULL COMMENT '发送人编号',
  `receiver_id` bigint NULL COMMENT '接收人编号',
  `type` int NULL COMMENT '消息类型',
  `content` longtext NULL COMMENT '消息内容，JSON 格式',
  `status` int NULL COMMENT '消息状态',
  `receipt_status` int NULL DEFAULT 0 COMMENT '回执状态',
  `send_time` datetime(6) NULL COMMENT '发送时间',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_im_private_message_sender_client` (`sender_id`, `client_message_id`, `tenant_id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_sender_id` (`tenant_id`, `sender_id`),
  KEY `idx_receiver_id` (`tenant_id`, `receiver_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='IM 私聊消息 DO';

-- Entity: yudao-module-im/src/main/java/cn/iocoder/yudao/module/im/dal/dataobject/rtc/ImRtcCallDO.java
-- Schema hints: yudao-module-im/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `im_rtc_call` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `room` varchar(64) NULL COMMENT '业务通话编号（UUID，同时作为 LiveKit 房间名）；唯一',
  `conversation_type` int NULL COMMENT '会话类型',
  `media_type` int NULL COMMENT '媒体类型',
  `inviter_user_id` bigint NULL COMMENT '发起人用户编号',
  `group_id` bigint NULL DEFAULT NULL COMMENT '群编号；私聊为 NULL',
  `status` int NULL COMMENT '通话状态',
  `end_reason` int NULL DEFAULT NULL COMMENT '结束原因；通话未结束时为 NULL',
  `start_time` datetime(6) NULL COMMENT '发起时间',
  `accept_time` datetime(6) NULL DEFAULT NULL COMMENT '接通时间',
  `end_time` datetime(6) NULL DEFAULT NULL COMMENT '通话结束时间',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_inviter_user_id` (`tenant_id`, `inviter_user_id`),
  KEY `idx_group_id` (`tenant_id`, `group_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='IM 通话记录 DO（房间级 / 主表）';

-- Entity: yudao-module-im/src/main/java/cn/iocoder/yudao/module/im/dal/dataobject/rtc/ImRtcParticipantDO.java
-- Schema hints: yudao-module-im/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `im_rtc_participant` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `call_id` bigint NULL COMMENT '通话编号',
  `room` varchar(64) NULL COMMENT '业务通话编号',
  `user_id` bigint NULL COMMENT '参与者用户编号',
  `role` int NULL COMMENT '参与角色',
  `status` int NULL COMMENT '参与状态',
  `invite_time` datetime(6) NULL COMMENT '被邀请时间；发起人取通话 startTime',
  `accept_time` datetime(6) NULL DEFAULT NULL COMMENT '接听时间；未接听 NULL',
  `leave_time` datetime(6) NULL DEFAULT NULL COMMENT '离开时间；未加入 NULL',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_im_rtc_participant_room_user` (`room`, `user_id`, `tenant_id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_call_id` (`tenant_id`, `call_id`),
  KEY `idx_user_id` (`tenant_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='IM 通话参与者 DO（用户级 / 明细表）';

-- Entity: yudao-module-im/src/main/java/cn/iocoder/yudao/module/im/dal/dataobject/sensitiveword/ImSensitiveWordDO.java
-- Schema hints: yudao-module-im/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `im_sensitive_word` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `word` varchar(128) NULL COMMENT '敏感词',
  `status` int NULL DEFAULT 0 COMMENT '状态',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_im_sensitive_word` (`word`, `tenant_id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='IM 敏感词 DO';
