-- Generated by sql/tools/schema/generate.py; see sql/mysql/modules/README.md.
-- Development schema reconstructed from entities; contains no seed data.
-- Existing tables are preserved; this is NOT an ALTER/migration script.
SET NAMES utf8mb4;

-- Entity: yudao-module-iot/yudao-module-iot-biz/src/main/java/cn/iocoder/yudao/module/iot/dal/dataobject/alert/IotAlertConfigDO.java
-- Schema hints: yudao-module-iot/yudao-module-iot-biz/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `iot_alert_config` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '配置编号',
  `name` varchar(255) NULL DEFAULT '' COMMENT '配置名称',
  `description` longtext NULL COMMENT '配置描述',
  `level` int NULL COMMENT '配置状态',
  `status` int NULL DEFAULT '0' COMMENT '配置状态',
  `scene_rule_ids` text NULL COMMENT '关联的场景联动规则编号数组',
  `receive_user_ids` text NULL COMMENT '接收的用户编号数组',
  `receive_types` text NULL COMMENT '接收的类型数组',
  `sms_template_code` longtext NULL COMMENT '短信模板编号',
  `mail_template_code` longtext NULL COMMENT '邮件模板编号',
  `notify_template_code` longtext NULL COMMENT '站内信模板编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='IoT 告警配置 DO';

-- Entity: yudao-module-iot/yudao-module-iot-biz/src/main/java/cn/iocoder/yudao/module/iot/dal/dataobject/alert/IotAlertRecordDO.java
-- Schema hints: yudao-module-iot/yudao-module-iot-biz/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `iot_alert_record` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '记录编号',
  `config_id` bigint NULL COMMENT '告警名称',
  `config_name` longtext NULL COMMENT '告警名称',
  `config_level` int NULL COMMENT '告警级别',
  `scene_rule_id` bigint NULL COMMENT '场景规则编号',
  `product_id` bigint NULL COMMENT '产品编号',
  `device_id` bigint NULL DEFAULT NULL COMMENT '设备编号',
  `device_message` json NULL COMMENT '触发的设备消息',
  `process_status` bit(1) NULL COMMENT '是否处理',
  `process_remark` longtext NULL COMMENT '处理结果（备注）',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_config_id` (`tenant_id`, `config_id`),
  KEY `idx_scene_rule_id` (`tenant_id`, `scene_rule_id`),
  KEY `idx_product_id` (`tenant_id`, `product_id`),
  KEY `idx_device_id` (`tenant_id`, `device_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='IoT 告警记录 DO';

-- Entity: yudao-module-iot/yudao-module-iot-biz/src/main/java/cn/iocoder/yudao/module/iot/dal/dataobject/rule/IotDataRuleDO.java
-- Schema hints: yudao-module-iot/yudao-module-iot-biz/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `iot_data_rule` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '数据流转规格编号',
  `name` varchar(128) NULL COMMENT '数据流转规格名称',
  `description` varchar(256) NULL DEFAULT '' COMMENT '数据流转规格描述',
  `status` int NULL COMMENT '数据流转规格状态',
  `source_configs` json NULL COMMENT '数据源配置数组',
  `sink_ids` text NULL COMMENT '数据目的编号数组',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='IoT 数据流转规则 DO';

-- Entity: yudao-module-iot/yudao-module-iot-biz/src/main/java/cn/iocoder/yudao/module/iot/dal/dataobject/rule/IotDataSinkDO.java
CREATE TABLE IF NOT EXISTS `iot_data_sink` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '数据流转目的编号',
  `name` longtext NULL COMMENT '数据流转目的名称',
  `description` longtext NULL COMMENT '数据流转目的描述',
  `status` int NULL COMMENT '数据流转目的状态',
  `type` int NULL COMMENT '数据流转目的类型',
  `config` json NULL COMMENT '数据流转目的配置',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='IoT 数据流转目的 DO';

-- Entity: yudao-module-iot/yudao-module-iot-biz/src/main/java/cn/iocoder/yudao/module/iot/dal/dataobject/device/IotDeviceDO.java
-- Schema hints: yudao-module-iot/yudao-module-iot-biz/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `iot_device` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '多租户编号',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '设备 ID，主键，自增',
  `device_name` varchar(255) NULL DEFAULT '' COMMENT '设备名称，在产品内唯一，用于标识设备',
  `nickname` varchar(255) NULL DEFAULT NULL COMMENT '设备备注名称',
  `serial_number` longtext NULL COMMENT '设备序列号',
  `pic_url` longtext NULL COMMENT '设备图片',
  `group_ids` text NULL COMMENT '设备分组编号集合',
  `product_id` bigint NULL COMMENT '产品编号',
  `product_key` longtext NULL COMMENT '产品标识',
  `device_type` int NULL DEFAULT '0' COMMENT '设备类型',
  `gateway_id` bigint NULL DEFAULT NULL COMMENT '网关设备编号',
  `state` int NULL COMMENT '设备状态',
  `online_time` datetime(6) NULL COMMENT '最后上线时间',
  `offline_time` datetime(6) NULL COMMENT '最后离线时间',
  `active_time` datetime(6) NULL DEFAULT NULL COMMENT '设备激活时间',
  `firmware_id` bigint NULL COMMENT '固件编号',
  `device_secret` varchar(100) NULL DEFAULT '' COMMENT '设备密钥，用于设备认证',
  `latitude` decimal(24,6) NULL COMMENT '设备位置的纬度',
  `longitude` decimal(24,6) NULL COMMENT '设备位置的经度',
  `config` longtext NULL COMMENT '设备配置',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_product_id` (`tenant_id`, `product_id`),
  KEY `idx_gateway_id` (`tenant_id`, `gateway_id`),
  KEY `idx_firmware_id` (`tenant_id`, `firmware_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='IoT 设备 DO';

-- Entity: yudao-module-iot/yudao-module-iot-biz/src/main/java/cn/iocoder/yudao/module/iot/dal/dataobject/device/IotDeviceGroupDO.java
CREATE TABLE IF NOT EXISTS `iot_device_group` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '分组 ID',
  `name` longtext NULL COMMENT '分组名字',
  `status` int NULL COMMENT '分组状态',
  `description` longtext NULL COMMENT '分组描述',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='IoT 设备分组 DO';

-- Entity: yudao-module-iot/yudao-module-iot-biz/src/main/java/cn/iocoder/yudao/module/iot/dal/dataobject/device/IotDeviceModbusConfigDO.java
CREATE TABLE IF NOT EXISTS `iot_device_modbus_config` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '多租户编号',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `product_id` bigint NULL COMMENT '产品编号',
  `device_id` bigint NULL COMMENT '设备编号',
  `ip` longtext NULL COMMENT 'Modbus 服务器 IP 地址',
  `port` int NULL COMMENT 'Modbus 服务器端口',
  `slave_id` int NULL COMMENT '从站地址',
  `timeout` int NULL COMMENT '连接超时时间，单位：毫秒',
  `retry_interval` int NULL COMMENT '重试间隔，单位：毫秒',
  `mode` int NULL COMMENT '模式',
  `frame_format` int NULL COMMENT '数据帧格式',
  `status` int NULL COMMENT '状态',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_product_id` (`tenant_id`, `product_id`),
  KEY `idx_device_id` (`tenant_id`, `device_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='IoT 设备 Modbus 连接配置 DO';

-- Entity: yudao-module-iot/yudao-module-iot-biz/src/main/java/cn/iocoder/yudao/module/iot/dal/dataobject/device/IotDeviceModbusPointDO.java
CREATE TABLE IF NOT EXISTS `iot_device_modbus_point` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '多租户编号',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `device_id` bigint NULL COMMENT '设备编号',
  `thing_model_id` bigint NULL COMMENT '物模型属性编号',
  `identifier` longtext NULL COMMENT '属性标识符',
  `name` longtext NULL COMMENT '属性名称',
  `function_code` int NULL COMMENT 'Modbus 功能码',
  `register_address` int NULL COMMENT '寄存器起始地址',
  `register_count` int NULL COMMENT '寄存器数量',
  `byte_order` longtext NULL COMMENT '字节序',
  `raw_data_type` longtext NULL COMMENT '原始数据类型',
  `scale` decimal(24,6) NULL COMMENT '缩放因子',
  `poll_interval` int NULL COMMENT '轮询间隔（毫秒）',
  `status` int NULL COMMENT '状态',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_device_id` (`tenant_id`, `device_id`),
  KEY `idx_thing_model_id` (`tenant_id`, `thing_model_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='IoT 设备 Modbus 点位配置 DO';

-- Entity: yudao-module-iot/yudao-module-iot-biz/src/main/java/cn/iocoder/yudao/module/iot/dal/dataobject/ota/IotOtaFirmwareDO.java
-- Schema hints: yudao-module-iot/yudao-module-iot-biz/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `iot_ota_firmware` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '固件编号',
  `name` varchar(255) NULL DEFAULT '' COMMENT '固件名称',
  `description` varchar(500) NULL DEFAULT NULL COMMENT '固件描述',
  `version` varchar(50) NULL DEFAULT '' COMMENT '版本号',
  `product_id` bigint NULL COMMENT '产品编号',
  `file_url` varchar(500) NULL DEFAULT NULL COMMENT '固件文件 URL',
  `file_size` bigint NULL DEFAULT '0' COMMENT '固件文件大小',
  `file_digest_algorithm` longtext NULL COMMENT '固件文件签名算法',
  `file_digest_value` longtext NULL COMMENT '固件文件签名结果',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_product_id` (`tenant_id`, `product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='IoT OTA 固件 DO';

-- Entity: yudao-module-iot/yudao-module-iot-biz/src/main/java/cn/iocoder/yudao/module/iot/dal/dataobject/ota/IotOtaTaskDO.java
-- Schema hints: yudao-module-iot/yudao-module-iot-biz/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `iot_ota_task` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '任务编号',
  `name` varchar(255) NULL DEFAULT '' COMMENT '任务名称',
  `description` longtext NULL COMMENT '任务描述',
  `firmware_id` bigint NULL COMMENT '固件编号',
  `status` int NULL DEFAULT '0' COMMENT '任务状态',
  `device_scope` int NULL COMMENT '设备升级范围',
  `device_total_count` int NULL COMMENT '设备总数数量',
  `device_success_count` int NULL COMMENT '设备成功数量',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_firmware_id` (`tenant_id`, `firmware_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='IoT OTA 升级任务 DO';

-- Entity: yudao-module-iot/yudao-module-iot-biz/src/main/java/cn/iocoder/yudao/module/iot/dal/dataobject/ota/IotOtaTaskRecordDO.java
CREATE TABLE IF NOT EXISTS `iot_ota_task_record` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '升级记录编号',
  `firmware_id` bigint NULL COMMENT '固件编号',
  `task_id` bigint NULL COMMENT '任务编号',
  `device_id` bigint NULL COMMENT '设备编号',
  `from_firmware_id` bigint NULL COMMENT '来源的固件编号',
  `status` int NULL COMMENT '升级状态',
  `progress` int NULL COMMENT '升级进度，百分比',
  `description` longtext NULL COMMENT '升级进度描述',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_firmware_id` (`tenant_id`, `firmware_id`),
  KEY `idx_task_id` (`tenant_id`, `task_id`),
  KEY `idx_device_id` (`tenant_id`, `device_id`),
  KEY `idx_from_firmware_id` (`tenant_id`, `from_firmware_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='IoT OTA 升级任务记录 DO';

-- Entity: yudao-module-iot/yudao-module-iot-biz/src/main/java/cn/iocoder/yudao/module/iot/dal/dataobject/product/IotProductDO.java
-- Schema hints: yudao-module-iot/yudao-module-iot-biz/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `iot_product` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '多租户编号',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '产品 ID',
  `name` varchar(255) NULL DEFAULT '' COMMENT '产品名称',
  `product_key` varchar(100) NULL DEFAULT '' COMMENT '产品标识',
  `product_secret` longtext NULL COMMENT '产品密钥，用于一型一密动态注册',
  `register_enabled` bit(1) NULL COMMENT '是否开启动态注册',
  `category_id` bigint NULL DEFAULT NULL COMMENT '产品分类编号',
  `icon` longtext NULL COMMENT '产品图标',
  `pic_url` longtext NULL COMMENT '产品图片',
  `description` varchar(500) NULL DEFAULT NULL COMMENT '产品描述',
  `status` int NULL DEFAULT '0' COMMENT '产品状态',
  `device_type` int NULL DEFAULT '0' COMMENT '设备类型',
  `net_type` int NULL DEFAULT '0' COMMENT '联网方式',
  `protocol_type` longtext NULL COMMENT '协议类型',
  `serialize_type` longtext NULL COMMENT '序列化类型',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_category_id` (`tenant_id`, `category_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='IoT 产品 DO';

-- Entity: yudao-module-iot/yudao-module-iot-biz/src/main/java/cn/iocoder/yudao/module/iot/dal/dataobject/product/IotProductCategoryDO.java
CREATE TABLE IF NOT EXISTS `iot_product_category` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '分类 ID',
  `name` longtext NULL COMMENT '分类名字',
  `sort` int NULL COMMENT '分类排序',
  `status` int NULL COMMENT '分类状态',
  `description` longtext NULL COMMENT '分类描述',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='IoT 产品分类 DO';

-- Entity: yudao-module-iot/yudao-module-iot-biz/src/main/java/cn/iocoder/yudao/module/iot/dal/dataobject/rule/IotSceneRuleDO.java
-- Schema hints: yudao-module-iot/yudao-module-iot-biz/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `iot_scene_rule` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '多租户编号',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '场景联动编号',
  `name` varchar(255) NULL DEFAULT '' COMMENT '场景联动名称',
  `description` varchar(500) NULL DEFAULT NULL COMMENT '场景联动描述',
  `status` int NULL DEFAULT '0' COMMENT '场景联动状态',
  `last_trigger_time` datetime(6) NULL COMMENT '最后触发时间',
  `triggers` json NULL COMMENT '场景定义配置',
  `actions` json NULL COMMENT '场景动作配置',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='IoT 场景联动规则 DO';

-- Entity: yudao-module-iot/yudao-module-iot-biz/src/main/java/cn/iocoder/yudao/module/iot/dal/dataobject/thingmodel/IotThingModelDO.java
-- Schema hints: yudao-module-iot/yudao-module-iot-biz/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `iot_thing_model` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '物模型功能编号',
  `identifier` varchar(100) NULL DEFAULT '' COMMENT '功能标识',
  `name` varchar(255) NULL DEFAULT '' COMMENT '功能名称',
  `description` varchar(500) NULL DEFAULT NULL COMMENT '功能描述',
  `product_id` bigint NULL COMMENT '产品标识',
  `product_key` longtext NULL COMMENT '产品标识',
  `type` int NULL DEFAULT '1' COMMENT '功能类型',
  `property` json NULL COMMENT '属性',
  `event` json NULL COMMENT '事件',
  `service` json NULL COMMENT '服务',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_product_id` (`tenant_id`, `product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='IoT 产品物模型功能 DO';
