-- Generated by sql/tools/schema/generate.py; see sql/mysql/modules/README.md.
-- Development schema reconstructed from entities; contains no seed data.
-- Existing tables are preserved; this is NOT an ALTER/migration script.
SET NAMES utf8mb4;

-- Entity: yudao-module-mall/yudao-module-product/src/main/java/cn/iocoder/yudao/module/product/dal/dataobject/brand/ProductBrandDO.java
-- Schema hints: yudao-module-mall/yudao-module-product/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `product_brand` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '品牌编号',
  `name` varchar(255) NULL COMMENT '品牌名称',
  `pic_url` varchar(255) NULL COMMENT '品牌图片',
  `sort` int NULL DEFAULT '0' COMMENT '品牌排序',
  `description` varchar(1024) NULL DEFAULT NULL COMMENT '品牌描述',
  `status` int NULL COMMENT '状态',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='商品品牌 DO';

-- Entity: yudao-module-mall/yudao-module-product/src/main/java/cn/iocoder/yudao/module/product/dal/dataobject/history/ProductBrowseHistoryDO.java
CREATE TABLE IF NOT EXISTS `product_browse_history` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '记录编号',
  `spu_id` bigint NULL COMMENT '商品 SPU 编号',
  `user_id` bigint NULL COMMENT '用户编号',
  `user_deleted` bit(1) NULL COMMENT '用户是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_spu_id` (`tenant_id`, `spu_id`),
  KEY `idx_user_id` (`tenant_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='商品浏览记录 DO';

-- Entity: yudao-module-mall/yudao-module-product/src/main/java/cn/iocoder/yudao/module/product/dal/dataobject/category/ProductCategoryDO.java
-- Schema hints: yudao-module-mall/yudao-module-product/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `product_category` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '分类编号',
  `parent_id` bigint NULL COMMENT '父分类编号',
  `name` varchar(255) NULL COMMENT '分类名称',
  `pic_url` varchar(255) NULL COMMENT '移动端分类图',
  `sort` int NULL DEFAULT '0' COMMENT '分类排序',
  `status` int NULL COMMENT '开启状态',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_parent_id` (`tenant_id`, `parent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='商品分类 DO';

-- Entity: yudao-module-mall/yudao-module-product/src/main/java/cn/iocoder/yudao/module/product/dal/dataobject/comment/ProductCommentDO.java
CREATE TABLE IF NOT EXISTS `product_comment` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '评论编号，主键自增',
  `user_id` bigint NULL COMMENT '评价人的用户编号',
  `user_nickname` longtext NULL COMMENT '评价人名称',
  `user_avatar` longtext NULL COMMENT '评价人头像',
  `anonymous` bit(1) NULL COMMENT '是否匿名',
  `order_id` bigint NULL COMMENT '交易订单编号',
  `order_item_id` bigint NULL COMMENT '交易订单项编号',
  `spu_id` bigint NULL COMMENT '商品 SPU 编号',
  `spu_name` longtext NULL COMMENT '商品 SPU 名称',
  `sku_id` bigint NULL COMMENT '商品 SKU 编号',
  `sku_pic_url` longtext NULL COMMENT '商品 SKU 图片地址',
  `sku_properties` json NULL COMMENT '属性数组，JSON 格式',
  `visible` bit(1) NULL COMMENT '是否可见',
  `scores` int NULL COMMENT '评分星级',
  `description_scores` int NULL COMMENT '描述星级',
  `benefit_scores` int NULL COMMENT '服务星级',
  `content` longtext NULL COMMENT '评论内容',
  `pic_urls` json NULL COMMENT '评论图片地址数组',
  `reply_status` bit(1) NULL COMMENT '商家是否回复',
  `reply_user_id` bigint NULL COMMENT '回复管理员编号',
  `reply_content` longtext NULL COMMENT '商家回复内容',
  `reply_time` datetime(6) NULL COMMENT '商家回复时间',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_user_id` (`tenant_id`, `user_id`),
  KEY `idx_order_id` (`tenant_id`, `order_id`),
  KEY `idx_order_item_id` (`tenant_id`, `order_item_id`),
  KEY `idx_spu_id` (`tenant_id`, `spu_id`),
  KEY `idx_sku_id` (`tenant_id`, `sku_id`),
  KEY `idx_reply_user_id` (`tenant_id`, `reply_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='商品评论 DO';

-- Entity: yudao-module-mall/yudao-module-product/src/main/java/cn/iocoder/yudao/module/product/dal/dataobject/favorite/ProductFavoriteDO.java
CREATE TABLE IF NOT EXISTS `product_favorite` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号，主键自增',
  `user_id` bigint NULL COMMENT '用户编号',
  `spu_id` bigint NULL COMMENT '商品 SPU 编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_user_id` (`tenant_id`, `user_id`),
  KEY `idx_spu_id` (`tenant_id`, `spu_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='商品收藏 DO';

-- Entity: yudao-module-mall/yudao-module-product/src/main/java/cn/iocoder/yudao/module/product/dal/dataobject/property/ProductPropertyDO.java
-- Schema hints: yudao-module-mall/yudao-module-product/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `product_property` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` varchar(64) NULL DEFAULT NULL COMMENT '名称',
  `remark` varchar(255) NULL DEFAULT NULL COMMENT '备注',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='商品属性项 DO';

-- Entity: yudao-module-mall/yudao-module-product/src/main/java/cn/iocoder/yudao/module/product/dal/dataobject/property/ProductPropertyValueDO.java
-- Schema hints: yudao-module-mall/yudao-module-product/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `product_property_value` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `property_id` bigint NULL DEFAULT NULL COMMENT '属性项的编号',
  `name` varchar(128) NULL DEFAULT NULL COMMENT '名称',
  `remark` varchar(255) NULL DEFAULT NULL COMMENT '备注',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_property_id` (`tenant_id`, `property_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='商品属性值 DO';

-- Entity: yudao-module-mall/yudao-module-product/src/main/java/cn/iocoder/yudao/module/product/dal/dataobject/sku/ProductSkuDO.java
-- Schema hints: yudao-module-mall/yudao-module-product/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `product_sku` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '商品 SKU 编号，自增',
  `spu_id` bigint NULL COMMENT 'SPU 编号',
  `properties` json NULL COMMENT '属性数组，JSON 格式',
  `price` int NULL DEFAULT '-1' COMMENT '商品价格，单位：分',
  `market_price` int NULL DEFAULT NULL COMMENT '市场价，单位：分',
  `cost_price` int NULL DEFAULT '-1' COMMENT '成本价，单位：分',
  `bar_code` varchar(64) NULL DEFAULT NULL COMMENT '商品条码',
  `pic_url` varchar(256) NULL COMMENT '图片地址',
  `stock` int NULL DEFAULT NULL COMMENT '库存',
  `weight` double NULL DEFAULT NULL COMMENT '商品重量，单位：kg 千克',
  `volume` double NULL DEFAULT NULL COMMENT '商品体积，单位：m^3 平米',
  `first_brokerage_price` int NULL COMMENT '一级分销的佣金，单位：分',
  `second_brokerage_price` int NULL COMMENT '二级分销的佣金，单位：分',
  `sales_count` int NULL DEFAULT NULL COMMENT '商品销量',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_spu_id` (`tenant_id`, `spu_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='商品 SKU DO';

-- Entity: yudao-module-mall/yudao-module-product/src/main/java/cn/iocoder/yudao/module/product/dal/dataobject/spu/ProductSpuDO.java
-- Schema hints: yudao-module-mall/yudao-module-product/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `product_spu` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '商品 SPU 编号，自增',
  `name` varchar(128) NULL COMMENT '商品名称',
  `keyword` varchar(256) NULL COMMENT '关键字',
  `introduction` varchar(256) NULL COMMENT '商品简介',
  `description` longtext NULL COMMENT '商品详情',
  `category_id` bigint NULL COMMENT '商品分类编号',
  `brand_id` bigint NULL DEFAULT NULL COMMENT '商品品牌编号',
  `pic_url` varchar(256) NULL COMMENT '商品封面图',
  `slider_pic_urls` json NULL COMMENT '商品轮播图',
  `sort` int NULL DEFAULT '0' COMMENT '排序字段',
  `status` int NULL COMMENT '商品状态',
  `spec_type` bit(1) NULL COMMENT '规格类型',
  `price` int NULL DEFAULT '-1' COMMENT '商品价格，单位使用：分',
  `market_price` int NULL COMMENT '市场价，单位使用：分',
  `cost_price` int NULL DEFAULT '-1' COMMENT '成本价，单位使用：分',
  `stock` int NULL DEFAULT '0' COMMENT '库存',
  `delivery_types` text NULL COMMENT '配送方式数组',
  `delivery_template_id` bigint NULL COMMENT '物流配置模板编号',
  `give_integral` int NULL COMMENT '赠送积分',
  `sub_commission_type` bit(1) NULL COMMENT '分销类型',
  `sales_count` int NULL DEFAULT '0' COMMENT '商品销量',
  `virtual_sales_count` int NULL DEFAULT '0' COMMENT '虚拟销量',
  `browse_count` int NULL DEFAULT '0' COMMENT '浏览量',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_category_id` (`tenant_id`, `category_id`),
  KEY `idx_brand_id` (`tenant_id`, `brand_id`),
  KEY `idx_delivery_template_id` (`tenant_id`, `delivery_template_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='商品 SPU DO';

-- Entity: yudao-module-mall/yudao-module-statistics/src/main/java/cn/iocoder/yudao/module/statistics/dal/dataobject/product/ProductStatisticsDO.java
CREATE TABLE IF NOT EXISTS `product_statistics` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号，主键自增',
  `time` date NULL COMMENT '统计日期',
  `spu_id` bigint NULL COMMENT '商品 SPU 编号',
  `browse_count` int NULL COMMENT '浏览量',
  `browse_user_count` int NULL COMMENT '访客量',
  `favorite_count` int NULL COMMENT '收藏数量',
  `cart_count` int NULL COMMENT '加购数量',
  `order_count` int NULL COMMENT '下单件数',
  `order_pay_count` int NULL COMMENT '支付件数',
  `order_pay_price` int NULL COMMENT '支付金额，单位：分',
  `after_sale_count` int NULL COMMENT '退款件数',
  `after_sale_refund_price` int NULL COMMENT '退款金额，单位：分',
  `browse_convert_percent` int NULL COMMENT '访客支付转化率（百分比）',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_spu_id` (`tenant_id`, `spu_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='商品统计 DO';

-- Entity: yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/article/ArticleDO.java
-- Schema hints: yudao-module-mall/yudao-module-promotion/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `promotion_article` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '文章管理编号',
  `category_id` bigint NULL COMMENT '分类编号 ArticleCategoryDO#id',
  `spu_id` bigint NULL COMMENT '关联商品编号 ProductSpuDO#id',
  `title` longtext NULL COMMENT '文章标题',
  `author` longtext NULL COMMENT '文章作者',
  `pic_url` longtext NULL COMMENT '文章封面图片地址',
  `introduction` longtext NULL COMMENT '文章简介',
  `browse_count` int NULL COMMENT '浏览次数',
  `sort` int NULL COMMENT '排序',
  `status` int NULL COMMENT '状态',
  `recommend_hot` bit(1) NULL COMMENT '是否热门(小程序)',
  `recommend_banner` bit(1) NULL COMMENT '是否轮播图(小程序)',
  `content` longtext NULL COMMENT '文章内容',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_category_id` (`tenant_id`, `category_id`),
  KEY `idx_spu_id` (`tenant_id`, `spu_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='文章管理 DO';

-- Entity: yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/article/ArticleCategoryDO.java
-- Schema hints: yudao-module-mall/yudao-module-promotion/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `promotion_article_category` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '文章分类编号',
  `name` longtext NULL COMMENT '文章分类名称',
  `pic_url` longtext NULL COMMENT '图标地址',
  `status` int NULL COMMENT '状态',
  `sort` int NULL COMMENT '排序',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='文章分类 DO';

-- Entity: yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/banner/BannerDO.java
CREATE TABLE IF NOT EXISTS `promotion_banner` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `title` longtext NULL COMMENT '标题',
  `url` longtext NULL COMMENT '跳转链接',
  `pic_url` longtext NULL COMMENT '图片链接',
  `sort` int NULL COMMENT '排序',
  `status` int NULL COMMENT '状态 CommonStatusEnum',
  `position` int NULL COMMENT '定位 BannerPositionEnum',
  `memo` longtext NULL COMMENT '备注',
  `browse_count` int NULL COMMENT '点击次数',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='banner DO';

-- Entity: yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/bargain/BargainActivityDO.java
CREATE TABLE IF NOT EXISTS `promotion_bargain_activity` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '砍价活动编号',
  `name` longtext NULL COMMENT '砍价活动名称',
  `start_time` datetime(6) NULL COMMENT '活动开始时间',
  `end_time` datetime(6) NULL COMMENT '活动结束时间',
  `status` int NULL COMMENT '活动状态',
  `spu_id` bigint NULL COMMENT '商品 SPU 编号',
  `sku_id` bigint NULL COMMENT '商品 SKU 编号',
  `bargain_first_price` int NULL COMMENT '砍价起始价格，单位：分',
  `bargain_min_price` int NULL COMMENT '砍价底价，单位：分',
  `stock` int NULL COMMENT '砍价库存(剩余库存砍价时扣减)',
  `total_stock` int NULL COMMENT '砍价总库存',
  `help_max_count` int NULL COMMENT '砍价人数',
  `bargain_count` int NULL COMMENT '帮砍次数',
  `total_limit_count` int NULL COMMENT '总限购数量',
  `random_min_price` int NULL COMMENT '用户每次砍价的最小金额，单位：分',
  `random_max_price` int NULL COMMENT '用户每次砍价的最大金额，单位：分',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_spu_id` (`tenant_id`, `spu_id`),
  KEY `idx_sku_id` (`tenant_id`, `sku_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='砍价活动 DO';

-- Entity: yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/bargain/BargainHelpDO.java
CREATE TABLE IF NOT EXISTS `promotion_bargain_help` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `activity_id` bigint NULL COMMENT '砍价活动编号',
  `record_id` bigint NULL COMMENT '砍价记录编号',
  `user_id` bigint NULL COMMENT '用户编号',
  `reduce_price` int NULL COMMENT '减少价格，单位：分',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_activity_id` (`tenant_id`, `activity_id`),
  KEY `idx_record_id` (`tenant_id`, `record_id`),
  KEY `idx_user_id` (`tenant_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='砍价助力 DO';

-- Entity: yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/bargain/BargainRecordDO.java
CREATE TABLE IF NOT EXISTS `promotion_bargain_record` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `user_id` bigint NULL COMMENT '用户编号',
  `activity_id` bigint NULL COMMENT '砍价活动编号',
  `spu_id` bigint NULL COMMENT '商品 SPU 编号',
  `sku_id` bigint NULL COMMENT '商品 SKU 编号',
  `bargain_first_price` int NULL COMMENT '砍价起始价格，单位：分',
  `bargain_price` int NULL COMMENT '当前砍价，单位：分',
  `status` int NULL COMMENT '砍价状态',
  `end_time` datetime(6) NULL COMMENT '结束时间',
  `order_id` bigint NULL COMMENT '订单编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_user_id` (`tenant_id`, `user_id`),
  KEY `idx_activity_id` (`tenant_id`, `activity_id`),
  KEY `idx_spu_id` (`tenant_id`, `spu_id`),
  KEY `idx_sku_id` (`tenant_id`, `sku_id`),
  KEY `idx_order_id` (`tenant_id`, `order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='砍价记录 DO TODO';

-- Entity: yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/combination/CombinationActivityDO.java
-- Schema hints: yudao-module-mall/yudao-module-promotion/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `promotion_combination_activity` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '活动编号',
  `name` longtext NULL COMMENT '拼团名称',
  `spu_id` bigint NULL COMMENT '商品 SPU 编号',
  `total_limit_count` int NULL COMMENT '总限购数量',
  `single_limit_count` int NULL COMMENT '单次限购数量',
  `start_time` datetime(6) NULL COMMENT '开始时间',
  `end_time` datetime(6) NULL COMMENT '结束时间',
  `user_size` int NULL COMMENT '几人团',
  `virtual_group` bit(1) NULL COMMENT '虚拟成团',
  `status` int NULL COMMENT '活动状态',
  `limit_duration` int NULL COMMENT '限制时长（小时）',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_spu_id` (`tenant_id`, `spu_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='拼团活动 DO';

-- Entity: yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/combination/CombinationProductDO.java
CREATE TABLE IF NOT EXISTS `promotion_combination_product` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `activity_id` bigint NULL COMMENT '拼团活动编号',
  `spu_id` bigint NULL COMMENT '商品 SPU 编号',
  `sku_id` bigint NULL COMMENT '商品 SKU 编号',
  `combination_price` int NULL COMMENT '拼团价格，单位分',
  `activity_status` int NULL COMMENT '拼团商品状态',
  `activity_start_time` datetime(6) NULL COMMENT '活动开始时间点',
  `activity_end_time` datetime(6) NULL COMMENT '活动结束时间点',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_activity_id` (`tenant_id`, `activity_id`),
  KEY `idx_spu_id` (`tenant_id`, `spu_id`),
  KEY `idx_sku_id` (`tenant_id`, `sku_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='拼团商品 DO';

-- Entity: yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/combination/CombinationRecordDO.java
-- Schema hints: yudao-module-mall/yudao-module-promotion/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `promotion_combination_record` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号，主键自增',
  `activity_id` bigint NULL COMMENT '拼团活动编号',
  `combination_price` int NULL COMMENT '拼团商品单价',
  `spu_id` bigint NULL COMMENT 'SPU 编号',
  `spu_name` longtext NULL COMMENT '商品名字',
  `pic_url` longtext NULL COMMENT '商品图片',
  `sku_id` bigint NULL COMMENT 'SKU 编号',
  `count` int NULL COMMENT '购买的商品数量',
  `user_id` bigint NULL COMMENT '用户编号',
  `nickname` longtext NULL COMMENT '用户昵称',
  `avatar` longtext NULL COMMENT '用户头像',
  `head_id` bigint NULL COMMENT '团长编号',
  `status` int NULL COMMENT '开团状态',
  `order_id` bigint NULL COMMENT '订单编号',
  `user_size` int NULL COMMENT '开团需要人数',
  `user_count` int NULL COMMENT '已加入拼团人数',
  `virtual_group` bit(1) NULL COMMENT '是否虚拟成团',
  `expire_time` datetime(6) NULL COMMENT '过期时间',
  `start_time` datetime(6) NULL COMMENT '开始时间 (订单付款后开始的时间)',
  `end_time` datetime(6) NULL COMMENT '结束时间（成团时间/失败时间）',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_activity_id` (`tenant_id`, `activity_id`),
  KEY `idx_spu_id` (`tenant_id`, `spu_id`),
  KEY `idx_sku_id` (`tenant_id`, `sku_id`),
  KEY `idx_user_id` (`tenant_id`, `user_id`),
  KEY `idx_head_id` (`tenant_id`, `head_id`),
  KEY `idx_order_id` (`tenant_id`, `order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='拼团记录 DO';

-- Entity: yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/coupon/CouponDO.java
-- Schema hints: yudao-module-mall/yudao-module-promotion/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `promotion_coupon` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '优惠劵编号',
  `template_id` bigint NULL COMMENT '优惠劵模板编号',
  `name` longtext NULL COMMENT '优惠劵名',
  `status` int NULL COMMENT '优惠码状态',
  `user_id` bigint NULL COMMENT '用户编号',
  `take_type` int NULL COMMENT '领取类型',
  `use_price` int NULL COMMENT '是否设置满多少金额可用，单位：分',
  `valid_start_time` datetime(6) NULL COMMENT '生效开始时间',
  `valid_end_time` datetime(6) NULL COMMENT '生效结束时间',
  `product_scope` int NULL COMMENT '商品范围',
  `product_scope_values` text NULL COMMENT '商品范围编号的数组',
  `discount_type` int NULL COMMENT '折扣类型',
  `discount_percent` int NULL COMMENT '折扣百分比',
  `discount_price` int NULL COMMENT '优惠金额，单位：分',
  `discount_limit_price` int NULL COMMENT '折扣上限，仅在 #discountType 等于 PromotionDiscountTypeEnum#PERCENT 时生效',
  `use_order_id` bigint NULL COMMENT '使用订单号',
  `use_time` datetime(6) NULL COMMENT '使用时间',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_template_id` (`tenant_id`, `template_id`),
  KEY `idx_user_id` (`tenant_id`, `user_id`),
  KEY `idx_use_order_id` (`tenant_id`, `use_order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='优惠劵 DO';

-- Entity: yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/coupon/CouponTemplateDO.java
-- Schema hints: yudao-module-mall/yudao-module-promotion/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `promotion_coupon_template` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '模板编号，自增唯一',
  `name` longtext NULL COMMENT '优惠劵名',
  `description` longtext NULL COMMENT '优惠券说明',
  `status` int NULL COMMENT '状态',
  `total_count` int NULL COMMENT '发放数量',
  `take_limit_count` int NULL COMMENT '每人限领个数',
  `take_type` int NULL COMMENT '领取方式',
  `use_price` int NULL COMMENT '是否设置满多少金额可用，单位：分',
  `product_scope` int NULL COMMENT '商品范围',
  `product_scope_values` text NULL COMMENT '商品范围编号的数组',
  `validity_type` int NULL COMMENT '生效日期类型',
  `valid_start_time` datetime(6) NULL COMMENT '固定日期 - 生效开始时间',
  `valid_end_time` datetime(6) NULL COMMENT '固定日期 - 生效结束时间',
  `fixed_start_term` int NULL COMMENT '领取日期 - 开始天数',
  `fixed_end_term` int NULL COMMENT '领取日期 - 结束天数',
  `discount_type` int NULL COMMENT '折扣类型',
  `discount_percent` int NULL COMMENT '折扣百分比',
  `discount_price` int NULL COMMENT '优惠金额，单位：分',
  `discount_limit_price` int NULL COMMENT '折扣上限，仅在 #discountType 等于 PromotionDiscountTypeEnum#PERCENT 时生效',
  `take_count` int NULL DEFAULT 0 COMMENT '领取优惠券的数量',
  `use_count` int NULL DEFAULT 0 COMMENT '使用优惠券的次数',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='优惠劵模板 DO';

-- Entity: yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/discount/DiscountActivityDO.java
-- Schema hints: yudao-module-mall/yudao-module-promotion/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `promotion_discount_activity` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '活动编号，主键自增',
  `name` longtext NULL COMMENT '活动标题',
  `status` int NULL COMMENT '状态',
  `start_time` datetime(6) NULL COMMENT '开始时间',
  `end_time` datetime(6) NULL COMMENT '结束时间',
  `remark` longtext NULL COMMENT '备注',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='限时折扣活动 DO';

-- Entity: yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/discount/DiscountProductDO.java
-- Schema hints: yudao-module-mall/yudao-module-promotion/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `promotion_discount_product` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号，主键自增',
  `activity_id` bigint NULL COMMENT '限时折扣活动的编号',
  `spu_id` bigint NULL COMMENT '商品 SPU 编号',
  `sku_id` bigint NULL COMMENT '商品 SKU 编号',
  `discount_type` int NULL COMMENT '折扣类型',
  `discount_percent` int NULL COMMENT '折扣百分比',
  `discount_price` int NULL COMMENT '优惠金额，单位：分',
  `activity_name` longtext NULL COMMENT '活动标题',
  `activity_status` int NULL COMMENT '活动状态',
  `activity_start_time` datetime(6) NULL COMMENT '活动开始时间点',
  `activity_end_time` datetime(6) NULL COMMENT '活动结束时间点',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_activity_id` (`tenant_id`, `activity_id`),
  KEY `idx_spu_id` (`tenant_id`, `spu_id`),
  KEY `idx_sku_id` (`tenant_id`, `sku_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='限时折扣商品 DO';

-- Entity: yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/diy/DiyPageDO.java
-- Schema hints: yudao-module-mall/yudao-module-promotion/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `promotion_diy_page` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '装修页面编号',
  `template_id` bigint NULL COMMENT '装修模板编号',
  `name` longtext NULL COMMENT '页面名称',
  `remark` longtext NULL COMMENT '备注',
  `preview_pic_urls` text NULL COMMENT '预览图，多个逗号分隔',
  `property` longtext NULL COMMENT '页面属性，JSON 格式',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_template_id` (`tenant_id`, `template_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='装修页面 DO';

-- Entity: yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/diy/DiyTemplateDO.java
-- Schema hints: yudao-module-mall/yudao-module-promotion/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `promotion_diy_template` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '装修模板编号',
  `name` longtext NULL COMMENT '模板名称',
  `used` bit(1) NULL COMMENT '是否使用',
  `used_time` datetime(6) NULL COMMENT '使用时间',
  `remark` longtext NULL COMMENT '备注',
  `preview_pic_urls` text NULL COMMENT '预览图',
  `property` longtext NULL COMMENT 'uni-app 底部导航属性，JSON 格式',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='装修模板 DO';

-- Entity: yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/kefu/KeFuConversationDO.java
CREATE TABLE IF NOT EXISTS `promotion_kefu_conversation` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `user_id` bigint NULL COMMENT '会话所属用户',
  `last_message_time` datetime(6) NULL COMMENT '最后聊天时间',
  `last_message_content` longtext NULL COMMENT '最后聊天内容',
  `last_message_content_type` int NULL COMMENT '最后发送的消息类型',
  `admin_pinned` bit(1) NULL COMMENT '管理端置顶',
  `user_deleted` bit(1) NULL COMMENT '用户是否可见',
  `admin_deleted` bit(1) NULL COMMENT '管理员是否可见',
  `admin_unread_message_count` int NULL COMMENT '管理员未读消息数',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_user_id` (`tenant_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='客服会话 DO';

-- Entity: yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/kefu/KeFuMessageDO.java
CREATE TABLE IF NOT EXISTS `promotion_kefu_message` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `conversation_id` bigint NULL COMMENT '会话编号',
  `sender_id` bigint NULL COMMENT '发送人编号',
  `sender_type` int NULL COMMENT '发送人类型',
  `receiver_id` bigint NULL COMMENT '接收人编号',
  `receiver_type` int NULL COMMENT '接收人类型',
  `content_type` int NULL COMMENT '消息类型',
  `content` longtext NULL COMMENT '消息',
  `read_status` bit(1) NULL COMMENT '是/否已读',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_conversation_id` (`tenant_id`, `conversation_id`),
  KEY `idx_sender_id` (`tenant_id`, `sender_id`),
  KEY `idx_receiver_id` (`tenant_id`, `receiver_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='客服消息 DO';

-- Entity: yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/point/PointActivityDO.java
CREATE TABLE IF NOT EXISTS `promotion_point_activity` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '积分商城活动编号',
  `spu_id` bigint NULL COMMENT '积分商城活动商品',
  `status` int NULL COMMENT '活动状态',
  `remark` longtext NULL COMMENT '备注',
  `sort` int NULL COMMENT '排序',
  `stock` int NULL COMMENT '积分商城活动库存(剩余库存积分兑换时扣减)',
  `total_stock` int NULL COMMENT '积分商城活动总库存',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_spu_id` (`tenant_id`, `spu_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='积分商城活动 DO';

-- Entity: yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/point/PointProductDO.java
CREATE TABLE IF NOT EXISTS `promotion_point_product` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '积分商城商品编号',
  `activity_id` bigint NULL COMMENT '积分商城活动 id',
  `spu_id` bigint NULL COMMENT '商品 SPU 编号',
  `sku_id` bigint NULL COMMENT '商品 SKU 编号',
  `count` int NULL COMMENT '可兑换次数',
  `point` int NULL COMMENT '所需兑换积分',
  `price` int NULL COMMENT '所需兑换金额，单位：分',
  `stock` int NULL COMMENT '积分商城商品库存',
  `activity_status` int NULL COMMENT '积分商城商品状态',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_activity_id` (`tenant_id`, `activity_id`),
  KEY `idx_spu_id` (`tenant_id`, `spu_id`),
  KEY `idx_sku_id` (`tenant_id`, `sku_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='积分商城商品 DO';

-- Entity: yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/reward/RewardActivityDO.java
-- Schema hints: yudao-module-mall/yudao-module-promotion/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `promotion_reward_activity` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '活动编号，主键自增',
  `name` longtext NULL COMMENT '活动标题',
  `status` int NULL COMMENT '状态',
  `start_time` datetime(6) NULL COMMENT '开始时间',
  `end_time` datetime(6) NULL COMMENT '结束时间',
  `remark` longtext NULL COMMENT '备注',
  `condition_type` int NULL COMMENT '条件类型',
  `product_scope` int NULL COMMENT '商品范围',
  `product_scope_values` text NULL COMMENT '商品 SPU 编号的数组',
  `rules` json NULL COMMENT '优惠规则的数组',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='满减送活动 DO';

-- Entity: yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/seckill/SeckillActivityDO.java
-- Schema hints: yudao-module-mall/yudao-module-promotion/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `promotion_seckill_activity` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '秒杀活动编号',
  `spu_id` bigint NULL COMMENT '秒杀活动商品',
  `name` longtext NULL COMMENT '秒杀活动名称',
  `status` int NULL COMMENT '活动状态',
  `remark` longtext NULL COMMENT '备注',
  `start_time` datetime(6) NULL COMMENT '活动开始时间',
  `end_time` datetime(6) NULL COMMENT '活动结束时间',
  `sort` int NULL COMMENT '排序',
  `config_ids` text NULL COMMENT '秒杀时段 id',
  `total_limit_count` int NULL COMMENT '总限购数量',
  `single_limit_count` int NULL COMMENT '单次限够数量',
  `stock` int NULL COMMENT '秒杀库存(剩余库存秒杀时扣减)',
  `total_stock` int NULL COMMENT '秒杀总库存',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_spu_id` (`tenant_id`, `spu_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='秒杀活动 DO';

-- Entity: yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/seckill/SeckillConfigDO.java
-- Schema hints: yudao-module-mall/yudao-module-promotion/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `promotion_seckill_config` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `name` longtext NULL COMMENT '秒杀时段名称',
  `start_time` longtext NULL COMMENT '开始时间点',
  `end_time` longtext NULL COMMENT '结束时间点',
  `slider_pic_urls` json NULL COMMENT '秒杀轮播图',
  `status` int NULL COMMENT '状态',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='秒杀时段 DO';

-- Entity: yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/seckill/SeckillProductDO.java
CREATE TABLE IF NOT EXISTS `promotion_seckill_product` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '秒杀参与商品编号',
  `activity_id` bigint NULL COMMENT '秒杀活动 id',
  `config_ids` text NULL COMMENT '秒杀时段 id',
  `spu_id` bigint NULL COMMENT '商品 SPU 编号',
  `sku_id` bigint NULL COMMENT '商品 SKU 编号',
  `seckill_price` int NULL COMMENT '秒杀金额，单位：分',
  `stock` int NULL COMMENT '秒杀库存',
  `activity_status` int NULL COMMENT '秒杀商品状态',
  `activity_start_time` datetime(6) NULL COMMENT '活动开始时间点',
  `activity_end_time` datetime(6) NULL COMMENT '活动结束时间点',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_activity_id` (`tenant_id`, `activity_id`),
  KEY `idx_spu_id` (`tenant_id`, `spu_id`),
  KEY `idx_sku_id` (`tenant_id`, `sku_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='秒杀参与商品 DO';

-- Entity: yudao-module-mall/yudao-module-trade/src/main/java/cn/iocoder/yudao/module/trade/dal/dataobject/aftersale/AfterSaleDO.java
-- Schema hints: yudao-module-mall/yudao-module-trade/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `trade_after_sale` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '售后编号，主键自增',
  `no` longtext NULL COMMENT '售后单号',
  `status` int NULL COMMENT '退款状态',
  `way` int NULL COMMENT '售后方式',
  `type` int NULL COMMENT '售后类型',
  `user_id` bigint NULL COMMENT '用户编号',
  `apply_reason` longtext NULL COMMENT '申请原因',
  `apply_description` longtext NULL COMMENT '补充描述',
  `apply_pic_urls` json NULL COMMENT '补充凭证图片',
  `order_id` bigint NULL COMMENT '交易订单编号',
  `order_no` longtext NULL COMMENT '订单流水号',
  `order_item_id` bigint NULL COMMENT '交易订单项编号',
  `spu_id` bigint NULL COMMENT '商品 SPU 编号',
  `spu_name` longtext NULL COMMENT '商品 SPU 名称',
  `sku_id` bigint NULL COMMENT '商品 SKU 编号',
  `properties` json NULL COMMENT '属性数组，JSON 格式',
  `pic_url` longtext NULL COMMENT '商品图片',
  `count` int NULL COMMENT '退货商品数量',
  `audit_time` datetime(6) NULL COMMENT '审批时间',
  `audit_user_id` bigint NULL COMMENT '审批人',
  `audit_reason` longtext NULL COMMENT '审批备注',
  `refund_price` int NULL COMMENT '退款金额，单位：分。',
  `pay_refund_id` bigint NULL COMMENT '支付退款编号',
  `refund_time` datetime(6) NULL COMMENT '退款时间',
  `logistics_id` bigint NULL COMMENT '退货物流公司编号',
  `logistics_no` longtext NULL COMMENT '退货物流单号',
  `delivery_time` datetime(6) NULL COMMENT '退货时间',
  `receive_time` datetime(6) NULL COMMENT '收货时间',
  `receive_reason` longtext NULL COMMENT '收货备注',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_user_id` (`tenant_id`, `user_id`),
  KEY `idx_order_id` (`tenant_id`, `order_id`),
  KEY `idx_order_item_id` (`tenant_id`, `order_item_id`),
  KEY `idx_spu_id` (`tenant_id`, `spu_id`),
  KEY `idx_sku_id` (`tenant_id`, `sku_id`),
  KEY `idx_audit_user_id` (`tenant_id`, `audit_user_id`),
  KEY `idx_pay_refund_id` (`tenant_id`, `pay_refund_id`),
  KEY `idx_logistics_id` (`tenant_id`, `logistics_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='售后订单，用于处理 TradeOrderDO 交易订单的退款退货流程';

-- Entity: yudao-module-mall/yudao-module-trade/src/main/java/cn/iocoder/yudao/module/trade/dal/dataobject/aftersale/AfterSaleLogDO.java
-- Schema hints: yudao-module-mall/yudao-module-trade/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `trade_after_sale_log` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `user_id` bigint NULL COMMENT '用户编号',
  `user_type` int NULL COMMENT '用户类型',
  `after_sale_id` bigint NULL COMMENT '售后编号',
  `before_status` int NULL COMMENT '操作前状态',
  `after_status` int NULL COMMENT '操作后状态',
  `operate_type` int NULL COMMENT '操作类型',
  `content` longtext NULL COMMENT '操作明细',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_user_id` (`tenant_id`, `user_id`),
  KEY `idx_after_sale_id` (`tenant_id`, `after_sale_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='交易售后日志 DO';

-- Entity: yudao-module-mall/yudao-module-trade/src/main/java/cn/iocoder/yudao/module/trade/dal/dataobject/brokerage/BrokerageRecordDO.java
-- Schema hints: yudao-module-mall/yudao-module-trade/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `trade_brokerage_record` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `user_id` bigint NULL COMMENT '用户编号',
  `biz_id` longtext NULL COMMENT '业务编号',
  `biz_type` int NULL COMMENT '业务类型',
  `title` longtext NULL COMMENT '标题',
  `description` longtext NULL COMMENT '说明',
  `price` int NULL COMMENT '金额',
  `total_price` int NULL COMMENT '当前总佣金',
  `status` int NULL COMMENT '状态',
  `frozen_days` int NULL COMMENT '冻结时间（天）',
  `unfreeze_time` datetime(6) NULL COMMENT '解冻时间',
  `source_user_level` int NULL COMMENT '来源用户等级',
  `source_user_id` bigint NULL COMMENT '来源用户编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_user_id` (`tenant_id`, `user_id`),
  KEY `idx_source_user_id` (`tenant_id`, `source_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='佣金记录 DO';

-- Entity: yudao-module-mall/yudao-module-trade/src/main/java/cn/iocoder/yudao/module/trade/dal/dataobject/brokerage/BrokerageUserDO.java
-- Schema hints: yudao-module-mall/yudao-module-trade/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `trade_brokerage_user` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '用户编号',
  `bind_user_id` bigint NULL COMMENT '推广员编号',
  `bind_user_time` datetime(6) NULL COMMENT '推广员绑定时间',
  `brokerage_enabled` bit(1) NULL COMMENT '是否有分销资格',
  `brokerage_time` datetime(6) NULL COMMENT '成为分销员时间',
  `brokerage_price` int NULL COMMENT '可用佣金',
  `frozen_price` int NULL COMMENT '冻结佣金',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_bind_user_id` (`tenant_id`, `bind_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='分销用户 DO';

-- Entity: yudao-module-mall/yudao-module-trade/src/main/java/cn/iocoder/yudao/module/trade/dal/dataobject/brokerage/BrokerageWithdrawDO.java
-- Schema hints: yudao-module-mall/yudao-module-trade/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `trade_brokerage_withdraw` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `user_id` bigint NULL COMMENT '用户编号',
  `price` int NULL COMMENT '提现金额，单位：分',
  `fee_price` int NULL COMMENT '提现手续费，单位：分',
  `total_price` int NULL COMMENT '当前总佣金，单位：分',
  `type` int NULL COMMENT '提现类型',
  `user_name` longtext NULL COMMENT '提现姓名',
  `user_account` longtext NULL COMMENT '提现账号',
  `qr_code_url` longtext NULL COMMENT '收款码',
  `bank_name` longtext NULL COMMENT '银行名称',
  `bank_address` longtext NULL COMMENT '开户地址',
  `status` int NULL COMMENT '状态',
  `audit_reason` longtext NULL COMMENT '审核驳回原因',
  `audit_time` datetime(6) NULL COMMENT '审核时间',
  `remark` longtext NULL COMMENT '备注',
  `pay_transfer_id` bigint NULL COMMENT '转账单编号',
  `transfer_channel_code` longtext NULL COMMENT '转账渠道',
  `transfer_time` datetime(6) NULL COMMENT '转账成功时间',
  `transfer_error_msg` longtext NULL COMMENT '转账错误提示',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_user_id` (`tenant_id`, `user_id`),
  KEY `idx_pay_transfer_id` (`tenant_id`, `pay_transfer_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='佣金提现 DO';

-- Entity: yudao-module-mall/yudao-module-trade/src/main/java/cn/iocoder/yudao/module/trade/dal/dataobject/cart/CartDO.java
CREATE TABLE IF NOT EXISTS `trade_cart` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号，唯一自增',
  `user_id` bigint NULL COMMENT '用户编号',
  `spu_id` bigint NULL COMMENT '商品 SPU 编号',
  `sku_id` bigint NULL COMMENT '商品 SKU 编号',
  `count` int NULL COMMENT '商品购买数量',
  `selected` bit(1) NULL COMMENT '是否选中',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_user_id` (`tenant_id`, `user_id`),
  KEY `idx_spu_id` (`tenant_id`, `spu_id`),
  KEY `idx_sku_id` (`tenant_id`, `sku_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='购物车的商品信息 DO';

-- Entity: yudao-module-mall/yudao-module-trade/src/main/java/cn/iocoder/yudao/module/trade/dal/dataobject/config/TradeConfigDO.java
CREATE TABLE IF NOT EXISTS `trade_config` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `after_sale_refund_reasons` json NULL COMMENT '售后的退款理由',
  `after_sale_return_reasons` json NULL COMMENT '售后的退货理由',
  `delivery_express_free_enabled` bit(1) NULL COMMENT '是否启用全场包邮',
  `delivery_express_free_price` int NULL COMMENT '全场包邮的最小金额，单位：分',
  `delivery_pick_up_enabled` bit(1) NULL COMMENT '是否开启自提',
  `brokerage_enabled` bit(1) NULL COMMENT '是否启用分佣',
  `brokerage_enabled_condition` int NULL COMMENT '分佣模式',
  `brokerage_bind_mode` int NULL COMMENT '分销关系绑定模式',
  `brokerage_poster_urls` json NULL COMMENT '分销海报图地址数组',
  `brokerage_first_percent` int NULL COMMENT '一级返佣比例',
  `brokerage_second_percent` int NULL COMMENT '二级返佣比例',
  `brokerage_withdraw_min_price` int NULL COMMENT '用户提现最低金额',
  `brokerage_withdraw_fee_percent` int NULL COMMENT '用户提现手续费百分比',
  `brokerage_frozen_days` int NULL COMMENT '佣金冻结时间(天)',
  `brokerage_withdraw_types` text NULL COMMENT '提现方式',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='交易中心配置 DO';

-- Entity: yudao-module-mall/yudao-module-trade/src/main/java/cn/iocoder/yudao/module/trade/dal/dataobject/delivery/DeliveryExpressDO.java
-- Schema hints: yudao-module-mall/yudao-module-trade/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `trade_delivery_express` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号，自增',
  `code` longtext NULL COMMENT '快递公司 code',
  `name` longtext NULL COMMENT '快递公司名称',
  `logo` longtext NULL COMMENT '快递公司 logo',
  `sort` int NULL COMMENT '排序',
  `status` int NULL COMMENT '状态',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='快递公司 DO';

-- Entity: yudao-module-mall/yudao-module-trade/src/main/java/cn/iocoder/yudao/module/trade/dal/dataobject/delivery/DeliveryExpressTemplateDO.java
CREATE TABLE IF NOT EXISTS `trade_delivery_express_template` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号，自增',
  `name` longtext NULL COMMENT '模板名称',
  `charge_mode` int NULL COMMENT '配送计费方式',
  `sort` int NULL COMMENT '排序',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='快递运费模板 DO';

-- Entity: yudao-module-mall/yudao-module-trade/src/main/java/cn/iocoder/yudao/module/trade/dal/dataobject/delivery/DeliveryExpressTemplateChargeDO.java
CREATE TABLE IF NOT EXISTS `trade_delivery_express_template_charge` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号，自增',
  `template_id` bigint NULL COMMENT '配送模板编号',
  `area_ids` text NULL COMMENT '配送区域编号列表',
  `charge_mode` int NULL COMMENT '配送计费方式',
  `start_count` double NULL COMMENT '首件数量(件数,重量，或体积)',
  `start_price` int NULL COMMENT '起步价，单位：分',
  `extra_count` double NULL COMMENT '续件数量(件, 重量，或体积)',
  `extra_price` int NULL COMMENT '额外价，单位：分',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_template_id` (`tenant_id`, `template_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='快递运费模板计费配置 DO';

-- Entity: yudao-module-mall/yudao-module-trade/src/main/java/cn/iocoder/yudao/module/trade/dal/dataobject/delivery/DeliveryExpressTemplateFreeDO.java
CREATE TABLE IF NOT EXISTS `trade_delivery_express_template_free` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `template_id` bigint NULL COMMENT '配送模板编号',
  `area_ids` text NULL COMMENT '配送区域编号列表',
  `free_price` int NULL COMMENT '包邮金额，单位：分',
  `free_count` int NULL COMMENT '包邮件数',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_template_id` (`tenant_id`, `template_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='快递运费模板包邮配置 DO';

-- Entity: yudao-module-mall/yudao-module-trade/src/main/java/cn/iocoder/yudao/module/trade/dal/dataobject/delivery/DeliveryPickUpStoreDO.java
CREATE TABLE IF NOT EXISTS `trade_delivery_pick_up_store` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `name` longtext NULL COMMENT '门店名称',
  `introduction` longtext NULL COMMENT '门店简介',
  `phone` longtext NULL COMMENT '门店手机',
  `area_id` int NULL COMMENT '区域编号',
  `detail_address` longtext NULL COMMENT '门店详细地址',
  `logo` longtext NULL COMMENT '门店 logo',
  `opening_time` time(6) NULL COMMENT '营业开始时间',
  `closing_time` time(6) NULL COMMENT '营业结束时间',
  `latitude` double NULL COMMENT '纬度',
  `longitude` double NULL COMMENT '经度',
  `verify_user_ids` text NULL COMMENT '核销员工用户编号数组',
  `status` int NULL COMMENT '门店状态',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='自提门店 DO';

-- Entity: yudao-module-mall/yudao-module-trade/src/main/java/cn/iocoder/yudao/module/trade/dal/dataobject/order/TradeOrderDO.java
-- Schema hints: yudao-module-mall/yudao-module-trade/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `trade_order` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '订单编号，主键自增',
  `no` longtext NULL COMMENT '订单流水号',
  `type` int NULL COMMENT '订单类型',
  `terminal` int NULL COMMENT '订单来源',
  `user_id` bigint NULL COMMENT '用户编号',
  `user_ip` longtext NULL COMMENT '用户 IP',
  `user_remark` longtext NULL COMMENT '用户备注',
  `status` int NULL COMMENT '订单状态',
  `product_count` int NULL COMMENT '购买的商品数量',
  `finish_time` datetime(6) NULL COMMENT '订单完成时间',
  `cancel_time` datetime(6) NULL COMMENT '订单取消时间',
  `cancel_type` int NULL COMMENT '取消类型',
  `remark` longtext NULL COMMENT '商家备注',
  `comment_status` bit(1) NULL COMMENT '是否评价',
  `brokerage_user_id` bigint NULL COMMENT '推广人编号',
  `pay_order_id` bigint NULL COMMENT '支付订单编号',
  `pay_status` bit(1) NULL COMMENT '是否已支付',
  `pay_time` datetime(6) NULL COMMENT '付款时间',
  `pay_channel_code` longtext NULL COMMENT '支付渠道',
  `total_price` int NULL COMMENT '商品原价，单位：分',
  `discount_price` int NULL COMMENT '优惠金额，单位：分',
  `delivery_price` int NULL COMMENT '运费金额，单位：分',
  `adjust_price` int NULL COMMENT '订单调价，单位：分',
  `pay_price` int NULL COMMENT '应付金额（总），单位：分',
  `delivery_type` int NULL COMMENT '配送方式',
  `logistics_id` bigint NULL COMMENT '发货物流公司编号',
  `logistics_no` longtext NULL COMMENT '发货物流单号',
  `delivery_time` datetime(6) NULL COMMENT '发货时间',
  `receive_time` datetime(6) NULL COMMENT '收货时间',
  `receiver_name` longtext NULL COMMENT '收件人名称',
  `receiver_mobile` longtext NULL COMMENT '收件人手机',
  `receiver_area_id` int NULL COMMENT '收件人地区编号',
  `receiver_detail_address` longtext NULL COMMENT '收件人详细地址',
  `pick_up_store_id` bigint NULL COMMENT '自提门店编号',
  `pick_up_verify_code` longtext NULL COMMENT '自提核销码',
  `refund_status` int NULL COMMENT '售后状态',
  `refund_price` int NULL COMMENT '退款金额，单位：分',
  `coupon_id` bigint NULL COMMENT '优惠劵编号',
  `coupon_price` int NULL COMMENT '优惠劵减免金额，单位：分',
  `use_point` int NULL COMMENT '使用的积分',
  `point_price` int NULL COMMENT '积分抵扣的金额，单位：分',
  `give_point` int NULL COMMENT '赠送的积分',
  `refund_point` int NULL COMMENT '退还的使用的积分',
  `vip_price` int NULL COMMENT 'VIP 减免金额，单位：分',
  `give_coupon_template_counts` json NULL COMMENT '赠送的优惠劵',
  `give_coupon_ids` text NULL COMMENT '赠送的优惠劵编号',
  `seckill_activity_id` bigint NULL COMMENT '秒杀活动编号',
  `bargain_activity_id` bigint NULL COMMENT '砍价活动编号',
  `bargain_record_id` bigint NULL COMMENT '砍价记录编号',
  `combination_activity_id` bigint NULL COMMENT '拼团活动编号',
  `combination_head_id` bigint NULL COMMENT '拼团团长编号',
  `combination_record_id` bigint NULL COMMENT '拼团记录编号',
  `point_activity_id` bigint NULL COMMENT '积分商城活动的编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_user_id` (`tenant_id`, `user_id`),
  KEY `idx_brokerage_user_id` (`tenant_id`, `brokerage_user_id`),
  KEY `idx_pay_order_id` (`tenant_id`, `pay_order_id`),
  KEY `idx_logistics_id` (`tenant_id`, `logistics_id`),
  KEY `idx_pick_up_store_id` (`tenant_id`, `pick_up_store_id`),
  KEY `idx_coupon_id` (`tenant_id`, `coupon_id`),
  KEY `idx_seckill_activity_id` (`tenant_id`, `seckill_activity_id`),
  KEY `idx_bargain_activity_id` (`tenant_id`, `bargain_activity_id`),
  KEY `idx_bargain_record_id` (`tenant_id`, `bargain_record_id`),
  KEY `idx_combination_activity_id` (`tenant_id`, `combination_activity_id`),
  KEY `idx_combination_head_id` (`tenant_id`, `combination_head_id`),
  KEY `idx_combination_record_id` (`tenant_id`, `combination_record_id`),
  KEY `idx_point_activity_id` (`tenant_id`, `point_activity_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='交易订单 DO';

-- Entity: yudao-module-mall/yudao-module-trade/src/main/java/cn/iocoder/yudao/module/trade/dal/dataobject/order/TradeOrderItemDO.java
-- Schema hints: yudao-module-mall/yudao-module-trade/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `trade_order_item` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `user_id` bigint NULL COMMENT '用户编号',
  `order_id` bigint NULL COMMENT '订单编号',
  `cart_id` bigint NULL COMMENT '购物车项编号',
  `spu_id` bigint NULL COMMENT '商品 SPU 编号',
  `spu_name` longtext NULL COMMENT '商品 SPU 名称',
  `sku_id` bigint NULL COMMENT '商品 SKU 编号',
  `properties` json NULL COMMENT '属性数组，JSON 格式',
  `pic_url` longtext NULL COMMENT '商品图片',
  `count` int NULL COMMENT '购买数量',
  `comment_status` bit(1) NULL COMMENT '是否评价',
  `price` int NULL COMMENT '商品原价（单），单位：分',
  `discount_price` int NULL COMMENT '优惠金额（总），单位：分',
  `delivery_price` int NULL COMMENT '运费金额（总），单位：分',
  `adjust_price` int NULL COMMENT '订单调价（总），单位：分',
  `pay_price` int NULL COMMENT '应付金额（总），单位：分',
  `coupon_price` int NULL COMMENT '优惠劵减免金额，单位：分',
  `point_price` int NULL COMMENT '积分抵扣的金额，单位：分',
  `use_point` int NULL COMMENT '使用的积分',
  `give_point` int NULL COMMENT '赠送的积分',
  `vip_price` int NULL COMMENT 'VIP 减免金额，单位：分',
  `after_sale_id` bigint NULL COMMENT '售后单编号',
  `after_sale_status` int NULL COMMENT '售后状态',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_user_id` (`tenant_id`, `user_id`),
  KEY `idx_order_id` (`tenant_id`, `order_id`),
  KEY `idx_cart_id` (`tenant_id`, `cart_id`),
  KEY `idx_spu_id` (`tenant_id`, `spu_id`),
  KEY `idx_sku_id` (`tenant_id`, `sku_id`),
  KEY `idx_after_sale_id` (`tenant_id`, `after_sale_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='交易订单项 DO';

-- Entity: yudao-module-mall/yudao-module-trade/src/main/java/cn/iocoder/yudao/module/trade/dal/dataobject/order/TradeOrderLogDO.java
CREATE TABLE IF NOT EXISTS `trade_order_log` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `user_id` bigint NULL COMMENT '用户编号',
  `user_type` int NULL COMMENT '用户类型',
  `order_id` bigint NULL COMMENT '订单号',
  `before_status` int NULL COMMENT '操作前状态',
  `after_status` int NULL COMMENT '操作后状态',
  `operate_type` int NULL COMMENT '操作类型',
  `content` longtext NULL COMMENT '订单日志信息',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_user_id` (`tenant_id`, `user_id`),
  KEY `idx_order_id` (`tenant_id`, `order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='订单日志 DO';

-- Entity: yudao-module-mall/yudao-module-statistics/src/main/java/cn/iocoder/yudao/module/statistics/dal/dataobject/trade/TradeStatisticsDO.java
CREATE TABLE IF NOT EXISTS `trade_statistics` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号，主键自增',
  `time` datetime(6) NULL COMMENT '统计日期',
  `order_create_count` int NULL COMMENT '创建订单数',
  `order_pay_count` int NULL COMMENT '支付订单商品数',
  `order_pay_price` int NULL COMMENT '总支付金额，单位：分',
  `after_sale_count` int NULL COMMENT '退款订单数',
  `after_sale_refund_price` int NULL COMMENT '总退款金额，单位：分',
  `brokerage_settlement_price` int NULL COMMENT '佣金金额（已结算），单位：分',
  `wallet_pay_price` int NULL COMMENT '总支付金额（余额），单位：分',
  `recharge_pay_count` int NULL COMMENT '充值订单数',
  `recharge_pay_price` int NULL COMMENT '充值金额，单位：分',
  `recharge_refund_count` int NULL COMMENT '充值退款订单数',
  `recharge_refund_price` int NULL COMMENT '充值退款金额，单位：分',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='交易统计 DO';
