-- Generated by sql/tools/schema/generate.py; see sql/mysql/modules/README.md.
-- Development schema reconstructed from entities; contains no seed data.
-- Existing tables are preserved; this is NOT an ALTER/migration script.
SET NAMES utf8mb4;

-- Entity: yudao-module-pay/src/main/java/cn/iocoder/yudao/module/pay/dal/dataobject/app/PayAppDO.java
-- Schema hints: yudao-module-pay/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pay_app` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '应用编号，数据库自增',
  `app_key` varchar(64) NULL COMMENT '应用标识',
  `name` varchar(64) NULL COMMENT '应用名',
  `status` int NULL COMMENT '状态',
  `remark` varchar(255) NULL DEFAULT NULL COMMENT '备注',
  `order_notify_url` varchar(1024) NULL COMMENT '支付结果的回调地址',
  `refund_notify_url` varchar(1024) NULL COMMENT '退款结果的回调地址',
  `transfer_notify_url` longtext NULL COMMENT '转账结果的回调地址',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='支付应用 DO';

-- Entity: yudao-module-pay/src/main/java/cn/iocoder/yudao/module/pay/dal/dataobject/channel/PayChannelDO.java
-- Schema hints: yudao-module-pay/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pay_channel` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '多租户编号',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '渠道编号，数据库自增',
  `code` varchar(32) NULL COMMENT '渠道编码',
  `status` int NULL COMMENT '状态',
  `fee_rate` double NULL DEFAULT 0 COMMENT '渠道费率，单位：百分比',
  `remark` varchar(255) NULL DEFAULT NULL COMMENT '备注',
  `app_id` bigint NULL COMMENT '应用编号',
  `config` json NULL COMMENT '支付渠道配置',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_app_id` (`tenant_id`, `app_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='支付渠道 DO';

-- Entity: yudao-module-pay/src/main/java/cn/iocoder/yudao/module/pay/dal/dataobject/demo/PayDemoOrderDO.java
CREATE TABLE IF NOT EXISTS `pay_demo_order` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '订单编号，自增',
  `user_id` bigint NULL COMMENT '用户编号',
  `spu_id` bigint NULL COMMENT '商品编号',
  `spu_name` longtext NULL COMMENT '商品名称',
  `price` int NULL COMMENT '价格，单位：分',
  `pay_status` bit(1) NULL COMMENT '是否支付',
  `pay_order_id` bigint NULL COMMENT '支付订单编号',
  `pay_time` datetime(6) NULL COMMENT '付款时间',
  `pay_channel_code` longtext NULL COMMENT '支付渠道',
  `pay_refund_id` bigint NULL COMMENT '支付退款单号',
  `refund_price` int NULL COMMENT '退款金额，单位：分',
  `refund_time` datetime(6) NULL COMMENT '退款完成时间',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_user_id` (`tenant_id`, `user_id`),
  KEY `idx_spu_id` (`tenant_id`, `spu_id`),
  KEY `idx_pay_order_id` (`tenant_id`, `pay_order_id`),
  KEY `idx_pay_refund_id` (`tenant_id`, `pay_refund_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='示例订单';

-- Entity: yudao-module-pay/src/main/java/cn/iocoder/yudao/module/pay/dal/dataobject/demo/PayDemoWithdrawDO.java
CREATE TABLE IF NOT EXISTS `pay_demo_withdraw` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '提现单编号，自增',
  `subject` longtext NULL COMMENT '提现标题',
  `price` int NULL COMMENT '提现金额，单位：分',
  `user_account` longtext NULL COMMENT '收款人账号',
  `user_name` longtext NULL COMMENT '收款人姓名',
  `type` int NULL COMMENT '提现方式',
  `status` int NULL COMMENT '提现状态',
  `pay_transfer_id` bigint NULL COMMENT '转账单编号',
  `transfer_channel_code` longtext NULL COMMENT '转账渠道',
  `transfer_time` datetime(6) NULL COMMENT '转账成功时间',
  `transfer_error_msg` longtext NULL COMMENT '转账错误提示',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_pay_transfer_id` (`tenant_id`, `pay_transfer_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='示例提现订单';

-- Entity: yudao-module-pay/src/main/java/cn/iocoder/yudao/module/pay/dal/dataobject/notify/PayNotifyLogDO.java
-- Schema hints: yudao-module-pay/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pay_notify_log` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '日志编号，自增',
  `task_id` bigint NULL COMMENT '通知任务编号',
  `notify_times` int NULL COMMENT '第几次被通知',
  `response` varchar(1024) NULL COMMENT 'HTTP 响应结果',
  `status` int NULL COMMENT '支付通知状态',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_task_id` (`tenant_id`, `task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='商户支付、退款等的通知 Log';

-- Entity: yudao-module-pay/src/main/java/cn/iocoder/yudao/module/pay/dal/dataobject/notify/PayNotifyTaskDO.java
-- Schema hints: yudao-module-pay/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pay_notify_task` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '多租户编号',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号，自增',
  `app_id` bigint NULL COMMENT '应用编号',
  `type` int NULL COMMENT '通知类型',
  `data_id` bigint NULL COMMENT '数据编号，根据不同 type 进行关联：',
  `merchant_order_id` varchar(64) NULL COMMENT '商户订单编号',
  `merchant_refund_id` longtext NULL COMMENT '商户退款编号',
  `merchant_transfer_id` longtext NULL COMMENT '商户转账编号',
  `status` int NULL COMMENT '通知状态',
  `next_notify_time` datetime(6) NULL DEFAULT NULL COMMENT '下一次通知时间',
  `last_execute_time` datetime(6) NULL DEFAULT NULL COMMENT '最后一次执行时间',
  `notify_times` int NULL COMMENT '当前通知次数',
  `max_notify_times` int NULL COMMENT '最大可通知次数',
  `notify_url` varchar(1024) NULL COMMENT '通知地址',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_app_id` (`tenant_id`, `app_id`),
  KEY `idx_data_id` (`tenant_id`, `data_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='支付通知';

-- Entity: yudao-module-pay/src/main/java/cn/iocoder/yudao/module/pay/dal/dataobject/order/PayOrderDO.java
-- Schema hints: yudao-module-pay/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pay_order` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '订单编号，数据库自增',
  `app_id` bigint NULL COMMENT '应用编号',
  `channel_id` bigint NULL DEFAULT NULL COMMENT '渠道编号',
  `channel_code` varchar(32) NULL DEFAULT NULL COMMENT '渠道编码',
  `user_id` bigint NULL DEFAULT NULL COMMENT '用户编号',
  `user_type` int NULL DEFAULT NULL COMMENT '用户类型',
  `merchant_order_id` varchar(64) NULL COMMENT '商户订单编号',
  `subject` varchar(32) NULL COMMENT '商品标题',
  `body` varchar(128) NULL COMMENT '商品描述信息',
  `notify_url` varchar(1024) NULL COMMENT '异步通知地址',
  `price` int NULL COMMENT '支付金额，单位：分',
  `channel_fee_rate` double NULL DEFAULT 0 COMMENT '渠道手续费，单位：百分比',
  `channel_fee_price` int NULL DEFAULT 0 COMMENT '渠道手续金额，单位：分',
  `status` int NULL COMMENT '支付状态',
  `user_ip` varchar(50) NULL COMMENT '用户 IP',
  `expire_time` datetime(6) NULL COMMENT '订单失效时间',
  `success_time` datetime(6) NULL COMMENT '订单支付成功时间',
  `extension_id` bigint NULL DEFAULT NULL COMMENT '支付成功的订单拓展单编号',
  `no` varchar(64) NULL COMMENT '支付成功的外部订单号',
  `refund_price` int NULL COMMENT '退款总金额，单位：分',
  `channel_user_id` varchar(255) NULL DEFAULT NULL COMMENT '渠道用户编号',
  `channel_order_no` varchar(64) NULL DEFAULT NULL COMMENT '渠道订单号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_app_id` (`tenant_id`, `app_id`),
  KEY `idx_channel_id` (`tenant_id`, `channel_id`),
  KEY `idx_user_id` (`tenant_id`, `user_id`),
  KEY `idx_extension_id` (`tenant_id`, `extension_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='支付订单 DO';

-- Entity: yudao-module-pay/src/main/java/cn/iocoder/yudao/module/pay/dal/dataobject/order/PayOrderExtensionDO.java
-- Schema hints: yudao-module-pay/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pay_order_extension` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '订单拓展编号，数据库自增',
  `no` varchar(64) NULL COMMENT '外部订单号，根据规则生成',
  `order_id` bigint NULL COMMENT '订单号',
  `channel_id` bigint NULL COMMENT '渠道编号',
  `channel_code` varchar(32) NULL COMMENT '渠道编码',
  `user_ip` varchar(50) NULL DEFAULT NULL COMMENT '用户 IP',
  `status` int NULL COMMENT '支付状态',
  `channel_extras` json NULL COMMENT '支付渠道的额外参数',
  `channel_error_code` varchar(64) NULL COMMENT '调用渠道的错误码',
  `channel_error_msg` varchar(64) NULL COMMENT '调用渠道报错时，错误信息',
  `channel_notify_data` varchar(1024) NULL COMMENT '支付渠道的同步/异步通知的内容',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_order_id` (`tenant_id`, `order_id`),
  KEY `idx_channel_id` (`tenant_id`, `channel_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='支付订单拓展 DO';

-- Entity: yudao-module-pay/src/main/java/cn/iocoder/yudao/module/pay/dal/dataobject/refund/PayRefundDO.java
-- Schema hints: yudao-module-pay/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pay_refund` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '退款单编号，数据库自增',
  `no` varchar(64) NULL COMMENT '外部退款号，根据规则生成',
  `app_id` bigint NULL COMMENT '应用编号',
  `channel_id` bigint NULL COMMENT '渠道编号',
  `channel_code` varchar(32) NULL COMMENT '渠道编码',
  `order_id` bigint NULL COMMENT '订单编号',
  `order_no` varchar(64) NULL COMMENT '支付订单编号',
  `user_id` bigint NULL DEFAULT NULL COMMENT '用户编号',
  `user_type` int NULL DEFAULT NULL COMMENT '用户类型',
  `merchant_order_id` varchar(64) NULL COMMENT '商户订单编号',
  `merchant_refund_id` varchar(64) NULL COMMENT '商户退款订单号',
  `notify_url` varchar(1024) NULL COMMENT '异步通知地址',
  `status` int NULL COMMENT '退款状态',
  `pay_price` int NULL COMMENT '支付金额，单位：分',
  `refund_price` int NULL COMMENT '退款金额，单位：分',
  `reason` varchar(256) NULL COMMENT '退款原因',
  `user_ip` varchar(50) NULL DEFAULT NULL COMMENT '用户 IP',
  `channel_order_no` varchar(64) NULL COMMENT '渠道订单号',
  `channel_refund_no` varchar(64) NULL DEFAULT NULL COMMENT '渠道退款单号',
  `success_time` datetime(6) NULL DEFAULT NULL COMMENT '退款成功时间',
  `channel_error_code` varchar(128) NULL DEFAULT NULL COMMENT '调用渠道的错误码',
  `channel_error_msg` varchar(256) NULL DEFAULT NULL COMMENT '调用渠道的错误提示',
  `channel_notify_data` varchar(1024) NULL COMMENT '支付渠道的同步/异步通知的内容',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_app_id` (`tenant_id`, `app_id`),
  KEY `idx_channel_id` (`tenant_id`, `channel_id`),
  KEY `idx_order_id` (`tenant_id`, `order_id`),
  KEY `idx_user_id` (`tenant_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='支付退款单 DO';

-- Entity: yudao-module-pay/src/main/java/cn/iocoder/yudao/module/pay/dal/dataobject/transfer/PayTransferDO.java
-- Schema hints: yudao-module-pay/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pay_transfer` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `no` varchar(64) NULL COMMENT '转账单号',
  `app_id` bigint NULL COMMENT '应用编号',
  `channel_id` bigint NULL COMMENT '转账渠道编号',
  `channel_code` varchar(32) NULL COMMENT '转账渠道编码',
  `user_id` bigint NULL DEFAULT NULL COMMENT '用户编号',
  `user_type` int NULL DEFAULT NULL COMMENT '用户类型',
  `merchant_transfer_id` varchar(64) NULL COMMENT '商户转账单编号',
  `subject` varchar(256) NULL COMMENT '转账标题',
  `price` int NULL COMMENT '转账金额，单位：分',
  `user_account` varchar(256) NULL COMMENT '收款人账号',
  `user_name` varchar(64) NULL DEFAULT NULL COMMENT '收款人姓名',
  `status` int NULL COMMENT '转账状态',
  `success_time` datetime(6) NULL DEFAULT NULL COMMENT '订单转账成功时间',
  `notify_url` varchar(1024) NULL DEFAULT NULL COMMENT '异步通知地址',
  `user_ip` varchar(50) NULL DEFAULT NULL COMMENT '用户 IP',
  `channel_extras` json NULL COMMENT '渠道的额外参数',
  `channel_transfer_no` varchar(64) NULL DEFAULT NULL COMMENT '渠道转账单号',
  `channel_error_code` varchar(128) NULL DEFAULT NULL COMMENT '调用渠道的错误码',
  `channel_error_msg` varchar(256) NULL DEFAULT NULL COMMENT '调用渠道的错误提示',
  `channel_notify_data` varchar(1024) NULL DEFAULT NULL COMMENT '渠道的同步/异步通知的内容',
  `channel_package_info` varchar(1024) NULL DEFAULT NULL COMMENT '渠道 package 信息',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_app_id` (`tenant_id`, `app_id`),
  KEY `idx_channel_id` (`tenant_id`, `channel_id`),
  KEY `idx_user_id` (`tenant_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='转账单 DO';

-- Entity: yudao-module-pay/src/main/java/cn/iocoder/yudao/module/pay/dal/dataobject/wallet/PayWalletDO.java
CREATE TABLE IF NOT EXISTS `pay_wallet` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `user_id` bigint NULL COMMENT '用户 id',
  `user_type` int NULL COMMENT '用户类型, 预留 多商户转帐可能需要用到',
  `balance` int NULL COMMENT '余额，单位分',
  `freeze_price` int NULL COMMENT '冻结金额，单位分',
  `total_expense` int NULL COMMENT '累计支出，单位分',
  `total_recharge` int NULL COMMENT '累计充值，单位分',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_user_id` (`tenant_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='会员钱包 DO';

-- Entity: yudao-module-pay/src/main/java/cn/iocoder/yudao/module/pay/dal/dataobject/wallet/PayWalletRechargeDO.java
CREATE TABLE IF NOT EXISTS `pay_wallet_recharge` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `wallet_id` bigint NULL COMMENT '钱包编号',
  `total_price` int NULL COMMENT '用户实际到账余额',
  `pay_price` int NULL COMMENT '实际支付金额',
  `bonus_price` int NULL COMMENT '钱包赠送金额',
  `package_id` bigint NULL COMMENT '充值套餐编号',
  `pay_status` bit(1) NULL COMMENT '是否已支付',
  `pay_order_id` bigint NULL COMMENT '支付订单编号',
  `pay_channel_code` longtext NULL COMMENT '支付成功的支付渠道',
  `pay_time` datetime(6) NULL COMMENT '订单支付时间',
  `pay_refund_id` bigint NULL COMMENT '支付退款单编号',
  `refund_total_price` int NULL COMMENT '退款金额，包含赠送金额',
  `refund_pay_price` int NULL COMMENT '退款支付金额',
  `refund_bonus_price` int NULL COMMENT '退款钱包赠送金额',
  `refund_time` datetime(6) NULL COMMENT '退款时间',
  `refund_status` int NULL COMMENT '退款状态',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_wallet_id` (`tenant_id`, `wallet_id`),
  KEY `idx_package_id` (`tenant_id`, `package_id`),
  KEY `idx_pay_order_id` (`tenant_id`, `pay_order_id`),
  KEY `idx_pay_refund_id` (`tenant_id`, `pay_refund_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='会员钱包充值';

-- Entity: yudao-module-pay/src/main/java/cn/iocoder/yudao/module/pay/dal/dataobject/wallet/PayWalletRechargePackageDO.java
CREATE TABLE IF NOT EXISTS `pay_wallet_recharge_package` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `name` longtext NULL COMMENT '套餐名',
  `pay_price` int NULL COMMENT '支付金额',
  `bonus_price` int NULL COMMENT '赠送金额',
  `status` int NULL COMMENT '状态',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='会员钱包充值套餐 DO';

-- Entity: yudao-module-pay/src/main/java/cn/iocoder/yudao/module/pay/dal/dataobject/wallet/PayWalletTransactionDO.java
CREATE TABLE IF NOT EXISTS `pay_wallet_transaction` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `no` longtext NULL COMMENT '流水号',
  `wallet_id` bigint NULL COMMENT '钱包编号',
  `biz_type` int NULL COMMENT '关联业务分类',
  `biz_id` longtext NULL COMMENT '关联业务编号',
  `title` longtext NULL COMMENT '流水说明',
  `price` int NULL COMMENT '交易金额，单位分',
  `balance` int NULL COMMENT '交易后余额，单位分',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_wallet_id` (`tenant_id`, `wallet_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='会员钱包流水 DO';
