-- Generated by sql/tools/schema/generate.py; see sql/mysql/modules/README.md.
-- Development schema reconstructed from entities; contains no seed data.
-- Existing tables are preserved; this is NOT an ALTER/migration script.
SET NAMES utf8mb4;

-- Entity: yudao-module-pms/src/main/java/cn/iocoder/yudao/module/pms/dal/dataobject/pm/iteration/PmsIterationDO.java
-- Schema hints: yudao-module-pms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pms_iteration` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '迭代编号',
  `project_id` bigint NULL COMMENT '项目编号',
  `name` varchar(100) NULL COMMENT '迭代名称',
  `owner_user_id` bigint NULL DEFAULT NULL COMMENT '负责人用户编号',
  `status` int NULL DEFAULT 1 COMMENT '迭代状态',
  `start_time` datetime(6) NULL DEFAULT NULL COMMENT '开始时间',
  `end_time` datetime(6) NULL DEFAULT NULL COMMENT '结束时间',
  `finish_time` datetime(6) NULL DEFAULT NULL COMMENT '完成时间',
  `target` varchar(255) NULL DEFAULT NULL COMMENT '迭代目标',
  `description` longtext NULL COMMENT '迭代描述',
  `sort` int NULL DEFAULT 0 COMMENT '显示顺序',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_project_id` (`tenant_id`, `project_id`),
  KEY `idx_owner_user_id` (`tenant_id`, `owner_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='PMS 项目迭代 DO';

-- Entity: yudao-module-pms/src/main/java/cn/iocoder/yudao/module/pms/dal/dataobject/kb/content/PmsKnowledgeContentPermissionDO.java
-- Schema hints: yudao-module-pms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pms_knowledge_content_permission` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '内容协作权限编号',
  `library_id` bigint NULL COMMENT '知识库编号',
  `open_status` bit(1) NULL DEFAULT b'1' COMMENT '是否对知识库可访问人公开',
  `open_level` int NULL DEFAULT 3 COMMENT '公开协作等级',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_library_id` (`tenant_id`, `library_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='PMS 知识内容协作权限 DO';

-- Entity: yudao-module-pms/src/main/java/cn/iocoder/yudao/module/pms/dal/dataobject/kb/content/PmsKnowledgeContentPermissionMemberDO.java
-- Schema hints: yudao-module-pms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pms_knowledge_content_permission_member` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '协作者编号',
  `permission_id` bigint NULL COMMENT '内容协作权限编号',
  `user_id` bigint NULL DEFAULT NULL COMMENT '后台用户编号',
  `dept_id` bigint NULL DEFAULT NULL COMMENT '部门编号',
  `level` int NULL COMMENT '协作等级',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_permission_id` (`tenant_id`, `permission_id`),
  KEY `idx_user_id` (`tenant_id`, `user_id`),
  KEY `idx_dept_id` (`tenant_id`, `dept_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='PMS 知识内容协作者 DO';

-- Entity: yudao-module-pms/src/main/java/cn/iocoder/yudao/module/pms/dal/dataobject/kb/content/PmsKnowledgeDocumentDO.java
-- Schema hints: yudao-module-pms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pms_knowledge_document` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '文档编号',
  `library_id` bigint NULL COMMENT '知识库编号',
  `permission_id` bigint NULL COMMENT '内容协作权限编号',
  `folder_id` bigint NULL DEFAULT 0 COMMENT '文件夹编号，0 表示不在文件夹中',
  `parent_id` bigint NULL DEFAULT 0 COMMENT '父文档编号，0 表示根文档',
  `title` varchar(255) NULL COMMENT '文档标题',
  `content` longtext NULL COMMENT '文档内容或文件地址',
  `type` int NULL COMMENT '文档类型',
  `file_type` varchar(50) NULL DEFAULT NULL COMMENT '文件类型',
  `file_size` bigint NULL DEFAULT NULL COMMENT '文件大小，单位：字节',
  `status` int NULL DEFAULT 1 COMMENT '文档状态',
  `label_ids` text NULL COMMENT '标签编号列表',
  `delete_user_id` bigint NULL DEFAULT NULL COMMENT '删除人用户编号',
  `delete_time` datetime(6) NULL DEFAULT NULL COMMENT '删除时间',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_library_id` (`tenant_id`, `library_id`),
  KEY `idx_permission_id` (`tenant_id`, `permission_id`),
  KEY `idx_folder_id` (`tenant_id`, `folder_id`),
  KEY `idx_parent_id` (`tenant_id`, `parent_id`),
  KEY `idx_delete_user_id` (`tenant_id`, `delete_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='PMS 知识库文档 DO';

-- Entity: yudao-module-pms/src/main/java/cn/iocoder/yudao/module/pms/dal/dataobject/kb/interaction/PmsKnowledgeDocumentCommentDO.java
-- Schema hints: yudao-module-pms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pms_knowledge_document_comment` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '评论编号',
  `document_id` bigint NULL COMMENT '文档编号',
  `user_id` bigint NULL COMMENT '评论人用户编号',
  `main_id` bigint NULL DEFAULT 0 COMMENT '主评论编号，0 表示主评论',
  `reply_user_id` bigint NULL DEFAULT NULL COMMENT '回复对象用户编号',
  `content` varchar(2000) NULL COMMENT '评论内容',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_document_id` (`tenant_id`, `document_id`),
  KEY `idx_user_id` (`tenant_id`, `user_id`),
  KEY `idx_main_id` (`tenant_id`, `main_id`),
  KEY `idx_reply_user_id` (`tenant_id`, `reply_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='PMS 知识库文档评论 DO';

-- Entity: yudao-module-pms/src/main/java/cn/iocoder/yudao/module/pms/dal/dataobject/kb/content/PmsKnowledgeDocumentLabelDO.java
-- Schema hints: yudao-module-pms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pms_knowledge_document_label` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '文档标签编号',
  `name` varchar(255) NULL COMMENT '标签名称',
  `color` varchar(20) NULL COMMENT '标签颜色',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='PMS 知识库文档标签 DO';

-- Entity: yudao-module-pms/src/main/java/cn/iocoder/yudao/module/pms/dal/dataobject/kb/interaction/PmsKnowledgeDocumentLikeDO.java
-- Schema hints: yudao-module-pms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pms_knowledge_document_like` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '点赞编号',
  `document_id` bigint NULL COMMENT '文档编号',
  `user_id` bigint NULL COMMENT '点赞人用户编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_like_tenant_document_create_time` (`tenant_id`, `document_id`, `create_time`),
  KEY `idx_like_tenant_user_document` (`tenant_id`, `user_id`, `document_id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='PMS 知识文档点赞 DO';

-- Entity: yudao-module-pms/src/main/java/cn/iocoder/yudao/module/pms/dal/dataobject/kb/interaction/PmsKnowledgeDocumentShareDO.java
-- Schema hints: yudao-module-pms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pms_knowledge_document_share` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '分享编号',
  `document_id` bigint NULL COMMENT '文档编号',
  `share_user_ids` json NULL COMMENT '内部分享成员用户编号列表',
  `token` varchar(64) NULL COMMENT '外部查看令牌',
  `status` int NULL DEFAULT 0 COMMENT '分享状态',
  `close_user_id` bigint NULL DEFAULT NULL COMMENT '关闭人用户编号',
  `close_time` datetime(6) NULL DEFAULT NULL COMMENT '关闭时间',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_1` (`token`),
  KEY `idx_share_tenant_document` (`tenant_id`, `document_id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_close_user_id` (`tenant_id`, `close_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='PMS 知识库文档分享 DO';

-- Entity: yudao-module-pms/src/main/java/cn/iocoder/yudao/module/pms/dal/dataobject/kb/interaction/PmsKnowledgeFavoriteDO.java
-- Schema hints: yudao-module-pms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pms_knowledge_favorite` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '收藏编号',
  `library_id` bigint NULL COMMENT '知识库编号',
  `type` int NULL COMMENT '收藏对象类型',
  `entity_id` bigint NULL COMMENT '收藏对象编号',
  `user_id` bigint NULL COMMENT '收藏人用户编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_favorite_tenant_user_create_time_id` (`tenant_id`, `user_id`, `create_time`, `id`),
  KEY `idx_favorite_tenant_user_library_create_time_id` (`tenant_id`, `user_id`, `library_id`, `create_time`, `id`),
  KEY `idx_favorite_tenant_user_type_entity` (`tenant_id`, `user_id`, `type`, `entity_id`),
  KEY `idx_favorite_tenant_library` (`tenant_id`, `library_id`),
  KEY `idx_favorite_tenant_type_entity` (`tenant_id`, `type`, `entity_id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_entity_id` (`tenant_id`, `entity_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='PMS 知识收藏（关注）DO';

-- Entity: yudao-module-pms/src/main/java/cn/iocoder/yudao/module/pms/dal/dataobject/kb/content/PmsKnowledgeFolderDO.java
-- Schema hints: yudao-module-pms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pms_knowledge_folder` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '文件夹编号',
  `library_id` bigint NULL COMMENT '知识库编号',
  `permission_id` bigint NULL COMMENT '内容协作权限编号',
  `parent_id` bigint NULL DEFAULT 0 COMMENT '父文件夹编号，0 表示根目录',
  `title` varchar(255) NULL COMMENT '文件夹标题',
  `status` int NULL DEFAULT 1 COMMENT '文件夹状态',
  `delete_user_id` bigint NULL DEFAULT NULL COMMENT '删除人用户编号',
  `delete_time` datetime(6) NULL DEFAULT NULL COMMENT '删除时间',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_library_id` (`tenant_id`, `library_id`),
  KEY `idx_permission_id` (`tenant_id`, `permission_id`),
  KEY `idx_parent_id` (`tenant_id`, `parent_id`),
  KEY `idx_delete_user_id` (`tenant_id`, `delete_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='PMS 知识库文件夹 DO';

-- Entity: yudao-module-pms/src/main/java/cn/iocoder/yudao/module/pms/dal/dataobject/kb/library/PmsKnowledgeGroupDO.java
-- Schema hints: yudao-module-pms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pms_knowledge_group` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '知识库分组编号',
  `user_id` bigint NULL COMMENT '后台用户编号',
  `name` varchar(100) NULL COMMENT '分组名称',
  `sort` int NULL DEFAULT 0 COMMENT '显示顺序',
  `type` int NULL DEFAULT 3 COMMENT '分组类型',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_group_tenant_user_type` (`tenant_id`, `user_id`, `type`),
  KEY `idx_group_tenant_user_sort` (`tenant_id`, `user_id`, `sort`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='PMS 个人知识库分组 DO';

-- Entity: yudao-module-pms/src/main/java/cn/iocoder/yudao/module/pms/dal/dataobject/kb/library/PmsKnowledgeGroupRelationDO.java
-- Schema hints: yudao-module-pms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pms_knowledge_group_relation` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `user_id` bigint NULL COMMENT '后台用户编号',
  `group_id` bigint NULL COMMENT '知识库分组编号',
  `library_id` bigint NULL COMMENT '知识库编号',
  `sort` int NULL DEFAULT 0 COMMENT '显示顺序',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_group_relation_tenant_user_group_library` (`tenant_id`, `user_id`, `group_id`, `library_id`),
  KEY `idx_group_relation_tenant_user_library` (`tenant_id`, `user_id`, `library_id`),
  KEY `idx_group_relation_tenant_library` (`tenant_id`, `library_id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_group_id` (`tenant_id`, `group_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='PMS 个人知识库分组关系 DO';

-- Entity: yudao-module-pms/src/main/java/cn/iocoder/yudao/module/pms/dal/dataobject/kb/library/PmsKnowledgeLibraryDO.java
-- Schema hints: yudao-module-pms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pms_knowledge_library` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '知识库编号',
  `name` varchar(255) NULL COMMENT '知识库名称',
  `description` varchar(300) NULL DEFAULT NULL COMMENT '知识库简介',
  `open_status` bit(1) NULL DEFAULT b'0' COMMENT '是否公开',
  `cover_url` varchar(255) NULL DEFAULT NULL COMMENT '知识库封面',
  `status` int NULL DEFAULT 1 COMMENT '知识库状态',
  `delete_user_id` bigint NULL DEFAULT NULL COMMENT '删除人用户编号',
  `delete_time` datetime(6) NULL DEFAULT NULL COMMENT '删除时间',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_delete_user_id` (`tenant_id`, `delete_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='PMS 知识库 DO';

-- Entity: yudao-module-pms/src/main/java/cn/iocoder/yudao/module/pms/dal/dataobject/kb/library/PmsKnowledgeLibraryMemberDO.java
-- Schema hints: yudao-module-pms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pms_knowledge_library_member` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '成员编号',
  `library_id` bigint NULL COMMENT '知识库编号',
  `user_id` bigint NULL DEFAULT NULL COMMENT '后台用户编号',
  `dept_id` bigint NULL DEFAULT NULL COMMENT '部门编号',
  `level` int NULL COMMENT '成员等级',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_library_id` (`tenant_id`, `library_id`),
  KEY `idx_user_id` (`tenant_id`, `user_id`),
  KEY `idx_dept_id` (`tenant_id`, `dept_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='PMS 知识库成员 DO';

-- Entity: yudao-module-pms/src/main/java/cn/iocoder/yudao/module/pms/dal/dataobject/kb/library/PmsKnowledgeLibraryTemplateDO.java
-- Schema hints: yudao-module-pms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pms_knowledge_library_template` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '模板编号',
  `name` varchar(100) NULL COMMENT '模板名称',
  `description` varchar(500) NULL DEFAULT NULL COMMENT '模板简介',
  `cover_url` varchar(255) NULL DEFAULT NULL COMMENT '模板封面地址',
  `status` int NULL DEFAULT 0 COMMENT '模板状态',
  `sort` int NULL DEFAULT 0 COMMENT '显示顺序',
  `documents` json NULL COMMENT '模板文档列表',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='PMS 知识库模板 DO';

-- Entity: yudao-module-pms/src/main/java/cn/iocoder/yudao/module/pms/dal/dataobject/kb/recycle/PmsKnowledgeRecycleRecordDO.java
-- Schema hints: yudao-module-pms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pms_knowledge_recycle_record` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '回收站记录编号',
  `library_id` bigint NULL COMMENT '知识库编号',
  `type` int NULL COMMENT '回收对象类型',
  `entity_id` bigint NULL COMMENT '回收对象编号',
  `name` varchar(255) NULL COMMENT '回收对象名称',
  `delete_user_id` bigint NULL COMMENT '删除人用户编号',
  `delete_time` datetime(6) NULL COMMENT '删除时间',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_type_entity` (`tenant_id`, `type`, `entity_id`),
  KEY `idx_tenant_delete_time_id` (`tenant_id`, `delete_time`, `id`),
  KEY `idx_tenant_library_delete_time` (`tenant_id`, `library_id`, `delete_time`),
  KEY `idx_tenant_delete_user_type` (`tenant_id`, `delete_user_id`, `type`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_entity_id` (`tenant_id`, `entity_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='PMS 知识库回收站记录 DO';

-- Entity: yudao-module-pms/src/main/java/cn/iocoder/yudao/module/pms/dal/dataobject/kb/interaction/PmsKnowledgeViewRecordDO.java
-- Schema hints: yudao-module-pms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pms_knowledge_view_record` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '浏览记录编号',
  `library_id` bigint NULL COMMENT '知识库编号',
  `type` int NULL COMMENT '浏览对象类型',
  `entity_id` bigint NULL COMMENT '浏览对象编号',
  `user_id` bigint NULL COMMENT '浏览人用户编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_view_tenant_user_create_time_id` (`tenant_id`, `user_id`, `create_time`, `id`),
  KEY `idx_view_tenant_user_type_entity` (`tenant_id`, `user_id`, `type`, `entity_id`),
  KEY `idx_view_tenant_library_create_time_id` (`tenant_id`, `library_id`, `create_time`, `id`),
  KEY `idx_view_tenant_type_entity` (`tenant_id`, `type`, `entity_id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_entity_id` (`tenant_id`, `entity_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='PMS 知识最近浏览记录 DO';

-- Entity: yudao-module-pms/src/main/java/cn/iocoder/yudao/module/pms/dal/dataobject/pm/project/PmsProjectDO.java
-- Schema hints: yudao-module-pms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pms_project` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '项目编号',
  `name` varchar(50) NULL COMMENT '项目名称',
  `status` int NULL DEFAULT 1 COMMENT '项目状态',
  `type` int NULL COMMENT '项目类型',
  `level` int NULL COMMENT '项目优先级',
  `description` longtext NULL COMMENT '项目描述',
  `open_status` bit(1) NULL DEFAULT b'1' COMMENT '是否公开',
  `icon` varchar(255) NULL DEFAULT NULL COMMENT '项目图标',
  `sort` int NULL DEFAULT NULL COMMENT '显示顺序',
  `start_time` datetime(6) NULL DEFAULT NULL COMMENT '开始时间',
  `end_time` datetime(6) NULL DEFAULT NULL COMMENT '截止时间',
  `archive_time` datetime(6) NULL DEFAULT NULL COMMENT '归档时间',
  `recycle_time` datetime(6) NULL DEFAULT NULL COMMENT '移入回收站时间',
  `access_time` datetime(6) NULL DEFAULT NULL COMMENT '最近访问时间',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='PMS 项目 DO';

-- Entity: yudao-module-pms/src/main/java/cn/iocoder/yudao/module/pms/dal/dataobject/pm/project/PmsProjectAnnouncementDO.java
-- Schema hints: yudao-module-pms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pms_project_announcement` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '公告编号',
  `project_id` bigint NULL COMMENT '项目编号',
  `content` longtext NULL COMMENT '公告内容',
  `file_urls` json NULL COMMENT '附件地址列表',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_project_id` (`tenant_id`, `project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='PMS 项目公告 DO';

-- Entity: yudao-module-pms/src/main/java/cn/iocoder/yudao/module/pms/dal/dataobject/pm/project/PmsProjectFavoriteDO.java
-- Schema hints: yudao-module-pms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pms_project_favorite` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '收藏编号',
  `project_id` bigint NULL COMMENT '项目编号',
  `user_id` bigint NULL COMMENT '收藏人用户编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_project_id` (`tenant_id`, `project_id`),
  KEY `idx_user_id` (`tenant_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='PMS 项目收藏 DO';

-- Entity: yudao-module-pms/src/main/java/cn/iocoder/yudao/module/pms/dal/dataobject/pm/project/PmsProjectGroupDO.java
-- Schema hints: yudao-module-pms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pms_project_group` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '分组编号',
  `user_id` bigint NULL COMMENT '后台用户编号',
  `name` varchar(100) NULL COMMENT '分组名称',
  `sort` int NULL DEFAULT 0 COMMENT '显示顺序',
  `type` int NULL DEFAULT 3 COMMENT '分组类型',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_user_id` (`tenant_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='PMS 项目分组 DO';

-- Entity: yudao-module-pms/src/main/java/cn/iocoder/yudao/module/pms/dal/dataobject/pm/project/PmsProjectGroupRelationDO.java
-- Schema hints: yudao-module-pms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pms_project_group_relation` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `user_id` bigint NULL COMMENT '后台用户编号',
  `group_id` bigint NULL COMMENT '项目分组编号',
  `project_id` bigint NULL COMMENT '项目编号',
  `sort` int NULL DEFAULT 0 COMMENT '显示顺序',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_user_id` (`tenant_id`, `user_id`),
  KEY `idx_group_id` (`tenant_id`, `group_id`),
  KEY `idx_project_id` (`tenant_id`, `project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='PMS 项目分组关系 DO';

-- Entity: yudao-module-pms/src/main/java/cn/iocoder/yudao/module/pms/dal/dataobject/pm/project/PmsProjectMemberDO.java
-- Schema hints: yudao-module-pms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pms_project_member` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `project_id` bigint NULL COMMENT '项目编号',
  `user_id` bigint NULL COMMENT '后台用户编号',
  `level` int NULL COMMENT '成员权限级别',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_project_id` (`tenant_id`, `project_id`),
  KEY `idx_user_id` (`tenant_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='PMS 项目成员 DO';

-- Entity: yudao-module-pms/src/main/java/cn/iocoder/yudao/module/pms/dal/dataobject/pm/project/PmsProjectTemplateDO.java
-- Schema hints: yudao-module-pms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pms_project_template` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '模板编号',
  `name` varchar(100) NULL COMMENT '模板名称',
  `description` varchar(500) NULL DEFAULT NULL COMMENT '模板描述',
  `project_type` int NULL COMMENT '项目类型',
  `status` int NULL DEFAULT 0 COMMENT '模板状态',
  `sort` int NULL DEFAULT 0 COMMENT '显示顺序',
  `item_types` json NULL COMMENT '启用的工作项类型列表',
  `statuses` json NULL COMMENT '工作项状态模板列表',
  `boards` json NULL COMMENT '看板列模板列表',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='PMS 项目模板 DO';

-- Entity: yudao-module-pms/src/main/java/cn/iocoder/yudao/module/pms/dal/dataobject/pm/workitem/PmsWorkItemDO.java
-- Schema hints: yudao-module-pms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pms_work_item` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '工作项编号',
  `project_id` bigint NULL COMMENT '项目编号',
  `type` int NULL COMMENT '工作项类型',
  `serial_number` int NULL COMMENT '项目内工作项序号',
  `name` varchar(100) NULL COMMENT '工作项标题',
  `description` longtext NULL COMMENT '工作项描述',
  `priority` int NULL COMMENT '优先级',
  `assignee_user_id` bigint NULL DEFAULT NULL COMMENT '负责人用户编号',
  `status_id` bigint NULL COMMENT '看板状态编号',
  `status` int NULL COMMENT '语义状态',
  `lifecycle_status` int NULL DEFAULT 1 COMMENT '生命周期状态',
  `archive_time` datetime(6) NULL DEFAULT NULL COMMENT '归档时间',
  `recycle_time` datetime(6) NULL DEFAULT NULL COMMENT '移入回收站时间',
  `iteration_id` bigint NULL DEFAULT NULL COMMENT '所属迭代编号',
  `parent_id` bigint NULL DEFAULT NULL COMMENT '父工作项编号',
  `related_requirement_id` bigint NULL DEFAULT NULL COMMENT '关联需求编号',
  `defect_type` int NULL DEFAULT NULL COMMENT '缺陷类型',
  `start_time` datetime(6) NULL DEFAULT NULL COMMENT '开始时间',
  `end_time` datetime(6) NULL DEFAULT NULL COMMENT '截止时间',
  `estimated_hours` int NULL DEFAULT NULL COMMENT '预估工时，单位：小时',
  `progress` int NULL DEFAULT 0 COMMENT '完成进度，取值范围 0-100',
  `file_urls` json NULL COMMENT '附件地址列表',
  `label_ids` json NULL COMMENT '标签编号列表',
  `sort` int NULL DEFAULT 0 COMMENT '看板内显示顺序',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_project_id` (`tenant_id`, `project_id`),
  KEY `idx_assignee_user_id` (`tenant_id`, `assignee_user_id`),
  KEY `idx_status_id` (`tenant_id`, `status_id`),
  KEY `idx_iteration_id` (`tenant_id`, `iteration_id`),
  KEY `idx_parent_id` (`tenant_id`, `parent_id`),
  KEY `idx_related_requirement_id` (`tenant_id`, `related_requirement_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='PMS 工作项 DO';

-- Entity: yudao-module-pms/src/main/java/cn/iocoder/yudao/module/pms/dal/dataobject/pm/workitem/PmsWorkItemActivityDO.java
-- Schema hints: yudao-module-pms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pms_work_item_activity` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '动态编号',
  `project_id` bigint NULL COMMENT '项目编号',
  `work_item_id` bigint NULL COMMENT '工作项编号',
  `operator_user_id` bigint NULL COMMENT '操作人用户编号',
  `content` varchar(500) NULL COMMENT '动态内容',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_project_id` (`tenant_id`, `project_id`),
  KEY `idx_work_item_id` (`tenant_id`, `work_item_id`),
  KEY `idx_operator_user_id` (`tenant_id`, `operator_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='PMS 工作项动态 DO';

-- Entity: yudao-module-pms/src/main/java/cn/iocoder/yudao/module/pms/dal/dataobject/pm/workitem/PmsWorkItemBoardDO.java
-- Schema hints: yudao-module-pms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pms_work_item_board` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '看板列编号',
  `project_id` bigint NULL COMMENT '项目编号',
  `work_item_type` int NULL COMMENT '工作项类型',
  `name` varchar(50) NULL COMMENT '看板列名称',
  `sort` int NULL DEFAULT 0 COMMENT '显示顺序',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_project_id` (`tenant_id`, `project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='PMS 工作项看板列 DO';

-- Entity: yudao-module-pms/src/main/java/cn/iocoder/yudao/module/pms/dal/dataobject/pm/workitem/PmsWorkItemCommentDO.java
-- Schema hints: yudao-module-pms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pms_work_item_comment` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '评论编号',
  `work_item_id` bigint NULL COMMENT '工作项编号',
  `user_id` bigint NULL COMMENT '评论人用户编号',
  `main_id` bigint NULL DEFAULT 0 COMMENT '主评论编号，#MAIN_ID_ROOT 表示主评论',
  `reply_user_id` bigint NULL DEFAULT NULL COMMENT '回复对象用户编号',
  `content` varchar(2000) NULL COMMENT '评论内容',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_work_item_id` (`tenant_id`, `work_item_id`),
  KEY `idx_user_id` (`tenant_id`, `user_id`),
  KEY `idx_main_id` (`tenant_id`, `main_id`),
  KEY `idx_reply_user_id` (`tenant_id`, `reply_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='PMS 工作项评论 DO';

-- Entity: yudao-module-pms/src/main/java/cn/iocoder/yudao/module/pms/dal/dataobject/pm/workitem/PmsWorkItemLabelDO.java
-- Schema hints: yudao-module-pms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pms_work_item_label` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '标签编号',
  `name` varchar(50) NULL COMMENT '标签名称',
  `color` varchar(20) NULL COMMENT '标签颜色',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='PMS 工作项标签 DO';

-- Entity: yudao-module-pms/src/main/java/cn/iocoder/yudao/module/pms/dal/dataobject/pm/workitem/PmsWorkItemMemberDO.java
-- Schema hints: yudao-module-pms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pms_work_item_member` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `project_id` bigint NULL COMMENT '项目编号',
  `work_item_id` bigint NULL COMMENT '工作项编号',
  `user_id` bigint NULL COMMENT '后台用户编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_project_id` (`tenant_id`, `project_id`),
  KEY `idx_work_item_id` (`tenant_id`, `work_item_id`),
  KEY `idx_user_id` (`tenant_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='PMS 工作项参与人 DO';

-- Entity: yudao-module-pms/src/main/java/cn/iocoder/yudao/module/pms/dal/dataobject/pm/workitem/PmsWorkItemStatusDO.java
-- Schema hints: yudao-module-pms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pms_work_item_status` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '状态编号',
  `project_id` bigint NULL COMMENT '项目编号',
  `work_item_type` int NULL COMMENT '工作项类型',
  `name` varchar(50) NULL COMMENT '状态名称',
  `status_type` int NULL COMMENT '语义状态',
  `description` varchar(255) NULL DEFAULT NULL COMMENT '状态描述',
  `board_name` varchar(50) NULL DEFAULT NULL COMMENT '所属看板列名称，为空时不在看板展示',
  `system_code` varchar(20) NULL DEFAULT NULL COMMENT '系统状态编码，仅默认状态使用，用于保证并发初始化幂等',
  `default_status` bit(1) NULL DEFAULT b'0' COMMENT '是否初始状态',
  `sort` int NULL DEFAULT 0 COMMENT '显示顺序',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_project_id` (`tenant_id`, `project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='PMS 工作项看板状态 DO';

-- Entity: yudao-module-pms/src/main/java/cn/iocoder/yudao/module/pms/dal/dataobject/pm/workitem/PmsWorkItemUserSortDO.java
-- Schema hints: yudao-module-pms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pms_work_item_user_sort` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `project_id` bigint NULL COMMENT '项目编号',
  `work_item_id` bigint NULL COMMENT '工作项编号',
  `user_id` bigint NULL COMMENT '用户编号',
  `sort` int NULL DEFAULT 0 COMMENT '显示顺序',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_project_id` (`tenant_id`, `project_id`),
  KEY `idx_work_item_id` (`tenant_id`, `work_item_id`),
  KEY `idx_user_id` (`tenant_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='PMS 工作项个人排序 DO';

-- Entity: yudao-module-pms/src/main/java/cn/iocoder/yudao/module/pms/dal/dataobject/pm/workitem/PmsWorkItemWorkLogDO.java
-- Schema hints: yudao-module-pms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `pms_work_item_work_log` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '工时记录编号',
  `project_id` bigint NULL COMMENT '项目编号',
  `work_item_id` bigint NULL COMMENT '工作项编号',
  `actual_hours` int NULL COMMENT '实际投入工时，单位：小时',
  `remaining_hours` int NULL DEFAULT 0 COMMENT '本次登记后的剩余工时，单位：小时',
  `description` varchar(500) NULL DEFAULT NULL COMMENT '工时说明',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_project_id` (`tenant_id`, `project_id`),
  KEY `idx_work_item_id` (`tenant_id`, `work_item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='PMS 工作项工时记录 DO';
