-- Generated by sql/tools/schema/generate.py; see sql/mysql/modules/README.md.
-- Development schema reconstructed from entities; contains no seed data.
-- Existing tables are preserved; this is NOT an ALTER/migration script.
SET NAMES utf8mb4;

-- Entity: yudao-module-report/src/main/java/cn/iocoder/yudao/module/report/dal/dataobject/goview/GoViewProjectDO.java
-- Schema hints: yudao-module-report/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `report_go_view_project` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号，数据库自增',
  `name` longtext NULL COMMENT '项目名称',
  `pic_url` longtext NULL COMMENT '预览图片 URL',
  `content` longtext NULL COMMENT '报表内容',
  `status` int NULL COMMENT '发布状态',
  `remark` longtext NULL COMMENT '项目备注',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='GoView 项目表';
