-- Generated by sql/tools/schema/generate.py; see sql/mysql/modules/README.md.
-- Development schema reconstructed from entities; contains no seed data.
-- Existing tables are preserved; this is NOT an ALTER/migration script.
SET NAMES utf8mb4;

-- Entity: yudao-module-wms/src/main/java/cn/iocoder/yudao/module/wms/dal/dataobject/order/check/WmsCheckOrderDO.java
-- Schema hints: yudao-module-wms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `wms_check_order` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键编号',
  `no` varchar(64) NULL COMMENT '盘库单号',
  `order_time` datetime(6) NULL COMMENT '单据日期',
  `status` int NULL DEFAULT '0' COMMENT '盘库状态',
  `remark` varchar(255) NULL DEFAULT NULL COMMENT '备注',
  `warehouse_id` bigint NULL COMMENT '仓库编号',
  `total_quantity` decimal(20,2) NULL DEFAULT '0' COMMENT '盈亏数量（实盘数量 - 账面数量）',
  `total_price` decimal(16,2) NULL DEFAULT NULL COMMENT '总金额（账面数量 * 单价）',
  `actual_price` decimal(16,2) NULL DEFAULT NULL COMMENT '实际金额（实盘数量 * 单价）',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_warehouse_id` (`tenant_id`, `warehouse_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='WMS 盘库单 DO';

-- Entity: yudao-module-wms/src/main/java/cn/iocoder/yudao/module/wms/dal/dataobject/order/check/WmsCheckOrderDetailDO.java
-- Schema hints: yudao-module-wms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `wms_check_order_detail` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键编号',
  `order_id` bigint NULL COMMENT '盘库单编号',
  `sku_id` bigint NULL COMMENT '商品 SKU 编号',
  `warehouse_id` bigint NULL COMMENT '仓库编号',
  `inventory_id` bigint NULL DEFAULT NULL COMMENT '库存编号',
  `receipt_time` datetime(6) NULL DEFAULT NULL COMMENT '入库时间',
  `quantity` decimal(20,2) NULL DEFAULT '0' COMMENT '账面数量',
  `check_quantity` decimal(20,2) NULL DEFAULT '0' COMMENT '实盘数量',
  `price` decimal(16,2) NULL DEFAULT NULL COMMENT '单价',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_order_id` (`tenant_id`, `order_id`),
  KEY `idx_sku_id` (`tenant_id`, `sku_id`),
  KEY `idx_warehouse_id` (`tenant_id`, `warehouse_id`),
  KEY `idx_inventory_id` (`tenant_id`, `inventory_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='WMS 盘库单明细 DO';

-- Entity: yudao-module-wms/src/main/java/cn/iocoder/yudao/module/wms/dal/dataobject/inventory/WmsInventoryDO.java
-- Schema hints: yudao-module-wms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `wms_inventory` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键编号',
  `sku_id` bigint NULL COMMENT '商品 SKU 编号',
  `warehouse_id` bigint NULL COMMENT '仓库编号',
  `quantity` decimal(20,2) NULL DEFAULT '0' COMMENT '库存数量',
  `remark` varchar(255) NULL DEFAULT NULL COMMENT '备注',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sku_id_warehouse_id` (`sku_id`, `warehouse_id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_sku_id` (`tenant_id`, `sku_id`),
  KEY `idx_warehouse_id` (`tenant_id`, `warehouse_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='WMS 库存 DO';

-- Entity: yudao-module-wms/src/main/java/cn/iocoder/yudao/module/wms/dal/dataobject/inventory/WmsInventoryHistoryDO.java
-- Schema hints: yudao-module-wms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `wms_inventory_history` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键编号',
  `warehouse_id` bigint NULL COMMENT '仓库编号',
  `sku_id` bigint NULL COMMENT '商品 SKU 编号',
  `quantity` decimal(20,2) NULL DEFAULT '0' COMMENT '库存变化数量',
  `before_quantity` decimal(20,2) NULL DEFAULT NULL COMMENT '变化前库存数量',
  `after_quantity` decimal(20,2) NULL DEFAULT NULL COMMENT '变化后库存数量',
  `price` decimal(16,2) NULL DEFAULT NULL COMMENT '单价',
  `total_price` decimal(16,2) NULL DEFAULT NULL COMMENT '库存变化金额',
  `remark` varchar(255) NULL DEFAULT NULL COMMENT '备注',
  `order_id` bigint NULL DEFAULT NULL COMMENT '单据编号',
  `order_no` varchar(64) NULL DEFAULT NULL COMMENT '单据号',
  `order_type` int NULL DEFAULT NULL COMMENT '单据类型',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_warehouse_id` (`tenant_id`, `warehouse_id`),
  KEY `idx_sku_id` (`tenant_id`, `sku_id`),
  KEY `idx_order_id` (`tenant_id`, `order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='WMS 库存流水 DO';

-- Entity: yudao-module-wms/src/main/java/cn/iocoder/yudao/module/wms/dal/dataobject/md/item/WmsItemDO.java
-- Schema hints: yudao-module-wms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `wms_item` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键编号',
  `code` varchar(20) NULL DEFAULT NULL COMMENT '商品编号',
  `name` varchar(60) NULL COMMENT '商品名称',
  `unit` varchar(20) NULL DEFAULT NULL COMMENT '单位',
  `category_id` bigint NULL COMMENT '商品分类编号',
  `brand_id` bigint NULL DEFAULT NULL COMMENT '商品品牌编号',
  `remark` varchar(255) NULL DEFAULT NULL COMMENT '备注',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_category_id` (`tenant_id`, `category_id`),
  KEY `idx_brand_id` (`tenant_id`, `brand_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='WMS 商品 DO';

-- Entity: yudao-module-wms/src/main/java/cn/iocoder/yudao/module/wms/dal/dataobject/md/item/WmsItemBrandDO.java
-- Schema hints: yudao-module-wms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `wms_item_brand` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键编号',
  `code` varchar(20) NULL COMMENT '品牌编号',
  `name` varchar(30) NULL COMMENT '品牌名称',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='WMS 商品品牌 DO';

-- Entity: yudao-module-wms/src/main/java/cn/iocoder/yudao/module/wms/dal/dataobject/md/item/WmsItemCategoryDO.java
-- Schema hints: yudao-module-wms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `wms_item_category` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键编号',
  `parent_id` bigint NULL DEFAULT '0' COMMENT '父级编号',
  `code` varchar(20) NULL COMMENT '分类编号',
  `name` varchar(30) NULL COMMENT '分类名称',
  `sort` int NULL DEFAULT '0' COMMENT '排序',
  `status` int NULL DEFAULT '1' COMMENT '状态',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_parent_id` (`tenant_id`, `parent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='WMS 商品分类 DO';

-- Entity: yudao-module-wms/src/main/java/cn/iocoder/yudao/module/wms/dal/dataobject/md/item/WmsItemSkuDO.java
-- Schema hints: yudao-module-wms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `wms_item_sku` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键编号',
  `name` varchar(255) NULL COMMENT '规格名称',
  `item_id` bigint NULL COMMENT '商品编号',
  `bar_code` varchar(64) NULL DEFAULT NULL COMMENT '条码',
  `code` varchar(64) NULL DEFAULT NULL COMMENT '规格编号',
  `length` decimal(10,1) NULL DEFAULT NULL COMMENT '长，单位 cm',
  `width` decimal(10,1) NULL DEFAULT NULL COMMENT '宽，单位 cm',
  `height` decimal(10,1) NULL DEFAULT NULL COMMENT '高，单位 cm',
  `gross_weight` decimal(10,3) NULL DEFAULT NULL COMMENT '毛重，单位 kg',
  `net_weight` decimal(10,3) NULL DEFAULT NULL COMMENT '净重，单位 kg',
  `cost_price` decimal(16,2) NULL DEFAULT NULL COMMENT '成本价，单位元',
  `selling_price` decimal(16,2) NULL DEFAULT NULL COMMENT '销售价，单位元',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_item_id` (`tenant_id`, `item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='WMS 商品 SKU DO';

-- Entity: yudao-module-wms/src/main/java/cn/iocoder/yudao/module/wms/dal/dataobject/md/merchant/WmsMerchantDO.java
-- Schema hints: yudao-module-wms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `wms_merchant` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键编号',
  `code` varchar(20) NULL COMMENT '往来企业编号',
  `name` varchar(60) NULL COMMENT '往来企业名称',
  `type` int NULL COMMENT '往来企业类型',
  `level` varchar(10) NULL DEFAULT NULL COMMENT '级别',
  `bank_name` varchar(255) NULL DEFAULT NULL COMMENT '开户行',
  `bank_account` varchar(40) NULL DEFAULT NULL COMMENT '银行账户',
  `address` varchar(200) NULL DEFAULT NULL COMMENT '地址',
  `mobile` varchar(13) NULL DEFAULT NULL COMMENT '手机号',
  `telephone` varchar(13) NULL DEFAULT NULL COMMENT '座机号',
  `contact` varchar(30) NULL DEFAULT NULL COMMENT '联系人',
  `email` varchar(50) NULL DEFAULT NULL COMMENT 'Email',
  `remark` varchar(255) NULL DEFAULT NULL COMMENT '备注',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='WMS 往来企业 DO';

-- Entity: yudao-module-wms/src/main/java/cn/iocoder/yudao/module/wms/dal/dataobject/order/movement/WmsMovementOrderDO.java
-- Schema hints: yudao-module-wms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `wms_movement_order` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键编号',
  `no` varchar(64) NULL COMMENT '移库单号',
  `order_time` datetime(6) NULL COMMENT '单据日期',
  `status` int NULL DEFAULT '0' COMMENT '移库状态',
  `remark` varchar(255) NULL DEFAULT NULL COMMENT '备注',
  `source_warehouse_id` bigint NULL COMMENT '来源仓库编号',
  `target_warehouse_id` bigint NULL COMMENT '目标仓库编号',
  `total_quantity` decimal(20,2) NULL DEFAULT '0' COMMENT '总数量',
  `total_price` decimal(16,2) NULL DEFAULT NULL COMMENT '总金额',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_source_warehouse_id` (`tenant_id`, `source_warehouse_id`),
  KEY `idx_target_warehouse_id` (`tenant_id`, `target_warehouse_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='WMS 移库单 DO';

-- Entity: yudao-module-wms/src/main/java/cn/iocoder/yudao/module/wms/dal/dataobject/order/movement/WmsMovementOrderDetailDO.java
-- Schema hints: yudao-module-wms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `wms_movement_order_detail` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键编号',
  `order_id` bigint NULL COMMENT '移库单编号',
  `sku_id` bigint NULL COMMENT '商品 SKU 编号',
  `source_warehouse_id` bigint NULL COMMENT '来源仓库编号',
  `target_warehouse_id` bigint NULL COMMENT '目标仓库编号',
  `quantity` decimal(20,2) NULL DEFAULT '0' COMMENT '移库数量',
  `price` decimal(16,2) NULL DEFAULT NULL COMMENT '单价',
  `total_price` decimal(16,2) NULL DEFAULT NULL COMMENT '行金额（数量 * 单价）',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_order_id` (`tenant_id`, `order_id`),
  KEY `idx_sku_id` (`tenant_id`, `sku_id`),
  KEY `idx_source_warehouse_id` (`tenant_id`, `source_warehouse_id`),
  KEY `idx_target_warehouse_id` (`tenant_id`, `target_warehouse_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='WMS 移库单明细 DO';

-- Entity: yudao-module-wms/src/main/java/cn/iocoder/yudao/module/wms/dal/dataobject/order/receipt/WmsReceiptOrderDO.java
-- Schema hints: yudao-module-wms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `wms_receipt_order` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键编号',
  `no` varchar(64) NULL COMMENT '入库单号',
  `type` int NULL COMMENT '入库类型',
  `order_time` datetime(6) NULL COMMENT '单据日期',
  `status` int NULL DEFAULT '0' COMMENT '入库状态',
  `biz_order_no` varchar(64) NULL DEFAULT NULL COMMENT '业务订单号',
  `merchant_id` bigint NULL DEFAULT NULL COMMENT '供应商编号',
  `remark` varchar(255) NULL DEFAULT NULL COMMENT '备注',
  `warehouse_id` bigint NULL COMMENT '仓库编号',
  `total_quantity` decimal(20,2) NULL DEFAULT '0' COMMENT '总数量',
  `total_price` decimal(16,2) NULL DEFAULT NULL COMMENT '总金额',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_merchant_id` (`tenant_id`, `merchant_id`),
  KEY `idx_warehouse_id` (`tenant_id`, `warehouse_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='WMS 入库单 DO';

-- Entity: yudao-module-wms/src/main/java/cn/iocoder/yudao/module/wms/dal/dataobject/order/receipt/WmsReceiptOrderDetailDO.java
-- Schema hints: yudao-module-wms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `wms_receipt_order_detail` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键编号',
  `order_id` bigint NULL COMMENT '入库单编号',
  `sku_id` bigint NULL COMMENT '商品 SKU 编号',
  `warehouse_id` bigint NULL COMMENT '仓库编号',
  `quantity` decimal(20,2) NULL DEFAULT '0' COMMENT '入库数量',
  `price` decimal(16,2) NULL DEFAULT NULL COMMENT '单价',
  `total_price` decimal(16,2) NULL DEFAULT NULL COMMENT '行金额（数量 * 单价）',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_order_id` (`tenant_id`, `order_id`),
  KEY `idx_sku_id` (`tenant_id`, `sku_id`),
  KEY `idx_warehouse_id` (`tenant_id`, `warehouse_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='WMS 入库单明细 DO';

-- Entity: yudao-module-wms/src/main/java/cn/iocoder/yudao/module/wms/dal/dataobject/order/shipment/WmsShipmentOrderDO.java
-- Schema hints: yudao-module-wms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `wms_shipment_order` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键编号',
  `no` varchar(64) NULL COMMENT '出库单号',
  `type` int NULL COMMENT '出库类型',
  `order_time` datetime(6) NULL COMMENT '单据日期',
  `status` int NULL DEFAULT '0' COMMENT '出库状态',
  `biz_order_no` varchar(64) NULL DEFAULT NULL COMMENT '业务订单号',
  `merchant_id` bigint NULL DEFAULT NULL COMMENT '客户编号',
  `remark` varchar(255) NULL DEFAULT NULL COMMENT '备注',
  `warehouse_id` bigint NULL COMMENT '仓库编号',
  `total_quantity` decimal(20,2) NULL DEFAULT '0' COMMENT '总数量',
  `total_price` decimal(16,2) NULL DEFAULT NULL COMMENT '总金额',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_merchant_id` (`tenant_id`, `merchant_id`),
  KEY `idx_warehouse_id` (`tenant_id`, `warehouse_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='WMS 出库单 DO';

-- Entity: yudao-module-wms/src/main/java/cn/iocoder/yudao/module/wms/dal/dataobject/order/shipment/WmsShipmentOrderDetailDO.java
-- Schema hints: yudao-module-wms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `wms_shipment_order_detail` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键编号',
  `order_id` bigint NULL COMMENT '出库单编号',
  `sku_id` bigint NULL COMMENT '商品 SKU 编号',
  `warehouse_id` bigint NULL COMMENT '仓库编号',
  `quantity` decimal(20,2) NULL DEFAULT '0' COMMENT '出库数量',
  `price` decimal(16,2) NULL DEFAULT NULL COMMENT '单价',
  `total_price` decimal(16,2) NULL DEFAULT NULL COMMENT '行金额（数量 * 单价）',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_order_id` (`tenant_id`, `order_id`),
  KEY `idx_sku_id` (`tenant_id`, `sku_id`),
  KEY `idx_warehouse_id` (`tenant_id`, `warehouse_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='WMS 出库单明细 DO';

-- Entity: yudao-module-wms/src/main/java/cn/iocoder/yudao/module/wms/dal/dataobject/md/warehouse/WmsWarehouseDO.java
-- Schema hints: yudao-module-wms/src/test/resources/sql/create_tables.sql
CREATE TABLE IF NOT EXISTS `wms_warehouse` (
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者，目前使用 SysUser 的 id 编号',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者，目前使用 SysUser 的 id 编号',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键编号',
  `code` varchar(20) NULL COMMENT '仓库编号',
  `name` varchar(50) NULL COMMENT '名称',
  `remark` varchar(255) NULL DEFAULT NULL COMMENT '备注',
  `sort` int NULL DEFAULT '0' COMMENT '排序',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号（租户拦截器写入）',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='WMS 仓库 DO';
